#region Header

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#endregion

using System;
using System.Drawing;
using Kiss.Interfaces.UI;
using KiSS4.Common.Report;
using KiSS4.DB;
using KiSS4.Gui;
using KiSS4.Messages;

namespace KiSS4.Vormundschaft.ZH
{
    public class CtlKgBilanzErfolg : KiSS4.Common.KissSearchUserControl
    {
        #region Fields

        private int baPersonID = 0;
        private KiSS4.Gui.KissButton btnCollapse;
        private KiSS4.Gui.KissButton btnDrucken;
        private KiSS4.Gui.KissButton btnExpand;
        private DevExpress.XtraGrid.Columns.GridColumn colBis;
        private DevExpress.XtraTreeList.Columns.TreeListColumn colKonto;
        private DevExpress.XtraTreeList.Columns.TreeListColumn colSaldo;
        private DevExpress.XtraGrid.Columns.GridColumn colStatus;
        private DevExpress.XtraTreeList.Columns.TreeListColumn colTotal;
        private DevExpress.XtraTreeList.Columns.TreeListColumn colUmsatz;
        private DevExpress.XtraGrid.Columns.GridColumn colVon;
        private DevExpress.XtraTreeList.Columns.TreeListColumn colVorsaldo;
        private System.ComponentModel.IContainer components;
        private KiSS4.Gui.KissTextEdit edtAdresse;
        private KiSS4.Gui.KissTextEdit edtBaPersonID;
        private KiSS4.Gui.KissMemoEdit edtBemerkung;
        private KiSS4.Gui.KissDateEdit edtDatumBis;
        private KiSS4.Gui.KissDateEdit edtDatumVon;
        private KiSS4.Gui.KissCheckEdit edtKeinAbrechnungsText;
        private KiSS4.Gui.KissTextEdit edtMA;
        private KiSS4.Gui.KissButtonEdit edtMandant;
        private KiSS4.Gui.KissTextEdit edtMT;
        private System.Windows.Forms.CheckBox edtNurMitBuchungen;
        private System.Windows.Forms.CheckBox edtOhneKtoGruppen;
        private KiSS4.Gui.KissMemoEdit edtPM;
        private int faLeistungID = 0;
        private KiSS4.Gui.KissGrid grdPeriode;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView2;
        private KiSS4.Gui.KissGroupBox groupBox1;
        private System.Windows.Forms.ImageList imageList1;
        private KiSS4.Gui.KissLabel kissLabel1;
        private KiSS4.Gui.KissLabel kissLabel2;
        private KiSS4.Gui.KissLabel kissLabel3;
        private KiSS4.Gui.KissLabel kissLabel4;
        private KiSS4.Gui.KissLabel kissLabel5;
        private KiSS4.Gui.KissLabel label1;
        private KiSS4.Gui.KissLabel label10;
        private KiSS4.Gui.KissLabel label40;
        private KiSS4.Gui.KissLabel lblMandant;
        private KiSS4.Gui.KissLabel lblTitel;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.PictureBox picTitel;
        private KiSS4.DB.SqlQuery qryBilanz;
        private KiSS4.DB.SqlQuery qryPeriode;
        private KiSS4.Gui.KissTree treKgBilanz;

        #endregion

        #region Constructors

        public CtlKgBilanzErfolg()
        {
            this.InitializeComponent();
        }

        #endregion

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CtlKgBilanzErfolg));
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject3 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject2 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject1 = new DevExpress.Utils.SerializableAppearanceObject();
            this.treKgBilanz = new KiSS4.Gui.KissTree();
            this.colKonto = new DevExpress.XtraTreeList.Columns.TreeListColumn();
            this.colVorsaldo = new DevExpress.XtraTreeList.Columns.TreeListColumn();
            this.colUmsatz = new DevExpress.XtraTreeList.Columns.TreeListColumn();
            this.colSaldo = new DevExpress.XtraTreeList.Columns.TreeListColumn();
            this.colTotal = new DevExpress.XtraTreeList.Columns.TreeListColumn();
            this.qryBilanz = new KiSS4.DB.SqlQuery(this.components);
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            this.lblMandant = new KiSS4.Gui.KissLabel();
            this.btnExpand = new KiSS4.Gui.KissButton();
            this.btnCollapse = new KiSS4.Gui.KissButton();
            this.edtMandant = new KiSS4.Gui.KissButtonEdit();
            this.grdPeriode = new KiSS4.Gui.KissGrid();
            this.qryPeriode = new KiSS4.DB.SqlQuery(this.components);
            this.gridView2 = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.colVon = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colBis = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colStatus = new DevExpress.XtraGrid.Columns.GridColumn();
            this.edtDatumVon = new KiSS4.Gui.KissDateEdit();
            this.edtDatumBis = new KiSS4.Gui.KissDateEdit();
            this.edtNurMitBuchungen = new System.Windows.Forms.CheckBox();
            this.edtOhneKtoGruppen = new System.Windows.Forms.CheckBox();
            this.groupBox1 = new KiSS4.Gui.KissGroupBox();
            this.edtKeinAbrechnungsText = new KiSS4.Gui.KissCheckEdit();
            this.btnDrucken = new KiSS4.Gui.KissButton();
            this.kissLabel5 = new KiSS4.Gui.KissLabel();
            this.edtMA = new KiSS4.Gui.KissTextEdit();
            this.kissLabel4 = new KiSS4.Gui.KissLabel();
            this.edtPM = new KiSS4.Gui.KissMemoEdit();
            this.kissLabel3 = new KiSS4.Gui.KissLabel();
            this.edtBemerkung = new KiSS4.Gui.KissMemoEdit();
            this.kissLabel1 = new KiSS4.Gui.KissLabel();
            this.label40 = new KiSS4.Gui.KissLabel();
            this.edtAdresse = new KiSS4.Gui.KissTextEdit();
            this.edtBaPersonID = new KiSS4.Gui.KissTextEdit();
            this.edtMT = new KiSS4.Gui.KissTextEdit();
            this.label10 = new KiSS4.Gui.KissLabel();
            this.label1 = new KiSS4.Gui.KissLabel();
            this.kissLabel2 = new KiSS4.Gui.KissLabel();
            this.panel1 = new System.Windows.Forms.Panel();
            this.picTitel = new System.Windows.Forms.PictureBox();
            this.lblTitel = new KiSS4.Gui.KissLabel();
            this.tabControlSearch.SuspendLayout();
            this.tpgListe.SuspendLayout();
            this.tpgSuchen.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.treKgBilanz)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.qryBilanz)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblMandant)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtMandant.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdPeriode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.qryPeriode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtDatumVon.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtDatumBis.Properties)).BeginInit();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.edtKeinAbrechnungsText.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtMA.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtPM.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtBemerkung.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.label40)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtAdresse.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtBaPersonID.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtMT.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.label10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.label1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel2)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picTitel)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblTitel)).BeginInit();
            this.SuspendLayout();
            //
            // searchTitle
            //
            this.searchTitle.Size = new System.Drawing.Size(706, 24);
            //
            // tabControlSearch
            //
            this.tabControlSearch.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tabControlSearch.Location = new System.Drawing.Point(3, 30);
            this.tabControlSearch.SelectedTabIndex = 1;
            this.tabControlSearch.Size = new System.Drawing.Size(730, 485);
            //
            // tpgListe
            //
            this.tpgListe.Controls.Add(this.btnCollapse);
            this.tpgListe.Controls.Add(this.btnExpand);
            this.tpgListe.Controls.Add(this.lblMandant);
            this.tpgListe.Controls.Add(this.treKgBilanz);
            this.tpgListe.Size = new System.Drawing.Size(718, 447);
            this.tpgListe.Title = "Liste";
            //
            // tpgSuchen
            //
            this.tpgSuchen.Controls.Add(this.kissLabel2);
            this.tpgSuchen.Controls.Add(this.label1);
            this.tpgSuchen.Controls.Add(this.label10);
            this.tpgSuchen.Controls.Add(this.edtMT);
            this.tpgSuchen.Controls.Add(this.edtBaPersonID);
            this.tpgSuchen.Controls.Add(this.edtAdresse);
            this.tpgSuchen.Controls.Add(this.label40);
            this.tpgSuchen.Controls.Add(this.kissLabel1);
            this.tpgSuchen.Controls.Add(this.groupBox1);
            this.tpgSuchen.Controls.Add(this.edtOhneKtoGruppen);
            this.tpgSuchen.Controls.Add(this.edtNurMitBuchungen);
            this.tpgSuchen.Controls.Add(this.edtDatumBis);
            this.tpgSuchen.Controls.Add(this.edtDatumVon);
            this.tpgSuchen.Controls.Add(this.grdPeriode);
            this.tpgSuchen.Controls.Add(this.edtMandant);
            this.tpgSuchen.Size = new System.Drawing.Size(718, 447);
            this.tpgSuchen.Title = "Suche";
            this.tpgSuchen.Controls.SetChildIndex(this.edtMandant, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.searchTitle, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.grdPeriode, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtDatumVon, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtDatumBis, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtNurMitBuchungen, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtOhneKtoGruppen, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.groupBox1, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.kissLabel1, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.label40, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtAdresse, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtBaPersonID, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtMT, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.label10, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.label1, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.kissLabel2, 0);
            //
            // treKgBilanz
            //
            this.treKgBilanz.AllowSortTree = true;
            this.treKgBilanz.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.treKgBilanz.Appearance.Empty.BackColor = System.Drawing.Color.Transparent;
            this.treKgBilanz.Appearance.Empty.ForeColor = System.Drawing.Color.White;
            this.treKgBilanz.Appearance.Empty.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.Empty.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.EvenRow.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(236)))), ((int)(((byte)(215)))));
            this.treKgBilanz.Appearance.EvenRow.ForeColor = System.Drawing.Color.Black;
            this.treKgBilanz.Appearance.EvenRow.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.EvenRow.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.FocusedCell.BackColor = System.Drawing.Color.Transparent;
            this.treKgBilanz.Appearance.FocusedCell.ForeColor = System.Drawing.Color.White;
            this.treKgBilanz.Appearance.FocusedCell.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.FocusedCell.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.FocusedRow.ForeColor = System.Drawing.Color.White;
            this.treKgBilanz.Appearance.FocusedRow.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.FooterPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(216)))), ((int)(((byte)(174)))));
            this.treKgBilanz.Appearance.FooterPanel.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.treKgBilanz.Appearance.FooterPanel.ForeColor = System.Drawing.Color.Black;
            this.treKgBilanz.Appearance.FooterPanel.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.FooterPanel.Options.UseFont = true;
            this.treKgBilanz.Appearance.FooterPanel.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.GroupButton.BackColor = System.Drawing.Color.Transparent;
            this.treKgBilanz.Appearance.GroupButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.treKgBilanz.Appearance.GroupButton.ForeColor = System.Drawing.Color.Black;
            this.treKgBilanz.Appearance.GroupButton.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.GroupButton.Options.UseFont = true;
            this.treKgBilanz.Appearance.GroupButton.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.GroupFooter.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(226)))), ((int)(((byte)(184)))));
            this.treKgBilanz.Appearance.GroupFooter.ForeColor = System.Drawing.Color.Black;
            this.treKgBilanz.Appearance.GroupFooter.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.GroupFooter.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.HeaderPanel.BackColor = System.Drawing.Color.Tan;
            this.treKgBilanz.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Bold);
            this.treKgBilanz.Appearance.HeaderPanel.ForeColor = System.Drawing.Color.Black;
            this.treKgBilanz.Appearance.HeaderPanel.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.HeaderPanel.Options.UseFont = true;
            this.treKgBilanz.Appearance.HeaderPanel.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.HideSelectionRow.BackColor = System.Drawing.Color.PowderBlue;
            this.treKgBilanz.Appearance.HideSelectionRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.treKgBilanz.Appearance.HideSelectionRow.ForeColor = System.Drawing.Color.Black;
            this.treKgBilanz.Appearance.HideSelectionRow.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.HideSelectionRow.Options.UseFont = true;
            this.treKgBilanz.Appearance.HideSelectionRow.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.HorzLine.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(216)))), ((int)(((byte)(174)))));
            this.treKgBilanz.Appearance.HorzLine.ForeColor = System.Drawing.Color.Red;
            this.treKgBilanz.Appearance.HorzLine.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.HorzLine.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.OddRow.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(227)))), ((int)(((byte)(215)))));
            this.treKgBilanz.Appearance.OddRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.treKgBilanz.Appearance.OddRow.ForeColor = System.Drawing.Color.Black;
            this.treKgBilanz.Appearance.OddRow.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.OddRow.Options.UseFont = true;
            this.treKgBilanz.Appearance.OddRow.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.Preview.BackColor = System.Drawing.Color.White;
            this.treKgBilanz.Appearance.Preview.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.treKgBilanz.Appearance.Preview.ForeColor = System.Drawing.Color.Maroon;
            this.treKgBilanz.Appearance.Preview.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.Preview.Options.UseFont = true;
            this.treKgBilanz.Appearance.Preview.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.Row.BackColor = System.Drawing.Color.Transparent;
            this.treKgBilanz.Appearance.Row.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.treKgBilanz.Appearance.Row.ForeColor = System.Drawing.Color.Black;
            this.treKgBilanz.Appearance.Row.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.Row.Options.UseFont = true;
            this.treKgBilanz.Appearance.Row.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.SelectedRow.ForeColor = System.Drawing.Color.White;
            this.treKgBilanz.Appearance.SelectedRow.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.TreeLine.BackColor = System.Drawing.Color.Gray;
            this.treKgBilanz.Appearance.TreeLine.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.VertLine.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(216)))), ((int)(((byte)(174)))));
            this.treKgBilanz.Appearance.VertLine.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(166)))), ((int)(((byte)(70)))));
            this.treKgBilanz.Appearance.VertLine.Options.UseBackColor = true;
            this.treKgBilanz.Appearance.VertLine.Options.UseForeColor = true;
            this.treKgBilanz.Appearance.VertLine.Options.UseTextOptions = true;
            this.treKgBilanz.Appearance.VertLine.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.treKgBilanz.Columns.AddRange(new DevExpress.XtraTreeList.Columns.TreeListColumn[] {
            this.colKonto,
            this.colVorsaldo,
            this.colUmsatz,
            this.colSaldo,
            this.colTotal});
            this.treKgBilanz.DataSource = this.qryBilanz;
            this.treKgBilanz.ImageIndexFieldName = "IconIndex";
            this.treKgBilanz.KeyFieldName = "KgKontoID";
            this.treKgBilanz.Location = new System.Drawing.Point(2, 33);
            this.treKgBilanz.Name = "treKgBilanz";
            this.treKgBilanz.OptionsBehavior.AutoSelectAllInEditor = false;
            this.treKgBilanz.OptionsBehavior.CloseEditorOnLostFocus = false;
            this.treKgBilanz.OptionsBehavior.Editable = false;
            this.treKgBilanz.OptionsBehavior.KeepSelectedOnClick = false;
            this.treKgBilanz.OptionsBehavior.MoveOnEdit = false;
            this.treKgBilanz.OptionsMenu.EnableColumnMenu = false;
            this.treKgBilanz.OptionsMenu.EnableFooterMenu = false;
            this.treKgBilanz.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.treKgBilanz.OptionsView.AutoWidth = false;
            this.treKgBilanz.OptionsView.EnableAppearanceEvenRow = true;
            this.treKgBilanz.OptionsView.EnableAppearanceOddRow = true;
            this.treKgBilanz.OptionsView.ShowIndicator = false;
            this.treKgBilanz.ParentFieldName = "GruppeKontoID";
            this.treKgBilanz.SelectImageList = this.imageList1;
            this.treKgBilanz.Size = new System.Drawing.Size(710, 414);
            this.treKgBilanz.TabIndex = 3;
            //
            // colKonto
            //
            this.colKonto.Caption = "Konto";
            this.colKonto.FieldName = "Konto";
            this.colKonto.MinWidth = 27;
            this.colKonto.Name = "colKonto";
            this.colKonto.OptionsColumn.AllowSort = false;
            this.colKonto.VisibleIndex = 0;
            this.colKonto.Width = 325;
            //
            // colVorsaldo
            //
            this.colVorsaldo.AppearanceCell.Options.UseTextOptions = true;
            this.colVorsaldo.AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            this.colVorsaldo.Caption = "Vorsaldo";
            this.colVorsaldo.FieldName = "Vorsaldo";
            this.colVorsaldo.Format.FormatString = "#,##0.00";
            this.colVorsaldo.Format.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.colVorsaldo.Name = "colVorsaldo";
            this.colVorsaldo.OptionsColumn.AllowSort = false;
            this.colVorsaldo.VisibleIndex = 1;
            this.colVorsaldo.Width = 80;
            //
            // colUmsatz
            //
            this.colUmsatz.Caption = "Umsatz";
            this.colUmsatz.FieldName = "Umsatz";
            this.colUmsatz.Format.FormatString = "#,##0.00";
            this.colUmsatz.Format.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.colUmsatz.Name = "colUmsatz";
            this.colUmsatz.OptionsColumn.AllowSort = false;
            this.colUmsatz.VisibleIndex = 2;
            this.colUmsatz.Width = 80;
            //
            // colSaldo
            //
            this.colSaldo.Caption = "Saldo";
            this.colSaldo.FieldName = "Saldo";
            this.colSaldo.Format.FormatString = "#,##0.00";
            this.colSaldo.Format.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.colSaldo.Name = "colSaldo";
            this.colSaldo.OptionsColumn.AllowSort = false;
            this.colSaldo.VisibleIndex = 3;
            this.colSaldo.Width = 80;
            //
            // colTotal
            //
            this.colTotal.AppearanceCell.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
            this.colTotal.AppearanceCell.Options.UseFont = true;
            this.colTotal.Caption = "Total";
            this.colTotal.FieldName = "Total";
            this.colTotal.Format.FormatString = "#,##0.00";
            this.colTotal.Format.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.colTotal.Name = "colTotal";
            this.colTotal.OptionsColumn.AllowSort = false;
            this.colTotal.VisibleIndex = 4;
            this.colTotal.Width = 90;
            //
            // qryBilanz
            //
            this.qryBilanz.HostControl = this;
            this.qryBilanz.SelectStatement = "SELECT 1 WHERE 1 = 0";
            //
            // imageList1
            //
            this.imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList1.Images.SetKeyName(0, "");
            this.imageList1.Images.SetKeyName(1, "");
            //
            // lblMandant
            //
            this.lblMandant.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblMandant.LabelStyle = KiSS4.Gui.LabelStyleType.TitleLabel;
            this.lblMandant.Location = new System.Drawing.Point(6, 7);
            this.lblMandant.Name = "lblMandant";
            this.lblMandant.Size = new System.Drawing.Size(632, 19);
            this.lblMandant.TabIndex = 4;
            this.lblMandant.Text = "Person mit zivilrechtlicher Massnahme";
            this.lblMandant.UseCompatibleTextRendering = true;
            //
            // btnExpand
            //
            this.btnExpand.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExpand.Image = ((System.Drawing.Image)(resources.GetObject("btnExpand.Image")));
            this.btnExpand.Location = new System.Drawing.Point(628, 3);
            this.btnExpand.Name = "btnExpand";
            this.btnExpand.Size = new System.Drawing.Size(24, 24);
            this.btnExpand.TabIndex = 313;
            this.btnExpand.UseCompatibleTextRendering = true;
            this.btnExpand.UseVisualStyleBackColor = false;
            this.btnExpand.Click += new System.EventHandler(this.btnExpand_Click);
            //
            // btnCollapse
            //
            this.btnCollapse.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCollapse.Image = ((System.Drawing.Image)(resources.GetObject("btnCollapse.Image")));
            this.btnCollapse.Location = new System.Drawing.Point(658, 3);
            this.btnCollapse.Name = "btnCollapse";
            this.btnCollapse.Size = new System.Drawing.Size(24, 24);
            this.btnCollapse.TabIndex = 314;
            this.btnCollapse.UseCompatibleTextRendering = true;
            this.btnCollapse.UseVisualStyleBackColor = false;
            this.btnCollapse.Click += new System.EventHandler(this.btnCollapse_Click);
            //
            // edtMandant
            //
            this.edtMandant.Location = new System.Drawing.Point(135, 45);
            this.edtMandant.Name = "edtMandant";
            this.edtMandant.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtMandant.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtMandant.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtMandant.Properties.Appearance.Options.UseBackColor = true;
            this.edtMandant.Properties.Appearance.Options.UseBorderColor = true;
            this.edtMandant.Properties.Appearance.Options.UseFont = true;
            this.edtMandant.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject3.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject3.Options.UseBackColor = true;
            this.edtMandant.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Ellipsis, "", -1, true, true, false, DevExpress.Utils.HorzAlignment.Center, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject3)});
            this.edtMandant.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtMandant.Properties.Name = "editMandant.Properties";
            this.edtMandant.SearchStringWhitelist = new string[] {
        ".",
        "*",
        "%"};
            this.edtMandant.Size = new System.Drawing.Size(216, 24);
            this.edtMandant.TabIndex = 0;
            this.edtMandant.UserModifiedFld += new KiSS4.Gui.UserModifiedFldEventHandler(this.edtMandant_UserModifiedFld);
            //
            // grdPeriode
            //
            this.grdPeriode.DataSource = this.qryPeriode;
            //
            //
            //
            this.grdPeriode.EmbeddedNavigator.Name = "gridPeriode.EmbeddedNavigator";
            this.grdPeriode.GridStyle = KiSS4.Gui.GridStyleType.ReadOnly;
            this.grdPeriode.Location = new System.Drawing.Point(427, 45);
            this.grdPeriode.MainView = this.gridView2;
            this.grdPeriode.Name = "grdPeriode";
            this.grdPeriode.Size = new System.Drawing.Size(283, 85);
            this.grdPeriode.TabIndex = 1;
            this.grdPeriode.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridView2});
            //
            // qryPeriode
            //
            this.qryPeriode.HostControl = this;
            this.qryPeriode.SelectStatement = resources.GetString("qryPeriode.SelectStatement");
            this.qryPeriode.PositionChanged += new System.EventHandler(this.qryPeriode_PositionChanged);
            //
            // gridView2
            //
            this.gridView2.Appearance.Empty.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.gridView2.Appearance.Empty.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView2.Appearance.Empty.Options.UseBackColor = true;
            this.gridView2.Appearance.Empty.Options.UseFont = true;
            this.gridView2.Appearance.EvenRow.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(227)))), ((int)(((byte)(215)))));
            this.gridView2.Appearance.EvenRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView2.Appearance.EvenRow.Options.UseBackColor = true;
            this.gridView2.Appearance.EvenRow.Options.UseFont = true;
            this.gridView2.Appearance.FocusedCell.BackColor = System.Drawing.SystemColors.Highlight;
            this.gridView2.Appearance.FocusedCell.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView2.Appearance.FocusedCell.ForeColor = System.Drawing.Color.White;
            this.gridView2.Appearance.FocusedCell.Options.UseBackColor = true;
            this.gridView2.Appearance.FocusedCell.Options.UseFont = true;
            this.gridView2.Appearance.FocusedCell.Options.UseForeColor = true;
            this.gridView2.Appearance.FocusedRow.BackColor = System.Drawing.SystemColors.Highlight;
            this.gridView2.Appearance.FocusedRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView2.Appearance.FocusedRow.ForeColor = System.Drawing.Color.White;
            this.gridView2.Appearance.FocusedRow.Options.UseBackColor = true;
            this.gridView2.Appearance.FocusedRow.Options.UseFont = true;
            this.gridView2.Appearance.FocusedRow.Options.UseForeColor = true;
            this.gridView2.Appearance.GroupPanel.BackColor = System.Drawing.Color.PeachPuff;
            this.gridView2.Appearance.GroupPanel.Options.UseBackColor = true;
            this.gridView2.Appearance.GroupRow.BackColor = System.Drawing.Color.PeachPuff;
            this.gridView2.Appearance.GroupRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel, ((byte)(0)));
            this.gridView2.Appearance.GroupRow.ForeColor = System.Drawing.SystemColors.WindowText;
            this.gridView2.Appearance.GroupRow.Options.UseBackColor = true;
            this.gridView2.Appearance.GroupRow.Options.UseFont = true;
            this.gridView2.Appearance.GroupRow.Options.UseForeColor = true;
            this.gridView2.Appearance.HeaderPanel.BackColor = System.Drawing.Color.Tan;
            this.gridView2.Appearance.HeaderPanel.BorderColor = System.Drawing.Color.Tan;
            this.gridView2.Appearance.HeaderPanel.Font = new System.Drawing.Font("Arial", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel, ((byte)(0)));
            this.gridView2.Appearance.HeaderPanel.Options.UseBackColor = true;
            this.gridView2.Appearance.HeaderPanel.Options.UseBorderColor = true;
            this.gridView2.Appearance.HeaderPanel.Options.UseFont = true;
            this.gridView2.Appearance.HideSelectionRow.BackColor = System.Drawing.Color.PowderBlue;
            this.gridView2.Appearance.HideSelectionRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView2.Appearance.HideSelectionRow.ForeColor = System.Drawing.SystemColors.WindowText;
            this.gridView2.Appearance.HideSelectionRow.Options.UseBackColor = true;
            this.gridView2.Appearance.HideSelectionRow.Options.UseFont = true;
            this.gridView2.Appearance.HideSelectionRow.Options.UseForeColor = true;
            this.gridView2.Appearance.HorzLine.BackColor = System.Drawing.Color.Silver;
            this.gridView2.Appearance.HorzLine.Options.UseBackColor = true;
            this.gridView2.Appearance.OddRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView2.Appearance.OddRow.Options.UseFont = true;
            this.gridView2.Appearance.Row.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.gridView2.Appearance.Row.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView2.Appearance.Row.Options.UseBackColor = true;
            this.gridView2.Appearance.Row.Options.UseFont = true;
            this.gridView2.Appearance.SelectedRow.BackColor = System.Drawing.Color.AliceBlue;
            this.gridView2.Appearance.SelectedRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView2.Appearance.SelectedRow.ForeColor = System.Drawing.Color.Black;
            this.gridView2.Appearance.SelectedRow.Options.UseBackColor = true;
            this.gridView2.Appearance.SelectedRow.Options.UseFont = true;
            this.gridView2.Appearance.SelectedRow.Options.UseForeColor = true;
            this.gridView2.Appearance.VertLine.BackColor = System.Drawing.Color.Silver;
            this.gridView2.Appearance.VertLine.Options.UseBackColor = true;
            this.gridView2.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.gridView2.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.colVon,
            this.colBis,
            this.colStatus});
            this.gridView2.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.None;
            this.gridView2.GridControl = this.grdPeriode;
            this.gridView2.GroupPanelText = "zu gruppierende Kolonnen in diesen Bereich ziehen";
            this.gridView2.Name = "gridView2";
            this.gridView2.OptionsBehavior.Editable = false;
            this.gridView2.OptionsCustomization.AllowFilter = false;
            this.gridView2.OptionsFilter.AllowFilterEditor = false;
            this.gridView2.OptionsFilter.UseNewCustomFilterDialog = true;
            this.gridView2.OptionsMenu.EnableColumnMenu = false;
            this.gridView2.OptionsNavigation.AutoFocusNewRow = true;
            this.gridView2.OptionsNavigation.UseTabKey = false;
            this.gridView2.OptionsView.ColumnAutoWidth = false;
            this.gridView2.OptionsView.ShowFilterPanelMode = DevExpress.XtraGrid.Views.Base.ShowFilterPanelMode.Never;
            this.gridView2.OptionsView.ShowGroupPanel = false;
            this.gridView2.OptionsView.ShowIndicator = false;
            //
            // colVon
            //
            this.colVon.Caption = "Periode Von";
            this.colVon.FieldName = "PeriodeVon";
            this.colVon.Name = "colVon";
            this.colVon.Visible = true;
            this.colVon.VisibleIndex = 0;
            this.colVon.Width = 80;
            //
            // colBis
            //
            this.colBis.Caption = "Periode Bis";
            this.colBis.FieldName = "PeriodeBis";
            this.colBis.Name = "colBis";
            this.colBis.Visible = true;
            this.colBis.VisibleIndex = 1;
            this.colBis.Width = 80;
            //
            // colStatus
            //
            this.colStatus.Caption = "Status";
            this.colStatus.FieldName = "Status";
            this.colStatus.Name = "colStatus";
            this.colStatus.Visible = true;
            this.colStatus.VisibleIndex = 2;
            this.colStatus.Width = 98;
            //
            // edtDatumVon
            //
            this.edtDatumVon.EditValue = null;
            this.edtDatumVon.Location = new System.Drawing.Point(135, 149);
            this.edtDatumVon.Name = "edtDatumVon";
            this.edtDatumVon.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
            this.edtDatumVon.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtDatumVon.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtDatumVon.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtDatumVon.Properties.Appearance.Options.UseBackColor = true;
            this.edtDatumVon.Properties.Appearance.Options.UseBorderColor = true;
            this.edtDatumVon.Properties.Appearance.Options.UseFont = true;
            this.edtDatumVon.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject2.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject2.Options.UseBackColor = true;
            this.edtDatumVon.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "", 8, true, true, false, DevExpress.Utils.HorzAlignment.Center, ((System.Drawing.Image)(resources.GetObject("edtDatumVon.Properties.Buttons"))), new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject2)});
            this.edtDatumVon.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtDatumVon.Properties.Name = "editPerDatum.Properties";
            this.edtDatumVon.Properties.ShowToday = false;
            this.edtDatumVon.Size = new System.Drawing.Size(100, 24);
            this.edtDatumVon.TabIndex = 2;
            //
            // edtDatumBis
            //
            this.edtDatumBis.EditValue = null;
            this.edtDatumBis.Location = new System.Drawing.Point(283, 149);
            this.edtDatumBis.Name = "edtDatumBis";
            this.edtDatumBis.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
            this.edtDatumBis.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtDatumBis.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtDatumBis.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtDatumBis.Properties.Appearance.Options.UseBackColor = true;
            this.edtDatumBis.Properties.Appearance.Options.UseBorderColor = true;
            this.edtDatumBis.Properties.Appearance.Options.UseFont = true;
            this.edtDatumBis.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject1.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject1.Options.UseBackColor = true;
            this.edtDatumBis.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "", 8, true, true, false, DevExpress.Utils.HorzAlignment.Center, ((System.Drawing.Image)(resources.GetObject("edtDatumBis.Properties.Buttons"))), new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject1)});
            this.edtDatumBis.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtDatumBis.Properties.Name = "editPerDatum.Properties";
            this.edtDatumBis.Properties.ShowToday = false;
            this.edtDatumBis.Size = new System.Drawing.Size(100, 24);
            this.edtDatumBis.TabIndex = 3;
            //
            // edtNurMitBuchungen
            //
            this.edtNurMitBuchungen.Checked = true;
            this.edtNurMitBuchungen.CheckState = System.Windows.Forms.CheckState.Checked;
            this.edtNurMitBuchungen.Location = new System.Drawing.Point(427, 148);
            this.edtNurMitBuchungen.Name = "edtNurMitBuchungen";
            this.edtNurMitBuchungen.Size = new System.Drawing.Size(210, 24);
            this.edtNurMitBuchungen.TabIndex = 4;
            this.edtNurMitBuchungen.Text = "nur Konti mit Buchungen";
            this.edtNurMitBuchungen.UseCompatibleTextRendering = true;
            //
            // edtOhneKtoGruppen
            //
            this.edtOhneKtoGruppen.Checked = true;
            this.edtOhneKtoGruppen.CheckState = System.Windows.Forms.CheckState.Checked;
            this.edtOhneKtoGruppen.Location = new System.Drawing.Point(427, 178);
            this.edtOhneKtoGruppen.Name = "edtOhneKtoGruppen";
            this.edtOhneKtoGruppen.Size = new System.Drawing.Size(142, 24);
            this.edtOhneKtoGruppen.TabIndex = 5;
            this.edtOhneKtoGruppen.Text = "ohne Kontogruppen";
            this.edtOhneKtoGruppen.UseCompatibleTextRendering = true;
            //
            // groupBox1
            //
            this.groupBox1.Controls.Add(this.edtKeinAbrechnungsText);
            this.groupBox1.Controls.Add(this.btnDrucken);
            this.groupBox1.Controls.Add(this.kissLabel5);
            this.groupBox1.Controls.Add(this.edtMA);
            this.groupBox1.Controls.Add(this.kissLabel4);
            this.groupBox1.Controls.Add(this.edtPM);
            this.groupBox1.Controls.Add(this.kissLabel3);
            this.groupBox1.Controls.Add(this.edtBemerkung);
            this.groupBox1.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.groupBox1.Location = new System.Drawing.Point(44, 208);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(601, 213);
            this.groupBox1.TabIndex = 6;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "für den Ausdruck";
            this.groupBox1.UseCompatibleTextRendering = true;
            //
            // edtKeinAbrechnungsText
            //
            this.edtKeinAbrechnungsText.EditValue = false;
            this.edtKeinAbrechnungsText.Location = new System.Drawing.Point(102, 188);
            this.edtKeinAbrechnungsText.Name = "edtKeinAbrechnungsText";
            this.edtKeinAbrechnungsText.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.edtKeinAbrechnungsText.Properties.Appearance.Options.UseBackColor = true;
            this.edtKeinAbrechnungsText.Properties.Caption = "\'Abrechnung eingesehen\' unterdrücken";
            this.edtKeinAbrechnungsText.Size = new System.Drawing.Size(233, 19);
            this.edtKeinAbrechnungsText.TabIndex = 4;
            //
            // btnDrucken
            //
            this.btnDrucken.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDrucken.Location = new System.Drawing.Point(492, 181);
            this.btnDrucken.Name = "btnDrucken";
            this.btnDrucken.Size = new System.Drawing.Size(90, 24);
            this.btnDrucken.TabIndex = 3;
            this.btnDrucken.Text = "Drucken";
            this.btnDrucken.UseCompatibleTextRendering = true;
            this.btnDrucken.UseVisualStyleBackColor = true;
            this.btnDrucken.Click += new System.EventHandler(this.btnDrucken_Click);
            //
            // kissLabel5
            //
            this.kissLabel5.Location = new System.Drawing.Point(5, 159);
            this.kissLabel5.Name = "kissLabel5";
            this.kissLabel5.Size = new System.Drawing.Size(94, 24);
            this.kissLabel5.TabIndex = 2;
            this.kissLabel5.Text = "zuständige/r MA";
            this.kissLabel5.UseCompatibleTextRendering = true;
            //
            // edtMA
            //
            this.edtMA.Location = new System.Drawing.Point(105, 159);
            this.edtMA.Name = "edtMA";
            this.edtMA.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtMA.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtMA.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtMA.Properties.Appearance.Options.UseBackColor = true;
            this.edtMA.Properties.Appearance.Options.UseBorderColor = true;
            this.edtMA.Properties.Appearance.Options.UseFont = true;
            this.edtMA.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtMA.Size = new System.Drawing.Size(297, 24);
            this.edtMA.TabIndex = 2;
            //
            // kissLabel4
            //
            this.kissLabel4.Location = new System.Drawing.Point(5, 92);
            this.kissLabel4.Name = "kissLabel4";
            this.kissLabel4.Size = new System.Drawing.Size(31, 24);
            this.kissLabel4.TabIndex = 1;
            this.kissLabel4.Text = "P.M.";
            this.kissLabel4.UseCompatibleTextRendering = true;
            //
            // edtPM
            //
            this.edtPM.Location = new System.Drawing.Point(105, 92);
            this.edtPM.Name = "edtPM";
            this.edtPM.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtPM.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtPM.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtPM.Properties.Appearance.Options.UseBackColor = true;
            this.edtPM.Properties.Appearance.Options.UseBorderColor = true;
            this.edtPM.Properties.Appearance.Options.UseFont = true;
            this.edtPM.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtPM.Size = new System.Drawing.Size(477, 61);
            this.edtPM.TabIndex = 1;
            //
            // kissLabel3
            //
            this.kissLabel3.Font = new System.Drawing.Font("Arial", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.kissLabel3.LabelStyle = KiSS4.Gui.LabelStyleType.Custom;
            this.kissLabel3.Location = new System.Drawing.Point(5, 23);
            this.kissLabel3.Name = "kissLabel3";
            this.kissLabel3.Size = new System.Drawing.Size(85, 38);
            this.kissLabel3.TabIndex = 0;
            this.kissLabel3.Text = "Erläuterung zur Abrechnung";
            this.kissLabel3.UseCompatibleTextRendering = true;
            //
            // edtBemerkung
            //
            this.edtBemerkung.Location = new System.Drawing.Point(105, 23);
            this.edtBemerkung.Name = "edtBemerkung";
            this.edtBemerkung.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtBemerkung.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtBemerkung.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtBemerkung.Properties.Appearance.Options.UseBackColor = true;
            this.edtBemerkung.Properties.Appearance.Options.UseBorderColor = true;
            this.edtBemerkung.Properties.Appearance.Options.UseFont = true;
            this.edtBemerkung.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtBemerkung.Size = new System.Drawing.Size(477, 61);
            this.edtBemerkung.TabIndex = 0;
            //
            // kissLabel1
            //
            this.kissLabel1.Location = new System.Drawing.Point(5, 149);
            this.kissLabel1.Name = "kissLabel1";
            this.kissLabel1.Size = new System.Drawing.Size(67, 24);
            this.kissLabel1.TabIndex = 371;
            this.kissLabel1.Text = "Datum von";
            this.kissLabel1.UseCompatibleTextRendering = true;
            //
            // label40
            //
            this.label40.Location = new System.Drawing.Point(5, 45);
            this.label40.Name = "label40";
            this.label40.Size = new System.Drawing.Size(124, 24);
            this.label40.TabIndex = 375;
            this.label40.Text = "Pers. mit zivilr. Massn.";
            this.label40.UseCompatibleTextRendering = true;
            //
            // edtAdresse
            //
            this.edtAdresse.EditMode = Kiss.Interfaces.UI.EditModeType.ReadOnly;
            this.edtAdresse.Location = new System.Drawing.Point(135, 83);
            this.edtAdresse.Name = "edtAdresse";
            this.edtAdresse.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.edtAdresse.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtAdresse.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtAdresse.Properties.Appearance.Options.UseBackColor = true;
            this.edtAdresse.Properties.Appearance.Options.UseBorderColor = true;
            this.edtAdresse.Properties.Appearance.Options.UseFont = true;
            this.edtAdresse.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtAdresse.Properties.Name = "editPlzOrt.Properties";
            this.edtAdresse.Properties.ReadOnly = true;
            this.edtAdresse.Size = new System.Drawing.Size(281, 24);
            this.edtAdresse.TabIndex = 376;
            //
            // edtBaPersonID
            //
            this.edtBaPersonID.EditMode = Kiss.Interfaces.UI.EditModeType.ReadOnly;
            this.edtBaPersonID.Location = new System.Drawing.Point(357, 45);
            this.edtBaPersonID.Name = "edtBaPersonID";
            this.edtBaPersonID.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.edtBaPersonID.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtBaPersonID.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtBaPersonID.Properties.Appearance.Options.UseBackColor = true;
            this.edtBaPersonID.Properties.Appearance.Options.UseBorderColor = true;
            this.edtBaPersonID.Properties.Appearance.Options.UseFont = true;
            this.edtBaPersonID.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtBaPersonID.Properties.Name = "editMandantNr.Properties";
            this.edtBaPersonID.Properties.ReadOnly = true;
            this.edtBaPersonID.Size = new System.Drawing.Size(59, 24);
            this.edtBaPersonID.TabIndex = 377;
            //
            // edtMT
            //
            this.edtMT.EditMode = Kiss.Interfaces.UI.EditModeType.ReadOnly;
            this.edtMT.Location = new System.Drawing.Point(135, 106);
            this.edtMT.Name = "edtMT";
            this.edtMT.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.edtMT.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtMT.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtMT.Properties.Appearance.Options.UseBackColor = true;
            this.edtMT.Properties.Appearance.Options.UseBorderColor = true;
            this.edtMT.Properties.Appearance.Options.UseFont = true;
            this.edtMT.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtMT.Properties.Name = "editMT.Properties";
            this.edtMT.Properties.ReadOnly = true;
            this.edtMT.Size = new System.Drawing.Size(281, 24);
            this.edtMT.TabIndex = 378;
            //
            // label10
            //
            this.label10.Location = new System.Drawing.Point(5, 106);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(98, 24);
            this.label10.TabIndex = 379;
            this.label10.Text = "Beist. oder Vorm.";
            this.label10.UseCompatibleTextRendering = true;
            //
            // label1
            //
            this.label1.Location = new System.Drawing.Point(5, 83);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(52, 24);
            this.label1.TabIndex = 380;
            this.label1.Text = "Adresse";
            this.label1.UseCompatibleTextRendering = true;
            //
            // kissLabel2
            //
            this.kissLabel2.Location = new System.Drawing.Point(253, 149);
            this.kissLabel2.Name = "kissLabel2";
            this.kissLabel2.Size = new System.Drawing.Size(24, 24);
            this.kissLabel2.TabIndex = 382;
            this.kissLabel2.Text = "bis";
            this.kissLabel2.UseCompatibleTextRendering = true;
            //
            // panel1
            //
            this.panel1.Controls.Add(this.picTitel);
            this.panel1.Controls.Add(this.lblTitel);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(736, 24);
            this.panel1.TabIndex = 1;
            //
            // picTitel
            //
            this.picTitel.Image = ((System.Drawing.Image)(resources.GetObject("picTitel.Image")));
            this.picTitel.Location = new System.Drawing.Point(5, 5);
            this.picTitel.Name = "picTitel";
            this.picTitel.Size = new System.Drawing.Size(16, 16);
            this.picTitel.TabIndex = 293;
            this.picTitel.TabStop = false;
            //
            // lblTitel
            //
            this.lblTitel.LabelStyle = KiSS4.Gui.LabelStyleType.TitleLabel;
            this.lblTitel.Location = new System.Drawing.Point(25, 5);
            this.lblTitel.Name = "lblTitel";
            this.lblTitel.Size = new System.Drawing.Size(542, 15);
            this.lblTitel.TabIndex = 0;
            this.lblTitel.Text = "Bilanz/Erfolg";
            this.lblTitel.UseCompatibleTextRendering = true;
            //
            // CtlKgBilanzErfolg
            //
            this.ActiveSQLQuery = this.qryBilanz;
            this.Controls.Add(this.panel1);
            this.Name = "CtlKgBilanzErfolg";
            this.Size = new System.Drawing.Size(736, 518);
            this.Load += new System.EventHandler(this.CtlKgBilanzErfolg_Load);
            this.Controls.SetChildIndex(this.tabControlSearch, 0);
            this.Controls.SetChildIndex(this.panel1, 0);
            this.tabControlSearch.ResumeLayout(false);
            this.tpgListe.ResumeLayout(false);
            this.tpgSuchen.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.treKgBilanz)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.qryBilanz)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblMandant)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtMandant.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdPeriode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.qryPeriode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtDatumVon.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtDatumBis.Properties)).EndInit();
            this.groupBox1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.edtKeinAbrechnungsText.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtMA.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtPM.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtBemerkung.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.label40)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtAdresse.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtBaPersonID.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtMT.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.label10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.label1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel2)).EndInit();
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picTitel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblTitel)).EndInit();
            this.ResumeLayout(false);
        }

        #endregion

        #region Dispose

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if ((components != null))
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #endregion

        #region Public Methods

        public override object GetContextValue(string FieldName)
        {
            switch (FieldName.ToUpper())
            {
                case "KGPERIODEID":
                    if (qryPeriode.Count > 0)
                        return qryPeriode["KgPeriodeID"];
                    else
                        return DBNull.Value;

                case "NURMITBUCHUNGEN":
                    return edtNurMitBuchungen.Checked;

                case "DATUMVON":
                    return edtDatumVon.EditValue;

                case "DATUMBIS":
                    return edtDatumBis.EditValue;
            }

            return base.GetContextValue(FieldName);
        }

        public void Init(string Name, Image TitleImage, int FaLeistungID, int BaPersonID)
        {
            lblTitel.Text = Name;
            picTitel.Image = TitleImage;
            faLeistungID = FaLeistungID;
            baPersonID = BaPersonID;
        }

        #endregion

        #region Protected Methods

        protected override void NewSearch()
        {
            tabControlSearch.SelectedTabIndex = 1;

            if (baPersonID > 0)
            {
                SqlQuery qry = DBUtil.OpenSQL(@"
                  SELECT Name    = PRS.NameVorname,
                         Adresse = PRS.Wohnsitz,
                         [Beist. oder Vorm.] = dbo.fnVmGetMTName(PRS.BaPersonID)
                  FROM   vwPerson PRS
                  WHERE  PRS.BaPersonID = {0}",
                  baPersonID);

                edtBaPersonID.EditValue = baPersonID;
                edtMandant.EditValue = qry["Name"];
                edtAdresse.EditValue = qry["Adresse"];
                edtMT.EditValue = qry["Beist. oder Vorm."];

                DisplayPerioden();
            }

            edtNurMitBuchungen.Checked = true;
            edtOhneKtoGruppen.Checked = true;

            edtDatumVon.Focus();
        }

        protected override void RunSearch()
        {
            if (!CheckPrms()) throw new Exception();

            treKgBilanz.DataSource = null;

            qryBilanz.Fill("exec spKgGetBilanzErfolg {0},{1},{2},{3},{4}",
                    qryPeriode["KgPeriodeID"],
                    edtDatumVon.EditValue,
                    edtDatumBis.EditValue,
                    edtNurMitBuchungen.Checked,
                    edtOhneKtoGruppen.Checked);

            lblMandant.Text = edtMandant.Text + "  (" +
                              ((DateTime)edtDatumVon.EditValue).ToString("dd.MM.yyyy") + " - " +
                              ((DateTime)edtDatumBis.EditValue).ToString("dd.MM.yyyy") + ")";

            tabControlSearch.SelectedTabIndex = 0;

            treKgBilanz.DataSource = qryBilanz;
            treKgBilanz.ExpandAll();
            treKgBilanz.Focus();
        }

        #endregion

        #region Private Methods

        private void btnCollapse_Click(object sender, System.EventArgs e)
        {
            treKgBilanz.CollapseAll();
            treKgBilanz.Focus();
        }

        private void btnDrucken_Click(object sender, System.EventArgs e)
        {
            if (qryPeriode.Count == 0) return;

            NamedPrm[] prms = new NamedPrm[10];
            prms[0] = new NamedPrm("KgPeriodeID", qryPeriode["KgPeriodeID"]);
            prms[1] = new NamedPrm("DatumVon", edtDatumVon.EditValue);
            prms[2] = new NamedPrm("DatumBis", edtDatumBis.EditValue);
            prms[3] = new NamedPrm("NurMitBuchungen", edtNurMitBuchungen.Checked);
            prms[4] = new NamedPrm("OhneKtoGruppen", edtOhneKtoGruppen.Checked);
            prms[5] = new NamedPrm("Bemerkung", edtBemerkung.Text.Replace(" ", "! !").Replace("?", "!?!"));
            prms[6] = new NamedPrm("PM", edtPM.Text.Replace(" ", "! !").Replace("?", "!?!"));
            prms[7] = new NamedPrm("MA", edtMA.Text.Replace(" ", "! !").Replace("?", "!?!"));
            prms[8] = new NamedPrm("UserID", Session.User.UserID);
            prms[9] = new NamedPrm("KeinAbrechnungsText", edtKeinAbrechnungsText.Checked);

            RepUtil.ExecuteReport("KgBilanzErfolg", KissReportDestination.Viewer, prms);
        }

        private void btnExpand_Click(object sender, System.EventArgs e)
        {
            treKgBilanz.ExpandAll();
            treKgBilanz.Focus();
        }

        private bool CheckPrms()
        {
            // Suchfelder validieren
            if (baPersonID == 0)
            {
                DlgInfo.Show("Es ist noch kein Mandant ausgewählt!", 0, 0);
                return false;
            }

            if (qryPeriode.Count == 0)
            {
                DlgInfo.Show("Es ist noch keine gültige Periode ausgewählt!", 0, 0);
                return false;
            }

            if (DBUtil.IsEmpty(edtDatumVon.EditValue))
            {
                DlgInfo.Show("Das Feld 'Datum von' darf nicht leer bleiben!", 0, 0);
                return false;
            }

            if (DBUtil.IsEmpty(edtDatumBis.EditValue))
            {
                DlgInfo.Show("Das Feld 'Datum bis' darf nicht leer bleiben!", 0, 0);
                return false;
            }
            return true;
        }

        private void CtlKgBilanzErfolg_Load(object sender, System.EventArgs e)
        {
            if (baPersonID > 0)
            {
                SqlQuery qry = DBUtil.OpenSQL(@"
                  SELECT Name    = PRS.NameVorname,
                         Adresse = PRS.Wohnsitz,
                         [Beist. oder Vorm.] = dbo.fnVmGetMTName(PRS.BaPersonID)
                  FROM   vwPerson PRS
                  WHERE  PRS.BaPersonID = {0}",
                  baPersonID);

                edtBaPersonID.EditValue = baPersonID;
                edtMandant.EditValue = qry["Name"];
                edtAdresse.EditValue = qry["Adresse"];
                edtMT.EditValue = qry["Beist. oder Vorm."];

                edtMandant.EditMode = EditModeType.ReadOnly;

                DisplayPerioden();

                RunSearch();
            }
            else
            {
                edtMandant.EditMode = EditModeType.Normal;
                NewSearch();
            }
        }

        private void DisplayPerioden()
        {
            qryPeriode.Fill(baPersonID);
            try
            {
                while (!((DateTime)qryPeriode["PeriodeVon"] <= DateTime.Today && (DateTime)qryPeriode["PeriodeBis"] >= DateTime.Today))
                    if (!qryPeriode.Next()) break;
            }
            catch { }
        }

        private void edtMandant_UserModifiedFld(object sender, KiSS4.Gui.UserModifiedFldEventArgs e)
        {
            string SearchString = edtMandant.EditValue.ToString().Replace("*", "%").Replace("?", "_").Replace(" ", "%");

            if (DBUtil.IsEmpty(SearchString))
            {
                if (e.ButtonClicked)
                {
                    SearchString = "%";
                }
                else
                {
                    baPersonID = -1;
                    edtMandant.EditValue = null;
                    edtBaPersonID.EditValue = null;
                    edtAdresse.EditValue = null;
                    edtMT.EditValue = null;
                    qryPeriode.DataTable.Rows.Clear();
                    qryPeriode.EnableBoundFields(false);
                    return;
                }
            }

            KissLookupDialog dlg = new KissLookupDialog();
            e.Cancel = !dlg.SearchData(@"
              SELECT distinct
                     BaPersonID$      = PRS.BaPersonID,
                     [Personen-Nr.]   = PRS.BaPersonID,
                     Name             = PRS.NameVorname,
                     Geburtsdatum     = PRS.Geburtsdatum,
                     [Alter]          = PRS.[Alter],
                     Adresse          = PRS.Wohnsitz,
                     [Beist. oder Vorm.] = dbo.fnVmGetMTName(PRS.BaPersonID)
              FROM   vwPerson PRS
                     inner join FaLeistung LEI on LEI.BaPersonID = PRS.BaPersonID and
                                                  LEI.FaProzessCode = 500
              WHERE  PRS.NameVorname LIKE '%' + {0} + '%'
              ORDER BY PRS.NameVorname",
              SearchString,
              e.ButtonClicked, null, null, null);

            if (!e.Cancel)
            {
                baPersonID = (int)dlg["BaPersonID$"];
                edtMandant.EditValue = dlg["Name"];
                edtBaPersonID.EditValue = dlg["BaPersonID$"];
                edtAdresse.EditValue = dlg["Adresse"];
                edtMT.EditValue = dlg["Beist. oder Vorm."];

                DisplayPerioden();
            }
        }

        private void qryPeriode_PositionChanged(object sender, System.EventArgs e)
        {
            edtDatumVon.EditValue = qryPeriode["PeriodeVon"];
            edtDatumBis.EditValue = qryPeriode["PeriodeBis"];
            edtMA.EditValue = qryPeriode["MA"];
        }

        #endregion
    }
}