CREATE TABLE [dbo].[OLD_30_Hist_DmgPerson](
	[DmgPersonID] [int] NOT NULL,
	[Titel] [varchar](50) NULL,
	[Name] [varchar](100) NOT NULL,
	[FruehererName] [varchar](100) NULL,
	[Vorname] [varchar](100) NOT NULL,
	[Vorname2] [varchar](100) NULL,
	[Geburtsdatum] [datetime] NULL,
	[Sterbedatum] [datetime] NULL,
	[AHVNummer] [varchar](16) NULL,
	[Versichertennummer] [varchar](18) NULL,
	[NNummer] [varchar](20) NULL,
	[BFFNummer] [varchar](20) NULL,
	[GeschlechtCode] [int] NULL,
	[KonfessionCode] [int] NULL,
	[ZivilstandCode] [int] NULL,
	[ZivilstandDatum] [datetime] NULL,
	[HeimatgemeindeBaGemeindeID] [int] NULL,
	[NationalitaetCode] [int] NULL,
	[AuslaenderStatusCode] [int] NULL,
	[AuslaenderStatusDatum] [datetime] NULL,
	[AuslaenderStatusGueltigBis] [datetime] NULL,
	[InGemeindeSeit] [datetime] NULL,
	[InCHSeitGeburt] [bit] NOT NULL,
	[ImKantonSeit] [datetime] NULL,
	[ImKantonSeitGeburt] [bit] NOT NULL,
	[Telefon_P] [varchar](100) NULL,
	[Telefon_G] [varchar](100) NULL,
	[MobilTel] [varchar](100) NULL,
	[Fax] [varchar](100) NULL,
	[EMail] [varchar](100) NULL,
	[SprachCode] [int] NULL,
	[Unterstuetzt] [bit] NOT NULL,
	[Fiktiv] [bit] NOT NULL,
	[Testperson] [bit] NOT NULL,
	[NavigatorZusatz] [varchar](30) NULL,
	[Bemerkung] [varchar](6000) NULL,
	[VerID] [int] NOT NULL,
	[VerID_DELETED] [int] NULL,
 CONSTRAINT [PK_Hist_DmgPerson] PRIMARY KEY CLUSTERED 
(
	[DmgPersonID] ASC,
	[VerID] ASC
) ON [PRIMARY]
) ON [PRIMARY]

GO