#region Header

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#endregion

using System;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraBars;
using Kiss.Interfaces.UI;
using Kiss.Interfaces.ViewModel;
using Kiss.UserInterface.ViewModel;
using KiSS.DBScheme;
using KiSS4.DB;
using KiSS4.Gui;

namespace KiSS4.Sozialhilfe
{
    public class CtlWhModulTree : KiSS4.Common.KissModulTree
    {
        #region Fields

        private DevExpress.XtraBars.BarButtonItem btnBgBudget;
        private DevExpress.XtraBars.BarButtonItem btnBgBudgetDelete;
        private DevExpress.XtraBars.BarButtonItem btnBgBudgetReset;
        private DevExpress.XtraBars.BarButtonItem btnBgBudgetResetMaster;
        private DevExpress.XtraBars.BarButtonItem btnBgFinanzplan1;
        private DevExpress.XtraBars.BarButtonItem btnBgFinanzplan2;
        private DevExpress.XtraBars.BarButtonItem btnBgFinanzplanDelete;
        private DevExpress.XtraBars.BarButtonItem btnFaLeistung300;
        private DevExpress.XtraBars.BarButtonItem btnFaLeistungDelete;
        private DevExpress.XtraTreeList.Columns.TreeListColumn colBaPersonID;
        private DevExpress.XtraTreeList.Columns.TreeListColumn colDate;
        private DevExpress.XtraTreeList.Columns.TreeListColumn colFaLeistungID;
        private DevExpress.XtraTreeList.Columns.TreeListColumn colName;

        #endregion

        #region Constructors

        public CtlWhModulTree(int baPersonID, System.Windows.Forms.Panel panelDetail)
            : base(baPersonID, panelDetail, Gui.ModulID.S)
        {
            // This call is required by the Windows Form Designer.
            InitializeComponent();

            this.popup_Tree.LinksPersistInfo.Clear();
            this.popup_Tree.LinksPersistInfo.AddRange(new DevExpress.XtraBars.LinkPersistInfo[] {
            new DevExpress.XtraBars.LinkPersistInfo(this.btnBgFinanzplan2),
            new DevExpress.XtraBars.LinkPersistInfo(this.btnBgFinanzplan1),
            new DevExpress.XtraBars.LinkPersistInfo(this.btnBgFinanzplanDelete),

            new DevExpress.XtraBars.LinkPersistInfo(this.btnFaLeistung300, true),
            //	new DevExpress.XtraBars.LinkPersistInfo(this.btnFaLeistung301),
            //	new DevExpress.XtraBars.LinkPersistInfo(this.btnFaLeistung302),
            //	new DevExpress.XtraBars.LinkPersistInfo(this.btnFaLeistung304),
            new DevExpress.XtraBars.LinkPersistInfo(this.btnFaLeistungDelete),

            new DevExpress.XtraBars.LinkPersistInfo(this.btnBgBudget, true),
            new DevExpress.XtraBars.LinkPersistInfo(this.btnBgBudgetReset),
            new DevExpress.XtraBars.LinkPersistInfo(this.btnBgBudgetDelete),

            new DevExpress.XtraBars.LinkPersistInfo(this.btnFallZugriff, true),
            new DevExpress.XtraBars.LinkPersistInfo(this.btnFallInfo)
            });
        }

        public CtlWhModulTree()
        {
            this.InitializeComponent();
        }

        #endregion

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.btnBgBudget = new DevExpress.XtraBars.BarButtonItem();
            this.btnBgBudgetDelete = new DevExpress.XtraBars.BarButtonItem();
            this.btnBgBudgetReset = new DevExpress.XtraBars.BarButtonItem();
            this.btnBgBudgetResetMaster = new DevExpress.XtraBars.BarButtonItem();
            this.btnBgFinanzplan1 = new DevExpress.XtraBars.BarButtonItem();
            this.btnBgFinanzplan2 = new DevExpress.XtraBars.BarButtonItem();
            this.btnBgFinanzplanDelete = new DevExpress.XtraBars.BarButtonItem();
            this.btnFaLeistung300 = new DevExpress.XtraBars.BarButtonItem();
            this.btnFaLeistungDelete = new DevExpress.XtraBars.BarButtonItem();
            this.colBaPersonID = new DevExpress.XtraTreeList.Columns.TreeListColumn();
            this.colDate = new DevExpress.XtraTreeList.Columns.TreeListColumn();
            this.colFaLeistungID = new DevExpress.XtraTreeList.Columns.TreeListColumn();
            this.colName = new DevExpress.XtraTreeList.Columns.TreeListColumn();
            ((System.ComponentModel.ISupportInitialize)(this.kissTree)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.qryModulTree)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.popup_Tree)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.barManager_Tree)).BeginInit();
            this.SuspendLayout();
            //
            // kissTree
            //
            this.kissTree.Appearance.Empty.BackColor = System.Drawing.Color.Transparent;
            this.kissTree.Appearance.Empty.ForeColor = System.Drawing.Color.White;
            this.kissTree.Appearance.Empty.Options.UseBackColor = true;
            this.kissTree.Appearance.Empty.Options.UseForeColor = true;
            this.kissTree.Appearance.EvenRow.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(227)))), ((int)(((byte)(215)))));
            this.kissTree.Appearance.EvenRow.ForeColor = System.Drawing.Color.Black;
            this.kissTree.Appearance.EvenRow.Options.UseBackColor = true;
            this.kissTree.Appearance.EvenRow.Options.UseForeColor = true;
            this.kissTree.Appearance.FocusedCell.BackColor = System.Drawing.Color.Transparent;
            this.kissTree.Appearance.FocusedCell.ForeColor = System.Drawing.Color.White;
            this.kissTree.Appearance.FocusedCell.Options.UseBackColor = true;
            this.kissTree.Appearance.FocusedCell.Options.UseForeColor = true;
            this.kissTree.Appearance.FocusedRow.ForeColor = System.Drawing.Color.White;
            this.kissTree.Appearance.FocusedRow.Options.UseForeColor = true;
            this.kissTree.Appearance.FooterPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(216)))), ((int)(((byte)(174)))));
            this.kissTree.Appearance.FooterPanel.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.kissTree.Appearance.FooterPanel.ForeColor = System.Drawing.Color.Black;
            this.kissTree.Appearance.FooterPanel.Options.UseBackColor = true;
            this.kissTree.Appearance.FooterPanel.Options.UseFont = true;
            this.kissTree.Appearance.FooterPanel.Options.UseForeColor = true;
            this.kissTree.Appearance.GroupButton.BackColor = System.Drawing.Color.Transparent;
            this.kissTree.Appearance.GroupButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.kissTree.Appearance.GroupButton.ForeColor = System.Drawing.Color.Black;
            this.kissTree.Appearance.GroupButton.Options.UseBackColor = true;
            this.kissTree.Appearance.GroupButton.Options.UseFont = true;
            this.kissTree.Appearance.GroupButton.Options.UseForeColor = true;
            this.kissTree.Appearance.GroupFooter.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(226)))), ((int)(((byte)(184)))));
            this.kissTree.Appearance.GroupFooter.ForeColor = System.Drawing.Color.Black;
            this.kissTree.Appearance.GroupFooter.Options.UseBackColor = true;
            this.kissTree.Appearance.GroupFooter.Options.UseForeColor = true;
            this.kissTree.Appearance.HeaderPanel.BackColor = System.Drawing.Color.Tan;
            this.kissTree.Appearance.HeaderPanel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Bold);
            this.kissTree.Appearance.HeaderPanel.ForeColor = System.Drawing.Color.Black;
            this.kissTree.Appearance.HeaderPanel.Options.UseBackColor = true;
            this.kissTree.Appearance.HeaderPanel.Options.UseFont = true;
            this.kissTree.Appearance.HeaderPanel.Options.UseForeColor = true;
            this.kissTree.Appearance.HideSelectionRow.BackColor = System.Drawing.Color.PowderBlue;
            this.kissTree.Appearance.HideSelectionRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.kissTree.Appearance.HideSelectionRow.ForeColor = System.Drawing.Color.Black;
            this.kissTree.Appearance.HideSelectionRow.Options.UseBackColor = true;
            this.kissTree.Appearance.HideSelectionRow.Options.UseFont = true;
            this.kissTree.Appearance.HideSelectionRow.Options.UseForeColor = true;
            this.kissTree.Appearance.HorzLine.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(216)))), ((int)(((byte)(174)))));
            this.kissTree.Appearance.HorzLine.ForeColor = System.Drawing.Color.Red;
            this.kissTree.Appearance.HorzLine.Options.UseBackColor = true;
            this.kissTree.Appearance.HorzLine.Options.UseForeColor = true;
            this.kissTree.Appearance.OddRow.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(236)))), ((int)(((byte)(215)))));
            this.kissTree.Appearance.OddRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.kissTree.Appearance.OddRow.ForeColor = System.Drawing.Color.Black;
            this.kissTree.Appearance.OddRow.Options.UseBackColor = true;
            this.kissTree.Appearance.OddRow.Options.UseFont = true;
            this.kissTree.Appearance.OddRow.Options.UseForeColor = true;
            this.kissTree.Appearance.Preview.BackColor = System.Drawing.Color.White;
            this.kissTree.Appearance.Preview.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.kissTree.Appearance.Preview.ForeColor = System.Drawing.Color.Maroon;
            this.kissTree.Appearance.Preview.Options.UseBackColor = true;
            this.kissTree.Appearance.Preview.Options.UseFont = true;
            this.kissTree.Appearance.Preview.Options.UseForeColor = true;
            this.kissTree.Appearance.Row.BackColor = System.Drawing.Color.Transparent;
            this.kissTree.Appearance.Row.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.kissTree.Appearance.Row.ForeColor = System.Drawing.Color.Black;
            this.kissTree.Appearance.Row.Options.UseBackColor = true;
            this.kissTree.Appearance.Row.Options.UseFont = true;
            this.kissTree.Appearance.Row.Options.UseForeColor = true;
            this.kissTree.Appearance.SelectedRow.ForeColor = System.Drawing.Color.White;
            this.kissTree.Appearance.SelectedRow.Options.UseForeColor = true;
            this.kissTree.Appearance.TreeLine.BackColor = System.Drawing.Color.Gray;
            this.kissTree.Appearance.TreeLine.Options.UseBackColor = true;
            this.kissTree.Appearance.VertLine.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(216)))), ((int)(((byte)(174)))));
            this.kissTree.Appearance.VertLine.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(166)))), ((int)(((byte)(70)))));
            this.kissTree.Appearance.VertLine.Options.UseBackColor = true;
            this.kissTree.Appearance.VertLine.Options.UseForeColor = true;
            this.kissTree.Appearance.VertLine.Options.UseTextOptions = true;
            this.kissTree.Appearance.VertLine.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.kissTree.Columns.AddRange(new DevExpress.XtraTreeList.Columns.TreeListColumn[] {
                        this.colName,
                        this.colDate,
                        this.colFaLeistungID,
                        this.colBaPersonID});
            this.kissTree.DataSource = this.qryModulTree;
            this.kissTree.OptionsBehavior.AutoSelectAllInEditor = false;
            this.kissTree.OptionsBehavior.CloseEditorOnLostFocus = false;
            this.kissTree.OptionsBehavior.Editable = false;
            this.kissTree.OptionsBehavior.KeepSelectedOnClick = false;
            this.kissTree.OptionsBehavior.MoveOnEdit = false;
            this.kissTree.OptionsBehavior.ShowToolTips = false;
            this.kissTree.OptionsBehavior.SmartMouseHover = false;
            this.kissTree.OptionsMenu.EnableColumnMenu = false;
            this.kissTree.OptionsMenu.EnableFooterMenu = false;
            this.kissTree.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.kissTree.OptionsView.AutoWidth = false;
            this.kissTree.OptionsView.EnableAppearanceEvenRow = true;
            this.kissTree.OptionsView.EnableAppearanceOddRow = true;
            this.kissTree.OptionsView.ShowIndicator = false;
            this.kissTree.OptionsView.ShowVertLines = false;
            this.kissTree.Styles.AddReplace("PressedColumn", new DevExpress.Utils.ViewStyle("PressedColumn", "TreeList", new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Bold), "HeaderPanel", ((DevExpress.Utils.StyleOptions)(((DevExpress.Utils.StyleOptions.StyleEnabled | DevExpress.Utils.StyleOptions.UseBackColor)
                                | DevExpress.Utils.StyleOptions.UseForeColor))), true, false, false, DevExpress.Utils.HorzAlignment.Near, DevExpress.Utils.VertAlignment.Center, null, System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(222))))), System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))))));
            //
            // qryModulTree
            //
            this.qryModulTree.SelectStatement = "EXECUTE dbo.spXGetModulTree {0}, {1}, {2}, {3}, {4}";
            //
            // popup_Tree
            //
            this.popup_Tree.LinksPersistInfo.AddRange(new DevExpress.XtraBars.LinkPersistInfo[] {
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnFaLeistung300),
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnFaLeistungDelete),
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnBgFinanzplan1, true),
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnBgFinanzplan2),
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnBgFinanzplanDelete),
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnBgBudget, true),
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnBgBudgetResetMaster),
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnBgBudgetReset),
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnBgBudgetDelete),
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnFallZugriff, true),
                        new DevExpress.XtraBars.LinkPersistInfo(this.btnFallInfo)});
            //
            // barManager_Tree
            //
            this.barManager_Tree.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
                        this.btnFaLeistung300,
                        this.btnFaLeistungDelete,
                        this.btnBgBudgetResetMaster,
                        this.btnBgBudget,
                        this.btnBgBudgetReset,
                        this.btnBgBudgetDelete,
                        this.btnBgFinanzplan1,
                        this.btnBgFinanzplan2,
                        this.btnBgFinanzplanDelete,
            });
            this.barManager_Tree.MaxItemId = 14;
            this.barManager_Tree.QueryShowPopupMenu += new DevExpress.XtraBars.QueryShowPopupMenuEventHandler(this.barManager_Tree_QueryShowPopupMenu);
            //
            // btnFallZugriff
            //
            this.btnFallZugriff.CategoryGuid = new System.Guid("f96a77cc-41a0-4295-8f5a-5c2410a21ef7");
            //
            // btnFallInfo
            //
            this.btnFallInfo.CategoryGuid = new System.Guid("f96a77cc-41a0-4295-8f5a-5c2410a21ef7");
            //
            // btnBgBudget
            //
            this.btnBgBudget.Caption = "Neues Monatsbudget einfügen ...";
            this.btnBgBudget.Id = 5;
            this.btnBgBudget.ImageIndex = 1323;
            this.btnBgBudget.Name = "btnBgBudget";
            this.btnBgBudget.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btnBgBudget_ItemClick);
            //
            // btnBgBudgetDelete
            //
            this.btnBgBudgetDelete.Caption = "Monatsbudget löschen ...";
            this.btnBgBudgetDelete.Id = 7;
            this.btnBgBudgetDelete.ImageIndex = 4;
            this.btnBgBudgetDelete.Name = "btnBgBudgetDelete";
            this.btnBgBudgetDelete.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btnBgBudgetDelete_ItemClick);
            //
            // btnBgBudgetReset
            //
            this.btnBgBudgetReset.Caption = "Monatsbudget an Masterbudget anpassen ...";
            this.btnBgBudgetReset.Id = 6;
            this.btnBgBudgetReset.ImageIndex = 3;
            this.btnBgBudgetReset.Name = "btnBgBudgetReset";
            this.btnBgBudgetReset.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btnBgBudgetReset_ItemClick);
            //
            // btnBgFinanzplan1
            //
            this.btnBgFinanzplan1.Caption = "neue Überbrückung";
            this.btnBgFinanzplan1.Id = 10;
            this.btnBgFinanzplan1.ImageIndex = 1312;
            this.btnBgFinanzplan1.Name = "btnBgFinanzplan1";
            this.btnBgFinanzplan1.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btnBgFinanzplan1_ItemClick);
            //
            // btnBgFinanzplan2
            //
            this.btnBgFinanzplan2.Caption = "neuer Regulärer Finanzplan";
            this.btnBgFinanzplan2.Id = 11;
            this.btnBgFinanzplan2.ImageIndex = 1312;
            this.btnBgFinanzplan2.Name = "btnBgFinanzplan2";
            this.btnBgFinanzplan2.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btnBgFinanzplan2_ItemClick);
            //
            // btnBgFinanzplanDelete
            //
            this.btnBgFinanzplanDelete.Caption = "Finanzplan löschen";
            this.btnBgFinanzplanDelete.Id = 13;
            this.btnBgFinanzplanDelete.ImageIndex = 4;
            this.btnBgFinanzplanDelete.Name = "btnBgFinanzplanDelete";
            this.btnBgFinanzplanDelete.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btnBgFinanzplanDelete_ItemClick);
            //
            // btnFaLeistung300
            //
            this.btnFaLeistung300.Caption = "Neue Sozialhilfe";
            this.btnFaLeistung300.Id = 0;
            this.btnFaLeistung300.ImageIndex = 1301;
            this.btnFaLeistung300.Name = "btnFaLeistung300";
            this.btnFaLeistung300.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btnFaLeistung300_ItemClick);
            //
            // btnFaLeistungDelete
            //
            this.btnFaLeistungDelete.Caption = "Sozialhilfe löschen";
            this.btnFaLeistungDelete.Id = 2;
            this.btnFaLeistungDelete.ImageIndex = 4;
            this.btnFaLeistungDelete.Name = "btnFaLeistungDelete";
            this.btnFaLeistungDelete.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btnFaLeistungDelete_ItemClick);
            //
            // colBaPersonID
            //
            this.colBaPersonID.FieldName = "BaPersonID";
            this.colBaPersonID.Name = "colBaPersonID";
            this.colBaPersonID.OptionsColumn.AllowSort = false;
            //
            // colDate
            //
            this.colDate.FieldName = "DatumVon";
            this.colDate.Name = "colDate";
            this.colDate.OptionsColumn.AllowSort = false;
            this.colDate.VisibleIndex = 1;
            this.colDate.Width = 100;
            //
            // colFaLeistungID
            //
            this.colFaLeistungID.FieldName = "FaLeistungID";
            this.colFaLeistungID.Name = "colFaLeistungID";
            this.colFaLeistungID.OptionsColumn.AllowSort = false;
            this.colFaLeistungID.Width = 91;
            //
            // colName
            //
            this.colName.Caption = "Sozialhilfe";
            this.colName.FieldName = "Name";
            this.colName.Name = "colName";
            this.colName.OptionsColumn.AllowSort = false;
            this.colName.VisibleIndex = 0;
            this.colName.Width = 250;
            //
            // CtlWhModulTree
            //
            this.Name = "CtlWhModulTree";
            this.Load += new System.EventHandler(this.CtlWhModulTree_Load);
            ((System.ComponentModel.ISupportInitialize)(this.kissTree)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.qryModulTree)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.popup_Tree)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.barManager_Tree)).EndInit();
            this.ResumeLayout(false);
        }

        #endregion

        #region Protected Methods

        protected override void kissTree_AfterFocusNode(object sender, DevExpress.XtraTreeList.NodeEventArgs e)
        {
            if (e == null || e.Node == null)
            {
                ShowDetail(null);
                return;
            }

            try
            {
                Cursor.Current = Cursors.WaitCursor;
                string className = e.Node.GetValue("ClassName") as string;
                Image imgIcon = this.GetIcon(e);
                string titel = e.Node.GetValue("Name") as string;
                KissUserControl ctl = null;

                // Neue WPF Masken (XAML)
                var faLeistungID = e.Node.GetValue("FaLeistungID");
                var baPersonID = e.Node.GetValue("BaPersonID");
                var initParams = new InitParameters
                {
                    BaPersonID = baPersonID as int?,
                    FaLeistungID = faLeistungID as int?,
                    Title = titel,
                };
                var xclassID = Kiss.Infrastructure.IoC.Container.Resolve<ViewFactory>().GetClassID(className);
                if (xclassID.HasValue)
                {
                    var view = new CtlWpfHost(xclassID.Value, initParams);
                    ShowDetail(view, true);
                    return;
                }

                switch (className)
                {
                    case null:
                        this.ShowDetail(ctl, true);
                        return;

                    case "CtlWhLeistung":
                    case "CtlUebersichtFinanzplan":
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className, imgIcon, titel
                            , (int)e.Node.GetValue("FaLeistungID"));
                        break;

                    case "CtlWhFinanzplan":
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className, imgIcon, titel
                            , (int)e.Node.GetValue("BgFinanzplanID"), (int)e.Node.GetValue("BgBudgetID"));
                        break;

                    case "CtlWhPersonen":
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className, imgIcon, titel
                            , (int)e.Node.GetValue("BgFinanzplanID"), (int)e.Node.GetValue("BaPersonID"));
                        break;

                    case "CtlBgUebersicht":
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className, imgIcon, titel
                            , (int)e.Node.GetValue("BgBudgetID"));
                        break;

                    case "CtlBgAlgErwerbsunkosten":
                    case "CtlBgAlimente":
                    case "CtlBgErwerbseinkommen":
                    case "CtlBgGrundbedarf":
                    case "CtlBgKrankenkasse":
                    case "CtlBgVermoegen":
                    case "CtlBgVersicherung":
                    case "CtlBgWohnkosten":
                    case "CtlBgZulagenEFB":
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className, imgIcon, titel
                            , (int)e.Node.GetValue("BgBudgetID"));
                        break;

                    case "CtlBgSil":
                    case "CtlBgSilBerufSozIntegration":
                    case "CtlBgSilAmbulanteErzHilfe":
                    case "CtlBgSilStationaereErzHilfe":
                    case "CtlBgSilWohnTherapEinrichtung":
                    case "CtlBgSilAHVBeitrag":
                    case "CtlBgSilWiedereingliederung":
                    case "CtlBgSilTherapieEntzug":
                    case "CtlBgSilSituationsbedingteLeistungen":
                    case "CtlBgSilKrankheitBehinderungLeistung":
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className, imgIcon, titel
                            , (int)e.Node.GetValue("BgBudgetID"));
                        break;

                    case "CtlWhBudget":
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className, imgIcon, titel
                            , (int)e.Node.GetValue("BgBudgetID"));
                        break;

                    case "CtlWhKontoauszug":
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className, imgIcon, titel
                            , (int)e.Node.GetValue("BaPersonID"));
                        break;

                    case "CtlWhSpezialkonto":
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className, imgIcon, titel
                            , (BgSpezkontoTyp)e.Node.GetValue("BgSpezkontoTypCode")
                            , (int)e.Node.GetValue("FaLeistungID"));
                        break;

                    case "CtlWhASVSErfassung":
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className,
                            (int)e.Node.GetValue("FaLeistungID"));
                        break;

                    default:
                        ctl = (KissUserControl)AssemblyLoader.CreateInstance(className);
                        break;
                }

                this.ApplyEditMaskToSqlQuery(ctl.ActiveSQLQuery);
                this.ShowDetail(ctl, true);
            }
            catch (Exception ex)
            {
                KissMsg.ShowError("CtlWhModulTree", "EintragAnzeigenNichtMoeglich", "Der gewünschte Eintrag kann nicht angezeigt werden", ex);
            }
            finally
            {
                Cursor.Current = Cursors.Default;
            }
        }

        #endregion

        #region Private Methods

        private void barManager_Tree_QueryShowPopupMenu(object sender, DevExpress.XtraBars.QueryShowPopupMenuEventArgs e)
        {
            foreach (DevExpress.XtraBars.BarItemLink barItemLink in e.Menu.ItemLinks)
                barItemLink.Item.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;

            if (kissTree.FocusedNode == null)
            {
                if (DBUtil.UserHasRight("ShNavigNewSozialhilfe"))
                {
                    btnFaLeistung300.Visibility = BarItemVisibility.Always;
                }
            }
            else
            {
                object bgBewilligungStatusCode = DBUtil.ExecuteScalarSQL(@"
                        SELECT BgBewilligungStatusCode
                        FROM dbo.BgFinanzPlan WITH(READUNCOMMITTED)
                        WHERE BgFinanzplanID = {0}",
                    kissTree.FocusedNode.GetValue("BgFinanzplanID"));

                switch (kissTree.FocusedNode.GetValue("ClassName") as string)
                {
                    case "CtlWhLeistung":

                        if (DBUtil.UserHasRight("ShNavigNewSozialhilfe"))
                        {
                            btnFaLeistung300.Visibility = BarItemVisibility.Always;
                        }

                        if (DBUtil.UserHasRight("ShNavigDeleteSozialhilfe"))
                        {
                            btnFaLeistungDelete.Visibility = BarItemVisibility.Always;
                        }

                        btnBgFinanzplan1.Visibility = BarItemVisibility.Always;
                        btnBgFinanzplan2.Visibility = BarItemVisibility.Always;

                        if (DBUtil.UserHasRight("FrmFallZugriff"))
                        {
                            btnFallZugriff.Visibility = BarItemVisibility.Always;
                        }

                        if (DBUtil.UserHasRight("FrmFallInfo"))
                        {
                            btnFallInfo.Visibility = BarItemVisibility.Always;
                        }
                        break;

                    case "CtlWhFinanzplan":
                        btnBgFinanzplanDelete.Visibility = BarItemVisibility.Always;

                        if (DBUtil.UserHasRight("ShNavigNewMonatsbudget")
                          && !(bool)kissTree.FocusedNode.GetValue("Abgeschlossen")
                          && (int)bgBewilligungStatusCode == (int)BgBewilligungStatus.Erteilt)
                        {
                            btnBgBudget.Visibility = BarItemVisibility.Always;
                        }
                        break;

                    case "CtlWhBudget":
                        if ((bool)kissTree.FocusedNode.GetValue("MasterBudget"))
                        {
                            btnBgBudgetResetMaster.Visibility = BarItemVisibility.Always;
                        }
                        else
                        {
                            btnBgBudgetReset.Visibility = BarItemVisibility.Always;

                            if (DBUtil.UserHasRight("ShNavigDeleteMonatsbudget"))
                            {
                                btnBgBudgetDelete.Visibility = BarItemVisibility.Always;
                            }
                        }

                        if (DBUtil.UserHasRight("ShNavigNewMonatsbudget")
                          && !(bool)kissTree.FocusedNode.GetValue("Abgeschlossen")
                          && (int)bgBewilligungStatusCode == (int)BgBewilligungStatus.Erteilt)
                        {
                            btnBgBudget.Visibility = BarItemVisibility.Always;
                        }
                        break;
                }
            }

            foreach (DevExpress.XtraBars.BarItemLink barItemLink in e.Menu.ItemLinks)
                if (barItemLink.Item.Visibility != DevExpress.XtraBars.BarItemVisibility.Never) return;
            e.Cancel = true;
        }

        private void btnBgBudget_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                int bgFinanzplanID = (int)kissTree.FocusedNode.GetValue("BgFinanzplanID");
                object bgBudgetID = DBUtil.ExecuteScalarSQL(@"EXECUTE spWhBudget_Create {0}", bgFinanzplanID);

                if (DBUtil.IsEmpty(bgBudgetID))
                    throw new KissInfoException(KissMsg.GetMLMessage("CtlWhModulTree", "EnthaeltAlleBudgets", "Der Finanzplan enthält bereits sämtliche Monatsbudgets", KissMsgCode.MsgInfo));

                FormController.SendMessage("FrmFall", "Action", "RefreshTree");

                // Eintrag Bewilligungsverlauf
                SqlQuery qry = ShUtil.GetBgBewilligung_Neu();
                qry["BgBewilligungCode"] = 101;
                qry["BgBudgetID"] = (int)bgBudgetID;
                qry.Post();
            }
            catch (KissCancelException ex)
            {
                ex.ShowMessage();
            }
        }

        private void btnBgBudgetDelete_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //ck Habe vorerst mal auf Namen geprüft. Sauberer wäre natürlich eine CtlWhBudget-Oberklasse, aber die müssen ja
            //baldmöglichst wieder zusammengeführt werden.
            if (DetailControl is CtlWhBudget || DetailControl.Name.Equals("CtlWhBudget"))
            {
                try
                {
                    if (!(bool)kissTree.FocusedNode.GetValue("MasterBudget")
                        && (int)kissTree.FocusedNode.GetValue("BgBewilligungStatusCode") < (int)BgBewilligungStatus.Erteilt)
                    {
                        DBUtil.ExecSQLThrowingException(@"
                            EXECUTE spWhBudget_Delete {0}
                            DELETE FROM BgBudget WHERE BgBudgetID = {0}"
                            , (int)kissTree.FocusedNode.GetValue("BgBudgetID"));

                        FormController.SendMessage("FrmFall", "Action", "RefreshTree");
                    }
                    else
                        throw new KissInfoException(KissMsg.GetMLMessage("CtlWhModulTree", "MonatsbudgetLoeschenNichtMoeglich", "Es können nur Monatsbudget im Status 'In Vorbereitung' gelöscht werden", KissMsgCode.MsgInfo));
                }
                catch (KissCancelException ex)
                {
                    ex.ShowMessage();
                }
            }
        }

        //TODO CtlwhBudget sollte nur temporär so laufen. Klassen sollten ja wieder zusammengenommen werden
        // oder eine Oberklasse erstellt werden.
        // --> danach kann dies wieder bereinigt werden!
        private void btnBgBudgetReset_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (DetailControl is CtlWhBudget)
            {
                ((CtlWhBudget)DetailControl).ResetBudget();
            }
        }

        private void btnBgFinanzplan1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            int anzahlFP = (int)DBUtil.ExecuteScalarSQL(@"
                SELECT Count(*)
                FROM BgFinanzPlan
                WHERE FaLeistungID = {0}
                  AND (WhHilfeTypCode = 2
                       OR (WhHilfeTypCode = 1 AND IsNull(DatumBis, GeplantBis) = GeplantBis))", //2: Regulärer Finanzplan, 1: Überbrückungshilfe
                kissTree.FocusedNode.GetValue("FaLeistungID"));
            if (anzahlFP > 0)
            {
                KissMsg.ShowInfo("CtlWhModulTree", "NurErsterFPUeberbrueckung", "Nur der erste Finanzplan kann eine Überbrückung sein.");
                return;
            }

            ShUtil.BgFinanzplanNeu((int)kissTree.FocusedNode.GetValue("FaLeistungID"), KiSS.DBScheme.LOV.WhHilfeTypCode.Ueberbrueckungshilfe);
            return;
        }

        private void btnBgFinanzplan2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            ShUtil.BgFinanzplanNeu((int)kissTree.FocusedNode.GetValue("FaLeistungID"), KiSS.DBScheme.LOV.WhHilfeTypCode.Regulaerer_Finanzplan);
        }

        private void btnBgFinanzplanDelete_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            // #5603: we need to do the following delete-procedure within a transaction to prevent deleting only parts of the data
            // start transaction
            Session.BeginTransaction();

            try
            {
                // get id
                int BgFinanzplanID = (int)kissTree.FocusedNode.GetValue("BgFinanzplanID");

                // delete data
                DBUtil.ExecSQLThrowingException(@"
                    EXECUTE dbo.spWhFinanzPlan_Delete {0}", BgFinanzplanID);

                DBUtil.ExecSQLThrowingException(@"
                    DELETE FROM dbo.BgFinanzplan
                    WHERE BgFinanzplanID = {0}", BgFinanzplanID);

                // persist
                Session.Commit();

                // refresh tree
                FormController.SendMessage("FrmFall", "Action", "RefreshTree");
            }
            catch (Exception ex)
            {
                // undo changes
                Session.Rollback();

                if (ex is KissCancelException)
                {
                    // show cancel-message
                    ((KissCancelException)ex).ShowMessage();
                }
                else
                {
                    // show error message
                    KissMsg.ShowError(this.Name, "ErrorDeleteFinanzplan", "Es ist ein Fehler beim Löschen des Finanzplans aufgetreten.", ex);
                }
            }
        }

        private void btnFaLeistung300_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                this.FaLeistungNeu(300);
            }
            catch (Exception ex)
            {
                if (ex is KissInfoException)
                {
                    ((KissInfoException)ex).ShowMessage();
                }
                else
                {
                    throw;
                }
            }
        }

        private void btnFaLeistungDelete_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (DetailControl is CtlWhLeistung)
            {
                ((IKissDataNavigator)DetailControl).DeleteData();
            }

            FormController.SendMessage("FrmFall", "Action", "RefreshTree");
            FormController.SendMessage("FrmFallNavigator", "Action", "RefreshTree");
        }

        private void CtlWhModulTree_Load(object sender, System.EventArgs e)
        {
            kissTree.DataSource = null; //sonst Exception: open DataReader!
            this.FillTree();

            // oberste Unterstützungsperiode expandieren
            if (this.kissTree.Nodes.Count > 0 && this.kissTree.Nodes[0].Nodes.Count > 0)
            {
                this.kissTree.Nodes[0].Expanded = true; // Sozialhilfe
                this.kissTree.Nodes[0].Nodes[0].Expanded = true; // Unterstützungsperioden
                if (this.kissTree.Nodes[0].Nodes[0].Nodes.Count > 0)
                {
                    this.kissTree.Nodes[0].Nodes[0].Nodes[0].Expanded = true; // Unterstützungsperiode
                }
            }
        }

        private void FaLeistungNeu(int FaProzessCode)
        {
            // Wenn noch eine offene Sozialhilfe existiert soll keine neue angelegt werden
            int offeneSH = (int)DBUtil.ExecuteScalarSQL(@"
                SELECT COUNT(*)
                FROM   FaLeistung WITH (READUNCOMMITTED)
                WHERE  BaPersonID = {0}
                  AND  ModulID = {1}
                  AND  DatumBis IS NULL;", this.BaPersonID, this.ModulID);

            if (offeneSH > 0)
            {
                throw new KissInfoException(KissMsg.GetMLMessage("CtlWhModulTree", "OffeneSozialhilfe", "Die letzte Sozialhilfe ist noch nicht abgeschlossen.", KissMsgCode.MsgInfo));
            }

            int? leistungsArt = DBUtil.GetConfigInt(@"System\Sozialhilfe\BfsLeistungsArtBeiEroeffnenSH", 0);
            leistungsArt = DBUtil.ExecuteScalarSQL(@"
                                 SELECT Code
                                   FROM  dbo.XLOVCode LOC
                                  WHERE LOVName='Leistungsart'
                                    AND Code = {0}", leistungsArt) as int?;

            DBUtil.ExecSQL(@"
                INSERT INTO FaLeistung (FaFallID, BaPersonID, ModulID, FaProzessCode, DatumVon, UserID, Creator, Created, Modifier, Modified, LeistungsartCode)
                  SELECT TOP 1 FaFallID, BaPersonID, 3, {2}, dbo.fnDateOf(GetDate()), {1}, {3}, GetDate(), {3}, GetDate(), {4}
                  FROM FaFall
                  WHERE BaPersonID = {0}
                  ORDER BY DatumBis, DatumVon DESC", this.BaPersonID, Session.User.UserID, FaProzessCode, DBUtil.GetDBRowCreatorModifier(), leistungsArt);

            FormController.SendMessage("FrmFall", "Action", "RefreshTree");
            FormController.SendMessage("FrmFallNavigator", "Action", "RefreshTree");
            this.kissTree.MoveFirst();
            this.kissTree.FocusedNode.Expanded = true;

            ShUtil.CreateTaskForDoubleSupport_NeueSozialhilfe(Session.User.UserID, this.BaPersonID.ToString());
        }

        #endregion
    }
}