SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO
EXECUTE dbo.spDropObject fnXAHVNummer
GO
/*===============================================================================================
  $Archive: /Database/KISS4_BSS_MasterDev/Functions/fnXAHVNummer.sql $
  $Author: Ckaeser $
  $Modtime: 24.06.09 16:07 $
  $Revision: 2 $
=================================================================================================
  Description
-------------------------------------------------------------------------------------------------
  SUMMARY: .
    @Param1   .
    @Param20: .
  -
  RETURNS: .
  -
  TEST:    .
=================================================================================================
  $Log: /Database/KISS4_BSS_MasterDev/Functions/fnXAHVNummer.sql $
 * 
 * 2     25.06.09 8:17 Ckaeser
 * Alter2Create
 * 
 * 1     13.09.08 17:06 Aklopfenstein
 * VSS First
=================================================================================================*/
/*
  KiSS 4.0
  --------
  DB-Object: fnXAHVNummer
  Branch   : KiSS_40_CORE
  BuildNr  : 1
  Datum    : 21.06.2008 19:27
*/
CREATE FUNCTION dbo.fnXAHVNummer
 (@Name           varchar(100),
  @Geburtsdatum   datetime,
  @GeschlechtCode int)
  RETURNS varchar(14)
AS 

BEGIN
  DECLARE @AHV   varchar(14)

  SET @Name = REPLACE(LOWER(@Name), 'sch', 's~')

  SET @AHV = CONVERT(varchar, CASE
      WHEN @Name > 'zy'   THEN 999
      WHEN @Name > 'zwe'  THEN 998
      WHEN @Name > 'zw'   THEN 997
      WHEN @Name > 'zus'  THEN 996
      WHEN @Name > 'zur'  THEN 995
      WHEN @Name > 'zun'  THEN 994
      WHEN @Name > 'zum'  THEN 993
      WHEN @Name > 'zul'  THEN 992
      WHEN @Name > 'zuc'  THEN 991
      WHEN @Name > 'zu'   THEN 990
      WHEN @Name > 'zo'   THEN 989
      WHEN @Name > 'zk'   THEN 988
      WHEN @Name > 'zin'  THEN 987
      WHEN @Name > 'zim'  THEN 986
      WHEN @Name > 'zi'   THEN 985
      WHEN @Name > 'zf'   THEN 984
      WHEN @Name > 'zem'  THEN 983
      WHEN @Name > 'zei'  THEN 982
      WHEN @Name > 'zeh'  THEN 981
      WHEN @Name > 'ze'   THEN 980
      WHEN @Name > 'zb'   THEN 979
      WHEN @Name > 'zau'  THEN 978
      WHEN @Name > 'zam'  THEN 977
      WHEN @Name > 'z'    THEN 976
      WHEN @Name > 'x'    THEN 975
      WHEN @Name > 'wyt'  THEN 974
      WHEN @Name > 'wyss' THEN 973
      WHEN @Name > 'wys'  THEN 972
      WHEN @Name > 'wym'  THEN 971
      WHEN @Name > 'wy'   THEN 970
      WHEN @Name > 'wut'  THEN 969
      WHEN @Name > 'wur'  THEN 968
      WHEN @Name > 'wun'  THEN 967
      WHEN @Name > 'wui'  THEN 966
      WHEN @Name > 'wu'   THEN 965
      WHEN @Name > 'wol'  THEN 964
      WHEN @Name > 'wo'   THEN 963
      WHEN @Name > 'witt' THEN 962
      WHEN @Name > 'wit'  THEN 961
      WHEN @Name > 'wis'  THEN 960
      WHEN @Name > 'wir'  THEN 959
      WHEN @Name > 'wip'  THEN 958
      WHEN @Name > 'wim'  THEN 957
      WHEN @Name > 'wile' THEN 956
      WHEN @Name > 'wil'  THEN 955
      WHEN @Name > 'wif'  THEN 954
      WHEN @Name > 'wiel' THEN 953
      WHEN @Name > 'wie'  THEN 952
      WHEN @Name > 'wid'  THEN 951
      WHEN @Name > 'wi'   THEN 950
      WHEN @Name > 'weu'  THEN 949
      WHEN @Name > 'wes'  THEN 948
      WHEN @Name > 'wern' THEN 947
      WHEN @Name > 'wer'  THEN 946
      WHEN @Name > 'wen'  THEN 945
      WHEN @Name > 'wek'  THEN 944
      WHEN @Name > 'weit' THEN 943
      WHEN @Name > 'weis' THEN 942
      WHEN @Name > 'weif' THEN 941
      WHEN @Name > 'wei'  THEN 940
      WHEN @Name > 'weh'  THEN 939
      WHEN @Name > 'wec'  THEN 938
      WHEN @Name > 'we'   THEN 937
      WHEN @Name > 'wat'  THEN 936
      WHEN @Name > 'was'  THEN 935
      WHEN @Name > 'wap'  THEN 934
      WHEN @Name > 'wam'  THEN 933
      WHEN @Name > 'walt' THEN 932
      WHEN @Name > 'wall' THEN 931
      WHEN @Name > 'wale' THEN 930
      WHEN @Name > 'wald' THEN 929
      WHEN @Name > 'wal'  THEN 928
      WHEN @Name > 'wah'  THEN 927
      WHEN @Name > 'wag'  THEN 926
      WHEN @Name > 'w'    THEN 925
      WHEN @Name > 'vu'   THEN 924
      WHEN @Name > 'voo'  THEN 923
      WHEN @Name > 'vono' THEN 922
      WHEN @Name > 'vong' THEN 921
      WHEN @Name > 'von'  THEN 920
      WHEN @Name > 'vol'  THEN 919
      WHEN @Name > 'voh'  THEN 918
      WHEN @Name > 'vog'  THEN 917
      WHEN @Name > 'vog'  THEN 916
      WHEN @Name > 'vo'   THEN 915
      WHEN @Name > 'vio'  THEN 914
      WHEN @Name > 'vil'  THEN 913
      WHEN @Name > 'vi'   THEN 912
      WHEN @Name > 'vet'  THEN 911
      WHEN @Name > 've'   THEN 910
      WHEN @Name > 'vau'  THEN 909
      WHEN @Name > 'var'  THEN 908
      WHEN @Name > 'vam'  THEN 907
      WHEN @Name > 'val'  THEN 906
      WHEN @Name > 'v'    THEN 905
      WHEN @Name > 'ur'   THEN 904
      WHEN @Name > 'um'   THEN 903
      WHEN @Name > 'ul'   THEN 902
      WHEN @Name > 'uf'   THEN 901
      WHEN @Name > 'u'    THEN 900
      WHEN @Name > 'tu'    THEN 899
      WHEN @Name > 'tschu' THEN 898
      WHEN @Name > 'tsche' THEN 897
      WHEN @Name > 'tscha' THEN 896
      WHEN @Name > 'ts'   THEN 895
      WHEN @Name > 'tru'  THEN 894
      WHEN @Name > 'tro'  THEN 893
      WHEN @Name > 'tri'  THEN 892
      WHEN @Name > 'tre'  THEN 891
      WHEN @Name > 'tr'   THEN 890
      WHEN @Name > 'tor'  THEN 889
      WHEN @Name > 'tog'  THEN 888
      WHEN @Name > 'to'   THEN 887
      WHEN @Name > 'tir'  THEN 886
      WHEN @Name > 'ti'   THEN 885
      WHEN @Name > 'thr'  THEN 884
      WHEN @Name > 'thon' THEN 883
      WHEN @Name > 'tho'  THEN 882
      WHEN @Name > 'the'  THEN 881
      WHEN @Name > 'th'   THEN 880
      WHEN @Name > 'ter'  THEN 879
      WHEN @Name > 'te'   THEN 878
      WHEN @Name > 'tao'  THEN 877
      WHEN @Name > 'tan'  THEN 876
      WHEN @Name > 't'    THEN 875
      WHEN @Name > 'stus' THEN 874
      WHEN @Name > 'stuf' THEN 873
      WHEN @Name > 'stud' THEN 872
      WHEN @Name > 'stuc' THEN 871
      WHEN @Name > 'stu'  THEN 870
      WHEN @Name > 'stru' THEN 869
      WHEN @Name > 'stri' THEN 868
      WHEN @Name > 'stre' THEN 867
      WHEN @Name > 'strau' THEN 866
      WHEN @Name > 'str'  THEN 865
      WHEN @Name > 'stoo' THEN 864
      WHEN @Name > 'stol' THEN 863
      WHEN @Name > 'stod' THEN 862
      WHEN @Name > 'sto'  THEN 861
      WHEN @Name > 'sti'  THEN 860
      WHEN @Name > 'stek' THEN 859
      WHEN @Name > 'stein' THEN 858
      WHEN @Name > 'stei' THEN 857
      WHEN @Name > 'stef' THEN 856
      WHEN @Name > 'ste'  THEN 855
      WHEN @Name > 'stau' THEN 854
      WHEN @Name > 'stan1' THEN 853
      WHEN @Name > 'stal' THEN 852
      WHEN @Name > 'stah' THEN 851
      WHEN @Name > 'st'   THEN 850
      WHEN @Name > 'sv'   THEN 799
      WHEN @Name > 'sut'  THEN 798
      WHEN @Name > 'su'   THEN 797
      WHEN @Name > 'sq'   THEN 796
      WHEN @Name > 'spo'  THEN 795
      WHEN @Name > 'spi'  THEN 794
      WHEN @Name > 'sp'   THEN 793
      WHEN @Name > 'som'  THEN 792
      WHEN @Name > 'so'   THEN 791
      WHEN @Name > 'sk'   THEN 790
      WHEN @Name > 'sim'  THEN 789
      WHEN @Name > 'sif'  THEN 788
      WHEN @Name > 'sieg' THEN 787
      WHEN @Name > 'si'   THEN 786
      WHEN @Name > 'sf'   THEN 785
      WHEN @Name > 'seo'  THEN 784
      WHEN @Name > 'sen'  THEN 783
      WHEN @Name > 'sei'  THEN 782
      WHEN @Name > 'se'   THEN 781
      WHEN @Name > 'sb'   THEN 780
      WHEN @Name > 'sav'  THEN 779
      WHEN @Name > 'sar'  THEN 778
      WHEN @Name > 'sam'  THEN 777
      WHEN @Name > 'sal'  THEN 776
      WHEN @Name > 's'    THEN 775
      WHEN @Name > 's~wi'   THEN 849
      WHEN @Name > 's~wek'  THEN 848
      WHEN @Name > 's~weiz' THEN 847
      WHEN @Name > 's~wei'  THEN 846
      WHEN @Name > 's~we'   THEN 845
      WHEN @Name > 's~warz' THEN 844
      WHEN @Name > 's~war'  THEN 843
      WHEN @Name > 's~wac'  THEN 842
      WHEN @Name > 's~wab'  THEN 841
      WHEN @Name > 's~w'    THEN 840
      WHEN @Name > 's~us'   THEN 839
      WHEN @Name > 's~ur'   THEN 838
      WHEN @Name > 's~um'   THEN 837
      WHEN @Name > 's~ul'   THEN 836
      WHEN @Name > 's~u'    THEN 835
      WHEN @Name > 's~r'    THEN 834
      WHEN @Name > 's~or'   THEN 833
      WHEN @Name > 's~oo'   THEN 832
      WHEN @Name > 's~on'   THEN 831
      WHEN @Name > 's~o'    THEN 830
      WHEN @Name > 's~ny'   THEN 829
      WHEN @Name > 's~ni'   THEN 828
      WHEN @Name > 's~nek'  THEN 827
      WHEN @Name > 's~nei'  THEN 826
      WHEN @Name > 's~n'    THEN 825
      WHEN @Name > 's~mo'   THEN 824
      WHEN @Name > 's~mie'  THEN 823
      WHEN @Name > 's~mida' THEN 822
      WHEN @Name > 's~mid'  THEN 821
      WHEN @Name > 's~m'  THEN 820
      WHEN @Name > 's~lu' THEN 819
      WHEN @Name > 's~le' THEN 818
      WHEN @Name > 's~l'  THEN 817
      WHEN @Name > 's~il' THEN 816
      WHEN @Name > 's~i'  THEN 815
      WHEN @Name > 's~eu' THEN 814
      WHEN @Name > 's~er' THEN 813
      WHEN @Name > 's~en' THEN 812
      WHEN @Name > 's~el' THEN 811
      WHEN @Name > 's~e'  THEN 810
      WHEN @Name > 's~av' THEN 809
      WHEN @Name > 's~au' THEN 808
      WHEN @Name > 's~as' THEN 807
      WHEN @Name > 's~arl' THEN 806
      WHEN @Name > 's~arb' THEN 805
      WHEN @Name > 's~ar' THEN 804
      WHEN @Name > 's~al' THEN 803
      WHEN @Name > 's~af' THEN 802
      WHEN @Name > 's~ad' THEN 801
      WHEN @Name > 's~'   THEN 800
      WHEN @Name > 'ry'   THEN 774
      WHEN @Name > 'rut'  THEN 773
      WHEN @Name > 'rus'  THEN 772
      WHEN @Name > 'rup'  THEN 771
      WHEN @Name > 'ruh'  THEN 770
      WHEN @Name > 'rug'  THEN 769
      WHEN @Name > 'ruf'  THEN 768
      WHEN @Name > 'rud'  THEN 767
      WHEN @Name > 'ruc'  THEN 766
      WHEN @Name > 'ru'   THEN 765
      WHEN @Name > 'rou'  THEN 764
      WHEN @Name > 'roti' THEN 763
      WHEN @Name > 'rotha' THEN 762
      WHEN @Name > 'roth' THEN 761
      WHEN @Name > 'rot'  THEN 760
      WHEN @Name > 'ross' THEN 759
      WHEN @Name > 'ros'  THEN 758
      WHEN @Name > 'roo'  THEN 757
      WHEN @Name > 'rom'  THEN 756
      WHEN @Name > 'roi'  THEN 755
      WHEN @Name > 'rohr' THEN 754
      WHEN @Name > 'roh'  THEN 753
      WHEN @Name > 'rod'  THEN 752
      WHEN @Name > 'roc'  THEN 751
      WHEN @Name > 'ro'   THEN 750
      WHEN @Name > 'riv'  THEN 749
      WHEN @Name > 'rit'  THEN 748
      WHEN @Name > 'rio'  THEN 747
      WHEN @Name > 'rin'  THEN 746
      WHEN @Name > 'rif'  THEN 745
      WHEN @Name > 'rieg' THEN 744
      WHEN @Name > 'rie'  THEN 743
      WHEN @Name > 'rid'  THEN 742
      WHEN @Name > 'ric'  THEN 741
      WHEN @Name > 'ri'   THEN 740
      WHEN @Name > 'rh'   THEN 739
      WHEN @Name > 'rey'  THEN 738
      WHEN @Name > 'reo'  THEN 737
      WHEN @Name > 'reni' THEN 736
      WHEN @Name > 'ren'  THEN 735
      WHEN @Name > 'rek'  THEN 734
      WHEN @Name > 'rein' THEN 733
      WHEN @Name > 'rei'  THEN 732
      WHEN @Name > 'rec'  THEN 731
      WHEN @Name > 're'   THEN 730
      WHEN @Name > 'rau'  THEN 729
      WHEN @Name > 'ras'  THEN 728
      WHEN @Name > 'ran'  THEN 727
      WHEN @Name > 'ram'  THEN 726
      WHEN @Name > 'r'    THEN 725
      WHEN @Name > 'q'    THEN 724
      WHEN @Name > 'pu'   THEN 723
      WHEN @Name > 'pr'   THEN 722
      WHEN @Name > 'por'  THEN 721
      WHEN @Name > 'po'   THEN 720
      WHEN @Name > 'pl'   THEN 719
      WHEN @Name > 'pir'  THEN 718
      WHEN @Name > 'pig'  THEN 717
      WHEN @Name > 'pi'   THEN 716
      WHEN @Name > 'ph'   THEN 715
      WHEN @Name > 'pfi'  THEN 714
      WHEN @Name > 'pf'   THEN 713
      WHEN @Name > 'peu'  THEN 712
      WHEN @Name > 'pet'  THEN 711
      WHEN @Name > 'pes'  THEN 710
      WHEN @Name > 'pers' THEN 709
      WHEN @Name > 'perri' THEN 708
      WHEN @Name > 'per'  THEN 707
      WHEN @Name > 'pel'  THEN 706
      WHEN @Name > 'pe'   THEN 705
      WHEN @Name > 'pat'  THEN 704
      WHEN @Name > 'par'  THEN 703
      WHEN @Name > 'pan'  THEN 702
      WHEN @Name > 'pag'  THEN 701
      WHEN @Name > 'p'    THEN 700
      WHEN @Name > 'ou'   THEN 699
      WHEN @Name > 'ot'   THEN 698
      WHEN @Name > 'os'   THEN 697
      WHEN @Name > 'op'   THEN 696
      WHEN @Name > 'ok'   THEN 695
      WHEN @Name > 'of'   THEN 694
      WHEN @Name > 'od'   THEN 693
      WHEN @Name > 'oc'   THEN 692
      WHEN @Name > 'obi'  THEN 691
      WHEN @Name > 'o'    THEN 690
      WHEN @Name > 'nyf'  THEN 689
      WHEN @Name > 'ny'   THEN 688
      WHEN @Name > 'nu'   THEN 687
      WHEN @Name > 'not'  THEN 686
      WHEN @Name > 'no'   THEN 685
      WHEN @Name > 'nif'  THEN 684
      WHEN @Name > 'nief' THEN 683
      WHEN @Name > 'niederg' THEN 682
      WHEN @Name > 'nie'  THEN 681
      WHEN @Name > 'ni'   THEN 680
      WHEN @Name > 'neu'  THEN 679
      WHEN @Name > 'neg'  THEN 678
      WHEN @Name > 'ne'   THEN 677
      WHEN @Name > 'nag'  THEN 676
      WHEN @Name > 'n'    THEN 675
      WHEN @Name > 'mus'  THEN 674
      WHEN @Name > 'mur'  THEN 673
      WHEN @Name > 'mum'  THEN 672
      WHEN @Name > 'mull' THEN 671
      WHEN @Name > 'mul'  THEN 670
      WHEN @Name > 'muh'  THEN 669
      WHEN @Name > 'mu'   THEN 668
      WHEN @Name > 'mot'  THEN 667
      WHEN @Name > 'mosi' THEN 666
      WHEN @Name > 'mose' THEN 665
      WHEN @Name > 'mos'  THEN 664
      WHEN @Name > 'morg' THEN 663
      WHEN @Name > 'more' THEN 662
      WHEN @Name > 'mor'  THEN 661
      WHEN @Name > 'moo'  THEN 660
      WHEN @Name > 'mono' THEN 659
      WHEN @Name > 'monn' THEN 658
      WHEN @Name > 'mon'  THEN 657
      WHEN @Name > 'moi'  THEN 656
      WHEN @Name > 'mo'   THEN 655
      WHEN @Name > 'mir'  THEN 654
      WHEN @Name > 'min'  THEN 653
      WHEN @Name > 'mid'  THEN 652
      WHEN @Name > 'mic'  THEN 651
      WHEN @Name > 'mi'   THEN 650
      WHEN @Name > 'meyf' THEN 649
      WHEN @Name > 'meyer' THEN 648
      WHEN @Name > 'mey'  THEN 647
      WHEN @Name > 'met'  THEN 646
      WHEN @Name > 'mes'  THEN 645
      WHEN @Name > 'mer'  THEN 644
      WHEN @Name > 'mek'  THEN 643
      WHEN @Name > 'meif' THEN 642
      WHEN @Name > 'meier' THEN 641
      WHEN @Name > 'me'   THEN 640
      WHEN @Name > 'may'  THEN 639
      WHEN @Name > 'mau'  THEN 638
      WHEN @Name > 'matt' THEN 637
      WHEN @Name > 'mat'  THEN 636
      WHEN @Name > 'mas'  THEN 635
      WHEN @Name > 'maru' THEN 634
      WHEN @Name > 'martin' THEN 633
      WHEN @Name > 'mart' THEN 632
      WHEN @Name > 'marg' THEN 631
      WHEN @Name > 'mar'  THEN 630
      WHEN @Name > 'mak'  THEN 629
      WHEN @Name > 'mai'  THEN 628
      WHEN @Name > 'mag'  THEN 627
      WHEN @Name > 'mad'  THEN 626
      WHEN @Name > 'm'    THEN 625
      WHEN @Name > 'ly'   THEN 624
      WHEN @Name > 'luu'  THEN 623
      WHEN @Name > 'luti' THEN 622
      WHEN @Name > 'luth' THEN 621
      WHEN @Name > 'lut'  THEN 620
      WHEN @Name > 'lus'  THEN 619
      WHEN @Name > 'lui'  THEN 618
      WHEN @Name > 'lug'  THEN 617
      WHEN @Name > 'lud'  THEN 616
      WHEN @Name > 'lu'   THEN 615
      WHEN @Name > 'lot'  THEN 614
      WHEN @Name > 'lor'  THEN 613
      WHEN @Name > 'loo'  THEN 612
      WHEN @Name > 'lof'  THEN 611
      WHEN @Name > 'lo'   THEN 610
      WHEN @Name > 'lis'  THEN 609
      WHEN @Name > 'lio'  THEN 608
      WHEN @Name > 'line' THEN 607
      WHEN @Name > 'lind' THEN 606
      WHEN @Name > 'lin'  THEN 605
      WHEN @Name > 'lif'  THEN 604
      WHEN @Name > 'lied' THEN 603
      WHEN @Name > 'liec' THEN 602
      WHEN @Name > 'lie'  THEN 601
      WHEN @Name > 'li'   THEN 600
      WHEN @Name > 'lev'  THEN 599
      WHEN @Name > 'leut' THEN 598
      WHEN @Name > 'leuf' THEN 597
      WHEN @Name > 'leue' THEN 596
      WHEN @Name > 'leu'  THEN 595
      WHEN @Name > 'ler'  THEN 594
      WHEN @Name > 'leo'  THEN 593
      WHEN @Name > 'lek'  THEN 592
      WHEN @Name > 'leip' THEN 591
      WHEN @Name > 'lei'  THEN 590
      WHEN @Name > 'lehn' THEN 589
      WHEN @Name > 'leh'  THEN 588
      WHEN @Name > 'lee'  THEN 587
      WHEN @Name > 'led'  THEN 586
      WHEN @Name > 'le'   THEN 585
      WHEN @Name > 'lav'  THEN 584
      WHEN @Name > 'laud' THEN 583
      WHEN @Name > 'lau'  THEN 582
      WHEN @Name > 'lat'  THEN 581
      WHEN @Name > 'lao'  THEN 580
      WHEN @Name > 'lanh' THEN 579
      WHEN @Name > 'lang' THEN 578
      WHEN @Name > 'lan'  THEN 577
      WHEN @Name > 'laf'  THEN 576
      WHEN @Name > 'l'    THEN 575
      WHEN @Name > 'kus'  THEN 574
      WHEN @Name > 'kur'  THEN 573
      WHEN @Name > 'kuo'  THEN 572
      WHEN @Name > 'kunzi' THEN 571
      WHEN @Name > 'kunz' THEN 570
      WHEN @Name > 'kun'  THEN 569
      WHEN @Name > 'kui'  THEN 568
      WHEN @Name > 'kuh'  THEN 567
      WHEN @Name > 'kuc'  THEN 566
      WHEN @Name > 'ku'   THEN 565
      WHEN @Name > 'kru'  THEN 564
      WHEN @Name > 'kri'  THEN 563
      WHEN @Name > 'kre'  THEN 562
      WHEN @Name > 'krap' THEN 561
      WHEN @Name > 'kr'   THEN 560
      WHEN @Name > 'kot'  THEN 559
      WHEN @Name > 'kor'  THEN 558
      WHEN @Name > 'kop'  THEN 557
      WHEN @Name > 'kom'  THEN 556
      WHEN @Name > 'koll' THEN 555
      WHEN @Name > 'kol'  THEN 554
      WHEN @Name > 'koh'  THEN 553
      WHEN @Name > 'kod'  THEN 552
      WHEN @Name > 'koc'  THEN 551
      WHEN @Name > 'ko'   THEN 550
      WHEN @Name > 'kno'  THEN 549
      WHEN @Name > 'kn'   THEN 548
      WHEN @Name > 'kli'  THEN 547
      WHEN @Name > 'kle'  THEN 546
      WHEN @Name > 'kl'   THEN 545
      WHEN @Name > 'kis'  THEN 544
      WHEN @Name > 'kir'  THEN 543
      WHEN @Name > 'kim'  THEN 542
      WHEN @Name > 'kif'  THEN 541
      WHEN @Name > 'ki'   THEN 540
      WHEN @Name > 'ket'  THEN 539
      WHEN @Name > 'kes'  THEN 538
      WHEN @Name > 'kem'  THEN 537
      WHEN @Name > 'kel'  THEN 536
      WHEN @Name > 'ke'   THEN 535
      WHEN @Name > 'kau'  THEN 534
      WHEN @Name > 'kat'  THEN 533
      WHEN @Name > 'kasp' THEN 532
      WHEN @Name > 'kas'  THEN 531
      WHEN @Name > 'kar'  THEN 530
      WHEN @Name > 'kan'  THEN 529
      WHEN @Name > 'kam'  THEN 528
      WHEN @Name > 'kal'  THEN 527
      WHEN @Name > 'kah'  THEN 526
      WHEN @Name > 'k'    THEN 525
      WHEN @Name > 'juo'  THEN 524
      WHEN @Name > 'junk' THEN 523
      WHEN @Name > 'jun'  THEN 522
      WHEN @Name > 'juf'  THEN 521
      WHEN @Name > 'ju'   THEN 520
      WHEN @Name > 'jot'  THEN 519
      WHEN @Name > 'jos'  THEN 518
      WHEN @Name > 'jor'  THEN 517
      WHEN @Name > 'jol'  THEN 516
      WHEN @Name > 'jo'   THEN 515
      WHEN @Name > 'jep'  THEN 514
      WHEN @Name > 'jen'  THEN 513
      WHEN @Name > 'jeh'  THEN 512
      WHEN @Name > 'jec'  THEN 511
      WHEN @Name > 'je'   THEN 510
      WHEN @Name > 'jar'  THEN 509
      WHEN @Name > 'jan'  THEN 508
      WHEN @Name > 'jah'  THEN 507
      WHEN @Name > 'jad'  THEN 506
      WHEN @Name > 'j'    THEN 505
      WHEN @Name > 'it'   THEN 504
      WHEN @Name > 'is'   THEN 503
      WHEN @Name > 'in'   THEN 502
      WHEN @Name > 'im'   THEN 501
      WHEN @Name > 'i'    THEN 500
      WHEN @Name > 'huw'  THEN 499
      WHEN @Name > 'hut'  THEN 498
      WHEN @Name > 'hus'  THEN 497
      WHEN @Name > 'hurn' THEN 496
      WHEN @Name > 'hur'  THEN 495
      WHEN @Name > 'huo'  THEN 494
      WHEN @Name > 'hunz' THEN 493
      WHEN @Name > 'huni' THEN 492
      WHEN @Name > 'hun'  THEN 491
      WHEN @Name > 'huh'  THEN 490
      WHEN @Name > 'hugi' THEN 489
      WHEN @Name > 'hug'  THEN 488
      WHEN @Name > 'huc'  THEN 487
      WHEN @Name > 'hubf' THEN 486
      WHEN @Name > 'hu'   THEN 485
      WHEN @Name > 'hot'  THEN 484
      WHEN @Name > 'hor'  THEN 483
      WHEN @Name > 'hom'  THEN 482
      WHEN @Name > 'hol'  THEN 481
      WHEN @Name > 'hog'  THEN 480
      WHEN @Name > 'hofn' THEN 479
      WHEN @Name > 'hofm' THEN 478
      WHEN @Name > 'hofl' THEN 477
      WHEN @Name > 'hof'  THEN 476
      WHEN @Name > 'ho'   THEN 475
      WHEN @Name > 'his'  THEN 474
      WHEN @Name > 'hirt' THEN 473
      WHEN @Name > 'hir'  THEN 472
      WHEN @Name > 'him'  THEN 471
      WHEN @Name > 'hi'   THEN 470
      WHEN @Name > 'het'  THEN 469
      WHEN @Name > 'hes'  THEN 468
      WHEN @Name > 'herz' THEN 467
      WHEN @Name > 'hers' THEN 466
      WHEN @Name > 'herr' THEN 465
      WHEN @Name > 'herm' THEN 464
      WHEN @Name > 'her'  THEN 463
      WHEN @Name > 'heo'  THEN 462
      WHEN @Name > 'heno' THEN 461
      WHEN @Name > 'heng' THEN 460
      WHEN @Name > 'hen'  THEN 459
      WHEN @Name > 'hem'  THEN 458
      WHEN @Name > 'hell' THEN 457
      WHEN @Name > 'helf' THEN 456
      WHEN @Name > 'hel'  THEN 455
      WHEN @Name > 'hein' THEN 454
      WHEN @Name > 'hei'  THEN 453
      WHEN @Name > 'heg'  THEN 452
      WHEN @Name > 'hee'  THEN 451
      WHEN @Name > 'he'   THEN 450
      WHEN @Name > 'hav'  THEN 449
      WHEN @Name > 'haut' THEN 448
      WHEN @Name > 'hausf' THEN 447
      WHEN @Name > 'haus' THEN 446
      WHEN @Name > 'hau'  THEN 445
      WHEN @Name > 'hat'  THEN 444
      WHEN @Name > 'has'  THEN 443
      WHEN @Name > 'hart' THEN 442
      WHEN @Name > 'har'  THEN 441
      WHEN @Name > 'hao'  THEN 440
      WHEN @Name > 'hann' THEN 439
      WHEN @Name > 'han'  THEN 438
      WHEN @Name > 'ham'  THEN 437
      WHEN @Name > 'hall' THEN 436
      WHEN @Name > 'hal'  THEN 435
      WHEN @Name > 'hah'  THEN 434
      WHEN @Name > 'hag'  THEN 433
      WHEN @Name > 'hafn' THEN 432
      WHEN @Name > 'hafl' THEN 431
      WHEN @Name > 'haf'  THEN 430
      WHEN @Name > 'had'  THEN 429
      WHEN @Name > 'hac'  THEN 428
      WHEN @Name > 'habi' THEN 427
      WHEN @Name > 'hab'  THEN 426
      WHEN @Name > 'h'    THEN 425
      WHEN @Name > 'gw'   THEN 424
      WHEN @Name > 'gut'  THEN 423
      WHEN @Name > 'gun'  THEN 422
      WHEN @Name > 'gui'  THEN 421
      WHEN @Name > 'gug'  THEN 420
      WHEN @Name > 'gud'  THEN 419
      WHEN @Name > 'gu'   THEN 418
      WHEN @Name > 'gs'   THEN 417
      WHEN @Name > 'grup' THEN 416
      WHEN @Name > 'gru'  THEN 415
      WHEN @Name > 'grot' THEN 414
      WHEN @Name > 'gros' THEN 413
      WHEN @Name > 'gro'  THEN 412
      WHEN @Name > 'grim' THEN 411
      WHEN @Name > 'gri'  THEN 410
      WHEN @Name > 'gres' THEN 409
      WHEN @Name > 'gre'  THEN 408
      WHEN @Name > 'grag' THEN 407
      WHEN @Name > 'graf' THEN 406
      WHEN @Name > 'gr'   THEN 405
      WHEN @Name > 'gom'  THEN 404
      WHEN @Name > 'go'   THEN 403
      WHEN @Name > 'gn'   THEN 402
      WHEN @Name > 'gle'  THEN 401
      WHEN @Name > 'gl'   THEN 400
      WHEN @Name > 'gis'  THEN 399
      WHEN @Name > 'gir'  THEN 398
      WHEN @Name > 'gim'  THEN 397
      WHEN @Name > 'gil'  THEN 396
      WHEN @Name > 'gig'  THEN 395
      WHEN @Name > 'gi'   THEN 394
      WHEN @Name > 'gf'   THEN 393
      WHEN @Name > 'ges'  THEN 392
      WHEN @Name > 'gerd' THEN 391
      WHEN @Name > 'ger'  THEN 390
      WHEN @Name > 'geo'  THEN 389
      WHEN @Name > 'gel'  THEN 388
      WHEN @Name > 'gei'  THEN 387
      WHEN @Name > 'geh'  THEN 386
      WHEN @Name > 'ge'   THEN 385
      WHEN @Name > 'gav'  THEN 384
      WHEN @Name > 'gat'  THEN 383
      WHEN @Name > 'gass' THEN 382
      WHEN @Name > 'gas'  THEN 381
      WHEN @Name > 'gap'  THEN 380
      WHEN @Name > 'gan'  THEN 379
      WHEN @Name > 'gam'  THEN 378
      WHEN @Name > 'gal'  THEN 377
      WHEN @Name > 'gaf'  THEN 376
      WHEN @Name > 'g'    THEN 375
      WHEN @Name > 'fus'  THEN 374
      WHEN @Name > 'fur'  THEN 373
      WHEN @Name > 'fui'  THEN 372
      WHEN @Name > 'fud'  THEN 371
      WHEN @Name > 'fu'   THEN 370
      WHEN @Name > 'fru'  THEN 369
      WHEN @Name > 'froi' THEN 368
      WHEN @Name > 'fro'  THEN 367
      WHEN @Name > 'frit' THEN 366
      WHEN @Name > 'fris' THEN 365
      WHEN @Name > 'frif' THEN 364
      WHEN @Name > 'frie' THEN 363
      WHEN @Name > 'fri'  THEN 362
      WHEN @Name > 'frey' THEN 361
      WHEN @Name > 'frek' THEN 360
      WHEN @Name > 'frei' THEN 359
      WHEN @Name > 'fre'  THEN 358
      WHEN @Name > 'frap' THEN 357
      WHEN @Name > 'fran' THEN 356
      WHEN @Name > 'fr'   THEN 355
      WHEN @Name > 'fos'  THEN 354
      WHEN @Name > 'forr' THEN 353
      WHEN @Name > 'for'  THEN 352
      WHEN @Name > 'fon'  THEN 351
      WHEN @Name > 'fo'   THEN 350
      WHEN @Name > 'flud' THEN 349
      WHEN @Name > 'flu'  THEN 348
      WHEN @Name > 'fli'  THEN 347
      WHEN @Name > 'fle'  THEN 346
      WHEN @Name > 'fl'   THEN 345
      WHEN @Name > 'fit'  THEN 344
      WHEN @Name > 'fisd' THEN 343
      WHEN @Name > 'fisch' THEN 342
      WHEN @Name > 'fin'  THEN 341
      WHEN @Name > 'fi'   THEN 340
      WHEN @Name > 'fet'  THEN 339
      WHEN @Name > 'fem'  THEN 338
      WHEN @Name > 'feli' THEN 337
      WHEN @Name > 'fel'  THEN 336
      WHEN @Name > 'fe'   THEN 335
      WHEN @Name > 'faw'  THEN 334
      WHEN @Name > 'fav'  THEN 333
      WHEN @Name > 'fat'  THEN 332
      WHEN @Name > 'fass' THEN 331
      WHEN @Name > 'fas'  THEN 330
      WHEN @Name > 'far'  THEN 329
      WHEN @Name > 'fan'  THEN 328
      WHEN @Name > 'fai'  THEN 327
      WHEN @Name > 'fah'  THEN 326
      WHEN @Name > 'f'    THEN 325
      WHEN @Name > 'eu'   THEN 324
      WHEN @Name > 'et'   THEN 323
      WHEN @Name > 'es'   THEN 322
      WHEN @Name > 'ern'  THEN 321
      WHEN @Name > 'er'   THEN 320
      WHEN @Name > 'eo'   THEN 319
      WHEN @Name > 'eni'  THEN 318
      WHEN @Name > 'eng'  THEN 317
      WHEN @Name > 'en'   THEN 316
      WHEN @Name > 'em'   THEN 315
      WHEN @Name > 'ek'   THEN 314
      WHEN @Name > 'ein'  THEN 313
      WHEN @Name > 'eid'  THEN 312
      WHEN @Name > 'eichf' THEN 311
      WHEN @Name > 'ei'   THEN 310
      WHEN @Name > 'ehre' THEN 309
      WHEN @Name > 'eh'   THEN 308
      WHEN @Name > 'egh'  THEN 307
      WHEN @Name > 'eggf' THEN 306
      WHEN @Name > 'egger' THEN 305
      WHEN @Name > 'eggen' THEN 304
      WHEN @Name > 'eg'   THEN 303
      WHEN @Name > 'ec'   THEN 302
      WHEN @Name > 'ebi'  THEN 301
      WHEN @Name > 'e'    THEN 300
      WHEN @Name > 'duv'  THEN 299
      WHEN @Name > 'dus'  THEN 298
      WHEN @Name > 'dur'  THEN 297
      WHEN @Name > 'dup'  THEN 296
      WHEN @Name > 'dum'  THEN 295
      WHEN @Name > 'dud'  THEN 294
      WHEN @Name > 'duc'  THEN 293
      WHEN @Name > 'dub'  THEN 292
      WHEN @Name > 'du'   THEN 291
      WHEN @Name > 'dr'   THEN 290
      WHEN @Name > 'dor'  THEN 289
      WHEN @Name > 'do'   THEN 288
      WHEN @Name > 'dig'  THEN 287
      WHEN @Name > 'die'  THEN 286
      WHEN @Name > 'di'   THEN 285
      WHEN @Name > 'det'  THEN 284
      WHEN @Name > 'des'  THEN 283
      WHEN @Name > 'dep'  THEN 282
      WHEN @Name > 'dem'  THEN 281
      WHEN @Name > 'del'  THEN 280
      WHEN @Name > 'deg'  THEN 279
      WHEN @Name > 'de'   THEN 278
      WHEN @Name > 'das'  THEN 277
      WHEN @Name > 'dam'  THEN 276
      WHEN @Name > 'd'    THEN 275
      WHEN @Name > 'cu'   THEN 274
      WHEN @Name > 'cri'  THEN 273
      WHEN @Name > 'cr'   THEN 272
      WHEN @Name > 'cos'  THEN 271
      WHEN @Name > 'corn' THEN 270
      WHEN @Name > 'cor'  THEN 269
      WHEN @Name > 'com'  THEN 268
      WHEN @Name > 'co'   THEN 267
      WHEN @Name > 'cl'   THEN 266
      WHEN @Name > 'ci'   THEN 265
      WHEN @Name > 'chr'  THEN 264
      WHEN @Name > 'chi'  THEN 263
      WHEN @Name > 'che'  THEN 262
      WHEN @Name > 'char' THEN 261
      WHEN @Name > 'ch'   THEN 260
      WHEN @Name > 'ce'   THEN 259
      WHEN @Name > 'cav'  THEN 258
      WHEN @Name > 'cat'  THEN 257
      WHEN @Name > 'cast' THEN 256
      WHEN @Name > 'cas'  THEN 255
      WHEN @Name > 'car'  THEN 254
      WHEN @Name > 'can'  THEN 253
      WHEN @Name > 'cam'  THEN 252
      WHEN @Name > 'cai'  THEN 251
      WHEN @Name > 'c'    THEN 250
      WHEN @Name > 'by'   THEN 249
      WHEN @Name > 'butt' THEN 248
      WHEN @Name > 'but'  THEN 247
      WHEN @Name > 'buss' THEN 246
      WHEN @Name > 'bus'  THEN 245
      WHEN @Name > 'burs' THEN 244
      WHEN @Name > 'burr' THEN 243
      WHEN @Name > 'burl' THEN 242
      WHEN @Name > 'burki' THEN 241
      WHEN @Name > 'burkh' THEN 240
      WHEN @Name > 'burk' THEN 239
      WHEN @Name > 'burh' THEN 238
      WHEN @Name > 'burgi' THEN 237
      WHEN @Name > 'burg' THEN 236
      WHEN @Name > 'bur'  THEN 235
      WHEN @Name > 'bui'  THEN 234
      WHEN @Name > 'buhm' THEN 233
      WHEN @Name > 'buhlm' THEN 232
      WHEN @Name > 'buh'  THEN 231
      WHEN @Name > 'bud'  THEN 230
      WHEN @Name > 'buci' THEN 229
      WHEN @Name > 'bucho' THEN 228
      WHEN @Name > 'buchi' THEN 227
      WHEN @Name > 'buch' THEN 226
      WHEN @Name > 'bu'   THEN 225
      WHEN @Name > 'bruo' THEN 224
      WHEN @Name > 'bruno' THEN 223
      WHEN @Name > 'brunn' THEN 222
      WHEN @Name > 'brund' THEN 221
      WHEN @Name > 'brun' THEN 220
      WHEN @Name > 'brul' THEN 219
      WHEN @Name > 'bruh' THEN 218
      WHEN @Name > 'brug' THEN 217
      WHEN @Name > 'brud' THEN 216
      WHEN @Name > 'bru'  THEN 215
      WHEN @Name > 'broo' THEN 214
      WHEN @Name > 'bronn' THEN 213
      WHEN @Name > 'bron' THEN 212
      WHEN @Name > 'brof' THEN 211
      WHEN @Name > 'bro'  THEN 210
      WHEN @Name > 'bri'  THEN 209
      WHEN @Name > 'bres' THEN 208
      WHEN @Name > 'brel' THEN 207
      WHEN @Name > 'breg' THEN 206
      WHEN @Name > 'bre'  THEN 205
      WHEN @Name > 'brau' THEN 204
      WHEN @Name > 'brap' THEN 203
      WHEN @Name > 'bran' THEN 202
      WHEN @Name > 'brag' THEN 201
      WHEN @Name > 'br'   THEN 200
      WHEN @Name > 'bov'  THEN 199
      WHEN @Name > 'bot'  THEN 198
      WHEN @Name > 'bossh' THEN 197
      WHEN @Name > 'boss' THEN 196
      WHEN @Name > 'bos'  THEN 195
      WHEN @Name > 'born' THEN 194
      WHEN @Name > 'borg' THEN 193
      WHEN @Name > 'bor'  THEN 192
      WHEN @Name > 'boo'  THEN 191
      WHEN @Name > 'bon'  THEN 190
      WHEN @Name > 'bom'  THEN 189
      WHEN @Name > 'bolm' THEN 188
      WHEN @Name > 'bolli' THEN 187
      WHEN @Name > 'boll' THEN 186
      WHEN @Name > 'bol'  THEN 185
      WHEN @Name > 'boi'  THEN 184
      WHEN @Name > 'boh'  THEN 183
      WHEN @Name > 'bof'  THEN 182
      WHEN @Name > 'bod'  THEN 181
      WHEN @Name > 'bo'   THEN 180
      WHEN @Name > 'blu'  THEN 179
      WHEN @Name > 'ble'  THEN 178
      WHEN @Name > 'blat' THEN 177
      WHEN @Name > 'blas' THEN 176
      WHEN @Name > 'bl'   THEN 175
      WHEN @Name > 'bit'  THEN 174
      WHEN @Name > 'bise' THEN 173
      WHEN @Name > 'bis'  THEN 172
      WHEN @Name > 'bio'  THEN 171
      WHEN @Name > 'bin'  THEN 170
      WHEN @Name > 'bil'  THEN 169
      WHEN @Name > 'bif'  THEN 168
      WHEN @Name > 'bier' THEN 167
      WHEN @Name > 'bie'  THEN 166
      WHEN @Name > 'bi'   THEN 165
      WHEN @Name > 'bf'   THEN 164
      WHEN @Name > 'beu'  THEN 163
      WHEN @Name > 'bes'  THEN 162
      WHEN @Name > 'bert' THEN 161
      WHEN @Name > 'bero' THEN 160
      WHEN @Name > 'berne' THEN 159
      WHEN @Name > 'bern' THEN 158
      WHEN @Name > 'berh' THEN 157
      WHEN @Name > 'berg' THEN 156
      WHEN @Name > 'ber'  THEN 155
      WHEN @Name > 'ben'  THEN 154
      WHEN @Name > 'bel'  THEN 153
      WHEN @Name > 'bef'  THEN 152
      WHEN @Name > 'bed'  THEN 151
      WHEN @Name > 'be'   THEN 150
      WHEN @Name > 'bay'  THEN 149
      WHEN @Name > 'bav'  THEN 148
      WHEN @Name > 'baun' THEN 147
      WHEN @Name > 'baumg' THEN 146
      WHEN @Name > 'baumb' THEN 145
      WHEN @Name > 'baum' THEN 144
      WHEN @Name > 'baue' THEN 143
      WHEN @Name > 'bau'  THEN 142
      WHEN @Name > 'bat'  THEN 141
      WHEN @Name > 'bas'  THEN 140
      WHEN @Name > 'bart' THEN 139
      WHEN @Name > 'barm' THEN 138
      WHEN @Name > 'barc' THEN 137
      WHEN @Name > 'bar'  THEN 136
      WHEN @Name > 'ban'  THEN 135
      WHEN @Name > 'bam'  THEN 134
      WHEN @Name > 'bals' THEN 133
      WHEN @Name > 'balm' THEN 132
      WHEN @Name > 'ball' THEN 131
      WHEN @Name > 'bal'  THEN 130
      WHEN @Name > 'bag'  THEN 129
      WHEN @Name > 'bad'  THEN 128
      WHEN @Name > 'bachm' THEN 127
      WHEN @Name > 'bach' THEN 126
      WHEN @Name > 'b'    THEN 125
      WHEN @Name > 'au'   THEN 124
      WHEN @Name > 'as'   THEN 123
      WHEN @Name > 'aro'  THEN 122
      WHEN @Name > 'arno' THEN 121
      WHEN @Name > 'ar'   THEN 120
      WHEN @Name > 'ao'   THEN 119
      WHEN @Name > 'ann'  THEN 118
      WHEN @Name > 'ane'  THEN 117
      WHEN @Name > 'ando' THEN 116
      WHEN @Name > 'an'   THEN 115
      WHEN @Name > 'ams'  THEN 114
      WHEN @Name > 'amo'  THEN 113
      WHEN @Name > 'amm'  THEN 112
      WHEN @Name > 'amd'  THEN 111
      WHEN @Name > 'am'   THEN 110
      WHEN @Name > 'alm'  THEN 109
      WHEN @Name > 'all'  THEN 108
      WHEN @Name > 'ald'  THEN 107
      WHEN @Name > 'al'   THEN 106
      WHEN @Name > 'ag'   THEN 105
      WHEN @Name > 'af'   THEN 104
      WHEN @Name > 'ac'   THEN 103
      WHEN @Name > 'abl'  THEN 102
      WHEN @Name > 'abi'  THEN 101
      WHEN @Name > 'a'    THEN 100
    END)
     + '.' + CASE WHEN @Geburtsdatum IS NULL THEN '__.___'
             ELSE
               SubString(CONVERT(varchar, Year(@Geburtsdatum)), 3, 2) + '.'
                + CONVERT(varchar,
                    CASE WHEN @GeschlechtCode = 1 THEN 0 ELSE 400 END
                     + DatePart(q, @Geburtsdatum) * 100
                     + DAY(@Geburtsdatum)
                     + ((MONTH(@Geburtsdatum) - 1) % 3) * 31
                  )
             END
     + '.___'

  RETURN @AHV
END

GO