#region Header

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#endregion

using System.Data;
using System.Windows.Forms;
using KiSS4.Common.ZH;
using KiSS4.DB;
using KiSS4.Gui;

namespace KiSS4.Query.ZH
{
    public class CtlQueryKbZahllaufFehlermeldungen : KiSS4.Common.KissQueryControl
    {
        #region Fields

        private KiSS4.Gui.KissButton btnJump;
        private DevExpress.XtraGrid.Columns.GridColumn colAuszahlungsart;
        private DevExpress.XtraGrid.Columns.GridColumn colBetrag;
        private DevExpress.XtraGrid.Columns.GridColumn colFehler;
        private DevExpress.XtraGrid.Columns.GridColumn colKD;
        private DevExpress.XtraGrid.Columns.GridColumn colKlient;
        private DevExpress.XtraGrid.Columns.GridColumn colKreditor;
        private DevExpress.XtraGrid.Columns.GridColumn colModul;
        private DevExpress.XtraGrid.Columns.GridColumn colSozialzentrum;
        private DevExpress.XtraGrid.Columns.GridColumn colTeam;
        private DevExpress.XtraGrid.Columns.GridColumn colUser;
        private DevExpress.XtraGrid.Columns.GridColumn colValuta;
        private DevExpress.XtraGrid.Columns.GridColumn colZahlinfo;
        private KiSS4.Common.ZH.CtlOrgUnitTeamUser ctlOrgUnitTeamUser;
        private KiSS4.Gui.KissMemoEdit edtMsg;
        private KiSS4.Gui.KissLookUpEdit edtSucheFaProzessCodes;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView1;
        private KiSS4.Gui.KissLabel lblModul;

        #endregion

        #region Constructors

        public CtlQueryKbZahllaufFehlermeldungen()
        {
            this.InitializeComponent();
        }

        #endregion

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CtlQueryKbZahllaufFehlermeldungen));
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject1 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject2 = new DevExpress.Utils.SerializableAppearanceObject();
            this.btnJump = new KiSS4.Gui.KissButton();
            this.edtMsg = new KiSS4.Gui.KissMemoEdit();
            this.lblModul = new KiSS4.Gui.KissLabel();
            this.edtSucheFaProzessCodes = new KiSS4.Gui.KissLookUpEdit();
            this.ctlOrgUnitTeamUser = new KiSS4.Common.ZH.CtlOrgUnitTeamUser();
            this.colAuszahlungsart = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colBetrag = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colFehler = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colKD = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colKlient = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colKreditor = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colModul = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colSozialzentrum = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colTeam = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colUser = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colValuta = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colZahlinfo = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridView1 = new DevExpress.XtraGrid.Views.Grid.GridView();
            ((System.ComponentModel.ISupportInitialize)(this.qryQuery)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdQuery1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.xDocument.Properties)).BeginInit();
            this.tabControlSearch.SuspendLayout();
            this.tpgListe.SuspendLayout();
            this.tpgSuchen.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.edtMsg.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblModul)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSucheFaProzessCodes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSucheFaProzessCodes.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).BeginInit();
            this.SuspendLayout();
            //
            // qryQuery
            //
            this.qryQuery.SelectStatement = resources.GetString("qryQuery.SelectStatement");
            //
            // grdQuery1
            //
            this.grdQuery1.EmbeddedNavigator.Name = "";
            this.grdQuery1.MainView = this.gridView1;
            this.grdQuery1.Size = new System.Drawing.Size(766, 320);
            this.grdQuery1.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
                        this.gridView1});
            //
            // xDocument
            //
            this.xDocument.DataMember = null;
            this.xDocument.EditValue = null;
            this.xDocument.Location = new System.Drawing.Point(3, 357);
            this.xDocument.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.xDocument.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.xDocument.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.xDocument.Properties.Appearance.Options.UseBackColor = true;
            this.xDocument.Properties.Appearance.Options.UseBorderColor = true;
            this.xDocument.Properties.Appearance.Options.UseFont = true;
            serializableAppearanceObject1.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject1.Options.UseBackColor = true;
            this.xDocument.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
                        new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Glyph, "", -1, true, false, false, DevExpress.Utils.HorzAlignment.Center, ((System.Drawing.Image)(resources.GetObject("xDocument.Properties.Buttons"))), new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject1, "Dokument öffnen")});
            this.xDocument.Visible = false;
            //
            // ctlGotoFall
            //
            this.ctlGotoFall.DataMember = "BaPersonID$";
            this.ctlGotoFall.Location = new System.Drawing.Point(3, 327);
            this.ctlGotoFall.Size = new System.Drawing.Size(110, 24);
            //
            // tpgListe
            //
            this.tpgListe.Controls.Add(this.edtMsg);
            this.tpgListe.Controls.Add(this.btnJump);
            this.tpgListe.Location = new System.Drawing.Point(6, 6);
            this.tpgListe.Controls.SetChildIndex(this.grdQuery1, 0);
            this.tpgListe.Controls.SetChildIndex(this.ctlGotoFall, 0);
            this.tpgListe.Controls.SetChildIndex(this.xDocument, 0);
            this.tpgListe.Controls.SetChildIndex(this.btnJump, 0);
            this.tpgListe.Controls.SetChildIndex(this.edtMsg, 0);
            //
            // tpgSuchen
            //
            this.tpgSuchen.Controls.Add(this.ctlOrgUnitTeamUser);
            this.tpgSuchen.Controls.Add(this.edtSucheFaProzessCodes);
            this.tpgSuchen.Controls.Add(this.lblModul);
            this.tpgSuchen.Location = new System.Drawing.Point(6, 6);
            this.tpgSuchen.Controls.SetChildIndex(this.searchTitle, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.lblModul, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtSucheFaProzessCodes, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.ctlOrgUnitTeamUser, 0);
            //
            // btnJump
            //
            this.btnJump.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnJump.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnJump.Location = new System.Drawing.Point(3, 360);
            this.btnJump.Name = "btnJump";
            this.btnJump.Size = new System.Drawing.Size(106, 24);
            this.btnJump.TabIndex = 3;
            this.btnJump.Text = "Zum Fall";
            this.btnJump.UseCompatibleTextRendering = true;
            this.btnJump.UseVisualStyleBackColor = false;
            this.btnJump.Click += new System.EventHandler(this.btnJump_Click);
            //
            // edtMsg
            //
            this.edtMsg.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.edtMsg.DataMember = "Fehler";
            this.edtMsg.DataSource = this.qryQuery;
            this.edtMsg.Location = new System.Drawing.Point(119, 327);
            this.edtMsg.Name = "edtMsg";
            this.edtMsg.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtMsg.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtMsg.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtMsg.Properties.Appearance.Options.UseBackColor = true;
            this.edtMsg.Properties.Appearance.Options.UseBorderColor = true;
            this.edtMsg.Properties.Appearance.Options.UseFont = true;
            this.edtMsg.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtMsg.Size = new System.Drawing.Size(650, 94);
            this.edtMsg.TabIndex = 5;
            //
            // lblModul
            //
            this.lblModul.Location = new System.Drawing.Point(10, 45);
            this.lblModul.Name = "lblModul";
            this.lblModul.Size = new System.Drawing.Size(43, 24);
            this.lblModul.TabIndex = 7;
            this.lblModul.Text = "Modul";
            this.lblModul.UseCompatibleTextRendering = true;
            //
            // edtSucheFaProzessCodes
            //
            this.edtSucheFaProzessCodes.Location = new System.Drawing.Point(123, 45);
            this.edtSucheFaProzessCodes.Name = "edtSucheFaProzessCodes";
            this.edtSucheFaProzessCodes.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtSucheFaProzessCodes.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtSucheFaProzessCodes.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtSucheFaProzessCodes.Properties.Appearance.Options.UseBackColor = true;
            this.edtSucheFaProzessCodes.Properties.Appearance.Options.UseBorderColor = true;
            this.edtSucheFaProzessCodes.Properties.Appearance.Options.UseFont = true;
            this.edtSucheFaProzessCodes.Properties.AppearanceDropDown.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.edtSucheFaProzessCodes.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.edtSucheFaProzessCodes.Properties.AppearanceDropDown.Options.UseBackColor = true;
            this.edtSucheFaProzessCodes.Properties.AppearanceDropDown.Options.UseFont = true;
            this.edtSucheFaProzessCodes.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject2.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject2.Options.UseBackColor = true;
            this.edtSucheFaProzessCodes.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
                        new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo, "", -1, true, true, false, DevExpress.Utils.HorzAlignment.Center, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject2)});
            this.edtSucheFaProzessCodes.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtSucheFaProzessCodes.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
                        new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Text")});
            this.edtSucheFaProzessCodes.Properties.DisplayMember = "Text";
            this.edtSucheFaProzessCodes.Properties.NullText = "";
            this.edtSucheFaProzessCodes.Properties.ShowFooter = false;
            this.edtSucheFaProzessCodes.Properties.ShowHeader = false;
            this.edtSucheFaProzessCodes.Properties.ValueMember = "Code";
            this.edtSucheFaProzessCodes.Size = new System.Drawing.Size(260, 24);
            this.edtSucheFaProzessCodes.TabIndex = 333;
            //
            // ctlOrgUnitTeamUser
            //
            this.ctlOrgUnitTeamUser.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.ctlOrgUnitTeamUser.LableWidth = 113;
            this.ctlOrgUnitTeamUser.Location = new System.Drawing.Point(10, 75);
            this.ctlOrgUnitTeamUser.Name = "ctlOrgUnitTeamUser";
            this.ctlOrgUnitTeamUser.ShowUser = true;
            this.ctlOrgUnitTeamUser.Size = new System.Drawing.Size(373, 84);
            this.ctlOrgUnitTeamUser.TabIndex = 334;
            //
            // colAuszahlungsart
            //
            this.colAuszahlungsart.Name = "colAuszahlungsart";
            //
            // colBetrag
            //
            this.colBetrag.Name = "colBetrag";
            //
            // colFehler
            //
            this.colFehler.Name = "colFehler";
            //
            // colKD
            //
            this.colKD.Name = "colKD";
            //
            // colKlient
            //
            this.colKlient.Name = "colKlient";
            //
            // colKreditor
            //
            this.colKreditor.Name = "colKreditor";
            //
            // colModul
            //
            this.colModul.Name = "colModul";
            //
            // colSozialzentrum
            //
            this.colSozialzentrum.Name = "colSozialzentrum";
            //
            // colTeam
            //
            this.colTeam.Name = "colTeam";
            //
            // colUser
            //
            this.colUser.Name = "colUser";
            //
            // colValuta
            //
            this.colValuta.Name = "colValuta";
            //
            // colZahlinfo
            //
            this.colZahlinfo.Name = "colZahlinfo";
            //
            // gridView1
            //
            this.gridView1.Appearance.Empty.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.gridView1.Appearance.Empty.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView1.Appearance.Empty.Options.UseBackColor = true;
            this.gridView1.Appearance.Empty.Options.UseFont = true;
            this.gridView1.Appearance.EvenRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView1.Appearance.EvenRow.Options.UseFont = true;
            this.gridView1.Appearance.FocusedCell.BackColor = System.Drawing.SystemColors.Highlight;
            this.gridView1.Appearance.FocusedCell.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView1.Appearance.FocusedCell.ForeColor = System.Drawing.Color.White;
            this.gridView1.Appearance.FocusedCell.Options.UseBackColor = true;
            this.gridView1.Appearance.FocusedCell.Options.UseFont = true;
            this.gridView1.Appearance.FocusedCell.Options.UseForeColor = true;
            this.gridView1.Appearance.FocusedRow.BackColor = System.Drawing.SystemColors.Highlight;
            this.gridView1.Appearance.FocusedRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView1.Appearance.FocusedRow.ForeColor = System.Drawing.Color.White;
            this.gridView1.Appearance.FocusedRow.Options.UseBackColor = true;
            this.gridView1.Appearance.FocusedRow.Options.UseFont = true;
            this.gridView1.Appearance.FocusedRow.Options.UseForeColor = true;
            this.gridView1.Appearance.GroupPanel.BackColor = System.Drawing.Color.PeachPuff;
            this.gridView1.Appearance.GroupPanel.Options.UseBackColor = true;
            this.gridView1.Appearance.GroupRow.BackColor = System.Drawing.Color.PeachPuff;
            this.gridView1.Appearance.GroupRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.gridView1.Appearance.GroupRow.ForeColor = System.Drawing.SystemColors.WindowText;
            this.gridView1.Appearance.GroupRow.Options.UseBackColor = true;
            this.gridView1.Appearance.GroupRow.Options.UseFont = true;
            this.gridView1.Appearance.GroupRow.Options.UseForeColor = true;
            this.gridView1.Appearance.HeaderPanel.BackColor = System.Drawing.Color.Tan;
            this.gridView1.Appearance.HeaderPanel.BorderColor = System.Drawing.Color.Tan;
            this.gridView1.Appearance.HeaderPanel.Font = new System.Drawing.Font("Arial", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.gridView1.Appearance.HeaderPanel.Options.UseBackColor = true;
            this.gridView1.Appearance.HeaderPanel.Options.UseBorderColor = true;
            this.gridView1.Appearance.HeaderPanel.Options.UseFont = true;
            this.gridView1.Appearance.HideSelectionRow.BackColor = System.Drawing.Color.PowderBlue;
            this.gridView1.Appearance.HideSelectionRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView1.Appearance.HideSelectionRow.ForeColor = System.Drawing.SystemColors.WindowText;
            this.gridView1.Appearance.HideSelectionRow.Options.UseBackColor = true;
            this.gridView1.Appearance.HideSelectionRow.Options.UseFont = true;
            this.gridView1.Appearance.HideSelectionRow.Options.UseForeColor = true;
            this.gridView1.Appearance.HorzLine.BackColor = System.Drawing.Color.Silver;
            this.gridView1.Appearance.HorzLine.Options.UseBackColor = true;
            this.gridView1.Appearance.OddRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView1.Appearance.OddRow.Options.UseFont = true;
            this.gridView1.Appearance.Row.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.gridView1.Appearance.Row.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView1.Appearance.Row.Options.UseBackColor = true;
            this.gridView1.Appearance.Row.Options.UseFont = true;
            this.gridView1.Appearance.SelectedRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.gridView1.Appearance.SelectedRow.Options.UseFont = true;
            this.gridView1.Appearance.VertLine.BackColor = System.Drawing.Color.Silver;
            this.gridView1.Appearance.VertLine.Options.UseBackColor = true;
            this.gridView1.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.gridView1.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.None;
            this.gridView1.GridControl = this.grdQuery1;
            this.gridView1.Name = "gridView1";
            this.gridView1.OptionsBehavior.Editable = false;
            this.gridView1.OptionsFilter.UseNewCustomFilterDialog = true;
            this.gridView1.OptionsNavigation.AutoFocusNewRow = true;
            this.gridView1.OptionsNavigation.UseTabKey = false;
            this.gridView1.OptionsView.ColumnAutoWidth = false;
            this.gridView1.OptionsView.ShowFilterPanelMode = DevExpress.XtraGrid.Views.Base.ShowFilterPanelMode.Never;
            this.gridView1.OptionsView.ShowGroupPanel = false;
            this.gridView1.OptionsView.ShowIndicator = false;
            //
            // CtlQueryKbZahllaufFehlermeldungen
            //
            this.Name = "CtlQueryKbZahllaufFehlermeldungen";
            this.Load += new System.EventHandler(this.CtlQueryKbZahllaufFehlermeldungen_Load);
            ((System.ComponentModel.ISupportInitialize)(this.qryQuery)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdQuery1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.xDocument.Properties)).EndInit();
            this.tabControlSearch.ResumeLayout(false);
            this.tpgListe.ResumeLayout(false);
            this.tpgSuchen.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.edtMsg.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblModul)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSucheFaProzessCodes.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSucheFaProzessCodes)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        #region Public Methods

        public override void OnSearch()
        {
            if (tabControlSearch.SelectedTab == tpgSuchen)
            {
                foreach (Control ctl in UtilsGui.AllControls(tpgSuchen))
                {
                    if (ctl is KissButtonEdit)
                    {
                        KissButtonEdit edt = (KissButtonEdit)ctl;
                        edt.CheckPendingSearchValue();
                    }

                    if (ctl is CtlOrgUnitTeamUser)
                    {
                        ((CtlOrgUnitTeamUser)ctl).CheckPendingSearchValue();
                    }
                }
            }

            // Workaround um F3 weiter zu reichen, da das FrameWork das OrgUnitTeamUser UserControl nicht kennt
            try
            {
                if (((ContainerControl)ActiveControl).ActiveControl.Equals(ctlOrgUnitTeamUser))
                    edtSucheFaProzessCodes.Focus();
            }
            catch
            {
            }

            base.OnSearch();
        }

        #endregion

        #region Protected Methods

        protected override void NewSearch()
        {
            base.NewSearch();
            ctlOrgUnitTeamUser.NewSearch();

            edtSucheFaProzessCodes.Focus();
        }

        #endregion

        #region Private Methods

        private void CtlQueryKbZahllaufFehlermeldungen_Load(object sender, System.EventArgs e)
        {
            edtSucheFaProzessCodes.Properties.DataSource = DBUtil.OpenSQL("SELECT Code = NULL, Text = ''\nUNION ALL\nSELECT Code = '300', Text = 'W - Wirtschaftliche Hilfe'\nUNION ALL\nSELECT Code = '301,302,304', Text = 'WIK - W-Inkasso'\nUNION ALL\nSELECT Code = '402,404,405,406,407,408,409,410', Text = 'A - Alimentwesen'");
        }

        private string GetJumpToPath(DataRow row)
        {
            string jumpToPath;
            if( (int)row["ModulID$"] == 3 ) // W
            {
                jumpToPath = string.Format(
                    "ClassName=FrmFall;" +
                    "BaPersonID={0};" +
                    "ModulID=3;" +
                    "TreeNodeID=CtlWhFinanzplan{1}\\BBG{2};",
                    //"ActiveSQLQuery.Find=BgPositionID = {3};",
                      row["BaPersonID$"],
                      row["BgFinanzplanID$"],
                      row["BgBudgetID$"],
                      row["BgPositionID$"]);
            }
            else // A
            {
                jumpToPath = string.Format(
                    "ClassName=FrmFall;" +
                    "BaPersonID={0};" +
                    "ModulID=4;",
                      row["BaPersonID$"]);
            }

            return jumpToPath;
        }

        private void btnJump_Click(object sender, System.EventArgs e)
        {
            if (qryQuery.Row == null) return;

            System.Collections.Specialized.HybridDictionary dic = FormController.ConvertToDictionary(GetJumpToPath(qryQuery.Row));
            bool result = FormController.OpenForm((string)dic["ClassName"], "Action", "JumpToPath", dic);
        }

        #endregion
    }
}