CREATE TABLE [dbo].[BFSDossierPerson](
	[BFSDossierPersonID] [int] IDENTITY(1,1) NOT NULL,
	[BFSDossierID] [int] NOT NULL,
	[BFSPersonCode] [int] NOT NULL,
	[PersonIndex] [int] NOT NULL,
	[PersonName] [varchar](100) NULL,
	[BaPersonID] [int] NULL,
	[BFSDossierPersonTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_BFSDossierPerson] PRIMARY KEY CLUSTERED 
(
	[BFSDossierPersonID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IX_BFSDossierPerson_1] ON [dbo].[BFSDossierPerson] 
(
	[BFSDossierPersonID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_BFSDossierPerson_BFSDossierIDBFSPersonCOdePersonIndex_Unique] ON [dbo].[BFSDossierPerson] 
(
	[BFSDossierID] ASC,
	[BFSPersonCode] ASC,
	[PersonIndex] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BFSDossierPerson]  WITH CHECK ADD  CONSTRAINT [FK_BFSDossierPerson_BFSDossier] FOREIGN KEY([BFSDossierID])
REFERENCES [dbo].[BFSDossier] ([BFSDossierID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[BFSDossierPerson] CHECK CONSTRAINT [FK_BFSDossierPerson_BFSDossier]