CREATE TABLE [dbo].[BFSFarbCode](
	[BFSFarbCodeID] [int] IDENTITY(1,1) NOT NULL,
	[Leistungsfilter] [int] NOT NULL,
	[ExcelFarbCode] [int] NOT NULL,
	[BFSFrageID] [int] NOT NULL,
 CONSTRAINT [PK_BFSFarbCode] PRIMARY KEY CLUSTERED 
(
	[BFSFarbCodeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[BFSFarbCode]  WITH CHECK ADD  CONSTRAINT [FK_BFSFarbCode_BFSFrage] FOREIGN KEY([BFSFrageID])
REFERENCES [dbo].[BFSFrage] ([BFSFrageID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[BFSFarbCode] CHECK CONSTRAINT [FK_BFSFarbCode_BFSFrage]