CREATE TABLE [dbo].[BFSKatalogVersion](
	[BFSKatalogVersionID] [int] NOT NULL,
	[Jahr] [int] NULL,
	[PlausexVersion] [varchar](50) NULL,
	[DossierXML] [text] NULL,
 CONSTRAINT [PK_BFSKatalogVersion] PRIMARY KEY CLUSTERED 
(
	[BFSKatalogVersionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING ON