CREATE TABLE [dbo].[BFSLOV](
	[LOVName] [varchar](100) NOT NULL,
	[BFSLOVTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_BFSLOV] PRIMARY KEY CLUSTERED 
(
	[LOVName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON