CREATE TABLE [dbo].[BDEPensum_XUser](
	[BDEPensum_XUserID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[DatumVon] [datetime] NOT NULL,
	[DatumBis] [datetime] NULL,
	[PensumProzent] [int] NOT NULL,
	[ManualEdit] [bit] NOT NULL,
	[BDEPensum_XUserTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_BDEPensum_XUser] PRIMARY KEY CLUSTERED 
(
	[BDEPensum_XUserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_BDEPensum_XUser] UNIQUE NONCLUSTERED 
(
	[UserID] ASC,
	[DatumVon] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE NONCLUSTERED INDEX [IX_BDEPensum_XUser_UserIDDatumVonBisPensumProzent] ON [dbo].[BDEPensum_XUser] 
(
	[UserID] ASC,
	[DatumVon] ASC,
	[DatumBis] ASC,
	[PensumProzent] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BDEPensum_XUser]  WITH CHECK ADD  CONSTRAINT [FK_BDEPensum_XUser_XUser] FOREIGN KEY([UserID])
REFERENCES [dbo].[XUser] ([UserID])
GO

ALTER TABLE [dbo].[BDEPensum_XUser] CHECK CONSTRAINT [FK_BDEPensum_XUser_XUser]
GO

ALTER TABLE [dbo].[BDEPensum_XUser] ADD  CONSTRAINT [DF_BDEPensum_XUser_ManualEdit]  DEFAULT ((0)) FOR [ManualEdit]
GO