//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace Kiss4Web.Infrastructure.CircuitBreakers {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aventis.Server.Infrastructure.CircuitBreakers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Zugriff auf die Ressource &apos;{0}&apos; schlägt fehl: {1}.
        /// </summary>
        internal static string CircuitBreakerExceptionUserText {
            get {
                return ResourceManager.GetString("CircuitBreakerExceptionUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Systemsicherungen.
        /// </summary>
        internal static string CircuitBreakerMonitorRight {
            get {
                return ResourceManager.GetString("CircuitBreakerMonitorRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt aufgetretener Fehler.
        /// </summary>
        internal static string CircuitBreakerStateDTO_LastException {
            get {
                return ResourceManager.GetString("CircuitBreakerStateDTO_LastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auslösungszeitpunkt.
        /// </summary>
        internal static string CircuitBreakerStateDTO_LastOpen {
            get {
                return ResourceManager.GetString("CircuitBreakerStateDTO_LastOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherung.
        /// </summary>
        internal static string CircuitBreakerStateDTO_Name {
            get {
                return ResourceManager.GetString("CircuitBreakerStateDTO_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string CircuitBreakerStateDTO_State {
            get {
                return ResourceManager.GetString("CircuitBreakerStateDTO_State", resourceCulture);
            }
        }
    }
}
