/*
SELECT  TestSql = 'SELECT TOP 10 * FROM dbo.' + name + ' WITH (READUNCOMMITTED)'
FROM sysobjects WHERE xtype = 'V'
ORDER BY 1
*/

SELECT TOP 10 * FROM dbo.AyKostenart WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.AyPositionsart WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.FaFall WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.FaFallPerson WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.viewDauerauftrag WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.viewDTAFbBuchungen WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.viewFbBuchungCode WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.viewFbBuchungen WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwBaZahlungsweg WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwBFSDossier WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwBgPosition WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwInstitution WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwKreditor WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwPerson WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwTmAbklPhasen WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwTmAllgemein WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwTmErblasser WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwTmErblasserBesch WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwTmPerson WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwTmUser WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwTmVermittlungEinsatz WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwTmVermittlungProfil WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.vwUser WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.WhKostenart WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.WhPositionsart WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.XDocument WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.XViewForeignKeys WITH (READUNCOMMITTED)
SELECT TOP 10 * FROM dbo.XViewIndex WITH (READUNCOMMITTED)