CREATE TABLE [dbo].[MigMappingPerson](
	[Person] [int] NOT NULL,
	[BaPersonID] [int] NOT NULL,
	[MatchType] [int] NOT NULL,
 CONSTRAINT [PK_MigMappingPerson] PRIMARY KEY CLUSTERED 
(
	[Person] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [ARCHIV]
) ON [ARCHIV]
