CREATE TABLE [dbo].[MigMappingSonarLeistung](
	[FallId] [int] NOT NULL,
	[Leistung] [int] NULL,
 CONSTRAINT [PK_MigMappingSonarLeistung] PRIMARY KEY CLUSTERED 
(
	[FallId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [ARCHIV]
) ON [ARCHIV]
