using System;
using System.Collections.Generic;

namespace Kiss4Web.Model
{
    public partial class HistBaPerson
    {
        public int BaPersonId { get; set; }
        public int? StatusPersonCode { get; set; }
        public string Titel { get; set; }
        public string Name { get; set; }
        public string FruehererName { get; set; }
        public string Vorname { get; set; }
        public string Vorname2 { get; set; }
        public DateTime? Geburtsdatum { get; set; }
        public DateTime? Sterbedatum { get; set; }
        public string Ahvnummer { get; set; }
        public string Versichertennummer { get; set; }
        public string HaushaltVersicherungsNummer { get; set; }
        public string Nnummer { get; set; }
        public string Bffnummer { get; set; }
        public string Zarnummer { get; set; }
        public int? Zipnr { get; set; }
        public string KantonaleReferenznummer { get; set; }
        public int? GeschlechtCode { get; set; }
        public int? ZivilstandCode { get; set; }
        public DateTime? ZivilstandDatum { get; set; }
        public int? HeimatgemeindeCode { get; set; }
        public string HeimatgemeindeCodes { get; set; }
        public int? NationalitaetCode { get; set; }
        public int? ReligionCode { get; set; }
        public int? AuslaenderStatusCode { get; set; }
        public DateTime? AuslaenderStatusGueltigBis { get; set; }
        public string TelefonP { get; set; }
        public string TelefonG { get; set; }
        public string MobilTel1 { get; set; }
        public string MobilTel2 { get; set; }
        public string Email { get; set; }
        public int? SprachCode { get; set; }
        public bool? Unterstuetzt { get; set; }
        public bool Fiktiv { get; set; }
        public string Bemerkung { get; set; }
        public bool? EinwohnerregisterAktiv { get; set; }
        public string EinwohnerregisterId { get; set; }
        public int? DeutschVerstehenCode { get; set; }
        public int? WichtigerHinweisCode { get; set; }
        public string ZuzugKtPlz { get; set; }
        public int? ZuzugKtOrtCode { get; set; }
        public string ZuzugKtOrt { get; set; }
        public string ZuzugKtKanton { get; set; }
        public int? ZuzugKtLandCode { get; set; }
        public DateTime? ZuzugKtDatum { get; set; }
        public bool? ZuzugKtSeitGeburt { get; set; }
        public string ZuzugGdePlz { get; set; }
        public int? ZuzugGdeOrtCode { get; set; }
        public string ZuzugGdeOrt { get; set; }
        public string ZuzugGdeKanton { get; set; }
        public int? ZuzugGdeLandCode { get; set; }
        public DateTime? ZuzugGdeDatum { get; set; }
        public bool? ZuzugGdeSeitGeburt { get; set; }
        public string UntWohnsitzPlz { get; set; }
        public string UntWohnsitzOrt { get; set; }
        public string UntWohnsitzKanton { get; set; }
        public int? UntWohnsitzLandCode { get; set; }
        public string WegzugPlz { get; set; }
        public int? WegzugOrtCode { get; set; }
        public string WegzugOrt { get; set; }
        public string WegzugKanton { get; set; }
        public int? WegzugLandCode { get; set; }
        public DateTime? WegzugDatum { get; set; }
        public int? WohnsitzWieBaPersonId { get; set; }
        public int? AufenthaltWieBaInstitutionId { get; set; }
        public int? ErwerbssituationCode { get; set; }
        public int? GrundTeilzeitarbeit1Code { get; set; }
        public int? GrundTeilzeitarbeit2Code { get; set; }
        public int? BaGrundNichtErwerbstaetigCode { get; set; }
        public int? ErwerbsBrancheCode { get; set; }
        public int? ErlernterBerufCode { get; set; }
        public int? BerufCode { get; set; }
        public int? HoechsteAusbildungCode { get; set; }
        public int? AbgebrocheneAusbildungCode { get; set; }
        public string ArbeitSpezFaehigkeiten { get; set; }
        public int? KbKostenstelleId { get; set; }
        public DateTime? InChseit { get; set; }
        public bool InChseitGeburt { get; set; }
        public int? PuanzahlVerlustscheine { get; set; }
        public string Pukrankenkasse { get; set; }
        public DateTime? PraemienuebernahmeVon { get; set; }
        public DateTime? PraemienuebernahmeBis { get; set; }
        public bool PersonOhneLeistung { get; set; }
        public bool Hcmcfluechtling { get; set; }
        public int? StellensuchendCode { get; set; }
        public int? ResoNr { get; set; }
        public DateTime? Neanmeldung { get; set; }
        public int? HeimatgemeindeBaGemeindeId { get; set; }
        public bool? AktiveKopfQuote { get; set; }
        public bool Alk { get; set; }
        public string AndereSvleistungen { get; set; }
        public string Anrede { get; set; }
        public int? AusbildungCode { get; set; }
        public int? Behinderungsart2Code { get; set; }
        public string BemerkungenAdresse { get; set; }
        public string BemerkungenSv { get; set; }
        public bool BeruflicheMassnahmeIv { get; set; }
        public string Briefanrede { get; set; }
        public int? BsvbehinderungsartCode { get; set; }
        public bool Bvgrente { get; set; }
        public DateTime? CausweisDatum { get; set; }
        public int? KlientenkontoNr { get; set; }
        public int? DebitorNr { get; set; }
        public DateTime? DebitorUpdate { get; set; }
        public bool EigenerMietvertrag { get; set; }
        public decimal? Einrichtpauschale { get; set; }
        public int? EinrichtungspauschaleCode { get; set; }
        public bool ErgaenzungsLeistungen { get; set; }
        public bool Assistenzbeitrag { get; set; }
        public DateTime? DatumAssistenzbeitrag { get; set; }
        public int? IvVerfuegteAssistenzberatung { get; set; }
        public DateTime? DatumIvVerfuegung { get; set; }
        public DateTime? ErteilungVa { get; set; }
        public bool IstFamiliennachzug { get; set; }
        public string Fax { get; set; }
        public int? HauptBehinderungsartCode { get; set; }
        public bool HelbkeinAntrag { get; set; }
        public DateTime? Helbab { get; set; }
        public DateTime? Helbanmeldung { get; set; }
        public DateTime? Helbentscheid { get; set; }
        public int? HelbentscheidCode { get; set; }
        public int? HilfslosenEntschaedigungCode { get; set; }
        public DateTime? ImKantonSeit { get; set; }
        public bool ImKantonSeitGeburt { get; set; }
        public DateTime? InGemeindeSeit { get; set; }
        public int? IntensivPflegeZuschlagCode { get; set; }
        public int? IvberechtigungAnfangsStatusCode { get; set; }
        public DateTime? IvberechtigungErsterEntscheidAb { get; set; }
        public int? IvberechtigungErsterEntscheidCode { get; set; }
        public DateTime? IvberechtigungZweiterEntscheidAb { get; set; }
        public int? IvberechtigungZweiterEntscheidCode { get; set; }
        public int? Ivgrad { get; set; }
        public bool Ivhilfsmittel { get; set; }
        public bool Ivtaggeld { get; set; }
        public bool KeinSerienbrief { get; set; }
        public int? KonfessionCode { get; set; }
        public bool KontoFuehrung { get; set; }
        public int? BaPersonIdDossiertraeger { get; set; }
        public int? KopfquoteBaInstitutionId { get; set; }
        public DateTime? KopfquoteAbDatum { get; set; }
        public DateTime? KopfquoteBisDatum { get; set; }
        public int? KorrespondenzSpracheCode { get; set; }
        public bool Ktg { get; set; }
        public bool LaufendeVollmachtErlaubnis { get; set; }
        public bool ManuelleAnrede { get; set; }
        public bool MedizinischeMassnahmeIv { get; set; }
        public bool Mehrfachbehinderung { get; set; }
        public bool MietdepotPi { get; set; }
        public int? MigrationKa { get; set; }
        public string MobilTel { get; set; }
        public string NavigatorZusatz { get; set; }
        public bool? PassiveKopfQuote { get; set; }
        public DateTime? PauschaleAktualDatum { get; set; }
        public bool PersonSichtbarSdflag { get; set; }
        public int? ProjNr { get; set; }
        public int? RentenstufeCode { get; set; }
        public bool SichtbarSdflag { get; set; }
        public bool Sozialhilfe { get; set; }
        public decimal? Sprachpauschale { get; set; }
        public bool Testperson { get; set; }
        public int? UntWohnsitzOrtCode { get; set; }
        public bool Uvgrente { get; set; }
        public bool Uvgtaggeld { get; set; }
        public int? VerstaendigungSprachCode { get; set; }
        public string Visdat36Area { get; set; }
        public string Visdat36Id { get; set; }
        public int? VormundMassnahmenCode { get; set; }
        public bool VormundPi { get; set; }
        public string WichtigerHinweis { get; set; }
        public bool WittwenWittwerWaisenrente { get; set; }
        public int? WohnstatusCode { get; set; }
        public bool ZeigeDetails { get; set; }
        public bool ZeigeTelGeschaeft { get; set; }
        public bool ZeigeTelMobil { get; set; }
        public bool ZeigeTelPrivat { get; set; }
        public string Zemisnummer { get; set; }
        public bool IstBerechnungsperson { get; set; }
        public DateTime? DatumAsylgesuch { get; set; }
        public DateTime? DatumEinbezugFaz { get; set; }
        public int VerId { get; set; }
        public string Creator { get; set; }
        public DateTime Created { get; set; }
        public string Modifier { get; set; }
        public DateTime Modified { get; set; }
        public int? VerIdDeleted { get; set; }
    }
}
