USE master
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'KiSS_ZH_VIS_Test')
  DROP DATABASE [KiSS_ZH_VIS_Test]

/****** Object:  Database [KiSS_ZH_VIS_Test]    Script Date: 08/15/2012 10:49:07 ******/
CREATE DATABASE [KiSS_ZH_VIS_Test] ON  PRIMARY 
( NAME = N'KiSS_ZH_VIS_Test_Primary', FILENAME = N'E:\mssql2005\SOZ_KISS_D\MSSQL.1\MSSQL\Data\KiSS_ZH_VIS_Test\KiSS_ZH_VIS_Test_Primary.mdf', SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 262144KB )
 LOG ON 
( NAME = N'KiSS_ZH_VIS_Test_log', FILENAME = N'E:\mssql2005\SOZ_KISS_D\MSSQL.1\MSSQL\Data\KiSS_ZH_VIS_Test\KiSS_ZH_VIS_Test_Log.ldf' , SIZE = 32768KB , MAXSIZE = 2048GB , FILEGROWTH = 32768KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
  EXEC [KiSS_ZH_VIS_Test].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET ANSI_NULLS ON 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET ANSI_PADDING ON 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET ARITHABORT ON 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET  READ_WRITE 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET  MULTI_USER 
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KiSS_ZH_VIS_Test] SET DB_CHAINING OFF 
GO

USE [KiSS_ZH_VIS_Test]
GO

/****** Object:  Table [dbo].[SD_BERICHTE_HIST]    Script Date: 08/15/2012 10:52:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SD_BERICHTE_HIST](
	[Berichts_ID] [int] NULL,
	[VORMSCH_ID] [int] NULL,
	[PERS_NR] [int] NULL,
	[MAND_ID] [int] NULL,
	[FALL_NR] [int] NULL,
	[BERICHTSTERMIN] [datetime] NULL,
	[T1] [int] NULL,
	[BERICHT_VON] [datetime] NULL,
	[BERICHT_PER] [datetime] NULL,
	[MAHNUNG1] [varchar](50) NULL,
	[MAHNUNG2] [varchar](50) NULL,
	[MAHNUNG3] [varchar](50) NULL,
	[EINGANG_SDS] [datetime] NULL,
	[AUSGANG_SDS] [datetime] NULL,
	[VB_BESCHLUSS] [nchar](10) NULL,
	[RB_SB_BRZ] [nchar](10) NULL,
	[FRISTERSTRECKUNG] [nchar](10) NULL,
	[BK_ID] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO


/****** Object:  Table [dbo].[SD_DOSSIER]    Script Date: 08/15/2012 10:52:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SD_DOSSIER](
	[FALL_NR] [int] NULL,
	[ABTEILUNG] [varchar](50) NULL,
	[ZIP_NR] [varchar](50) NULL,
	[NAME] [varchar](50) NULL,
	[ALLIANZNAME] [varchar](50) NULL,
	[VORNAME] [varchar](50) NULL,
	[G_DAT] [datetime] NULL,
	[H_ORT] [varchar](50) NULL,
	[ZIV] [varchar](50) NULL,
	[AHV_NR] [varchar](50) NULL,
	[SEX] [varchar](50) NULL,
	[WMA_STR] [varchar](50) NULL,
	[WMA_POSTLAGERND] [varchar](50) NULL,
	[WMA_PLZ] [varchar](50) NULL,
	[WMA_ORT] [varchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO


/****** Object:  Table [dbo].[SD_MANDATSTRAEGER]    Script Date: 08/15/2012 10:52:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SD_MANDATSTRAEGER](
	[MAND_ID] [int] NULL,
	[VORMSCH_ID] [int] NULL,
	[PERS_NR] [int] NULL,
	[NAME] [varchar](50) NULL,
	[VORNAME] [varchar](50) NULL,
	[ORTSCODE] [varchar](50) NULL,
	[M_ERNENN_DT] [datetime] NULL,
	[M_AUFHEB_DT] [datetime] NULL,
	[BERICHTSTERMIN] [datetime] NULL,
	[T1] [varchar](50) NULL,
	[BERICHT_VON] [datetime] NULL,
	[BERICHT_PER] [datetime] NULL,
	[MAHNUNG1] [varchar](50) NULL,
	[MAHNUNG2] [varchar](50) NULL,
	[MAHNUNG3] [varchar](50) NULL,
	[EINGANG_SDS] [datetime] NULL,
	[AUSGANG_SDS] [datetime] NULL,
	[VB_BESCHLUSS] [datetime] NULL,
	[RB_SB_BRZ] [varchar](50) NULL,
	[FRISTERSTRECKUNG] [varchar](50) NULL,
	[FALL_NR] [int] NULL,
	[BK_ID] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO


/****** Object:  Table [dbo].[SD_MASSNAHMEN]    Script Date: 08/15/2012 10:52:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SD_MASSNAHMEN](
	[Vormsch_ID] [int] NULL,
	[FALL_NR] [int] NULL,
	[BESCH_A_ED] [datetime] NULL,
	[BESCH_A_AD] [datetime] NULL,
	[Massnahme] [varchar](50) NULL,
	[Mandatstyp] [varchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO


/****** Object:  Table [dbo].[SD_MASSNAHMEN_HIST]    Script Date: 08/15/2012 10:52:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SD_MASSNAHMEN_HIST](
	[Vormsch_ID] [int] NULL,
	[FALL_NR] [int] NULL,
	[BESCH_A_ED] [datetime] NULL,
	[BESCH_A_AD] [datetime] NULL,
	[Massnahme] [varchar](50) NULL,
	[Mandatstyp] [varchar](50) NULL,
	[MODDAT] [datetime] NULL,
	[SACHBEARBC] [varchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO


/****** Object:  Table [dbo].[SD_WAISENRAT]    Script Date: 08/15/2012 10:53:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SD_WAISENRAT](
	[Waisenrat] [varchar](50) NULL,
	[Telefon] [varchar](50) NULL,
	[Abteilung] [varchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO


