CREATE TABLE [dbo].[KgBuchung_Backup](
	[KgBuchungID] [int] IDENTITY(1,1) NOT NULL,
	[KgPeriodeID] [int] NOT NULL,
	[KgPositionID] [int] NULL,
	[KgBuchungTypCode] [int] NOT NULL,
	[KgAusgleichStatusCode] [int] NULL,
	[KgZahlungseingangID] [int] NULL,
	[CodeVorlage] [varchar](15) NULL,
	[BelegNr] [varchar](15) NULL,
	[BelegNrPos] [int] NULL,
	[BuchungsDatum] [datetime] NOT NULL,
	[SollKtoNr] [varchar](10) NULL,
	[HabenKtoNr] [varchar](10) NULL,
	[Betrag] [money] NOT NULL,
	[BetragFW] [money] NULL,
	[FbWaehrungID] [int] NULL,
	[Text] [varchar](200) NOT NULL,
	[ValutaDatum] [datetime] NULL,
	[BarbezugDatum] [datetime] NULL,
	[TransferDatum] [datetime] NULL,
	[KgBuchungStatusCode] [int] NULL,
	[UserIDKasse] [int] NULL,
	[BaZahlungswegID] [int] NULL,
	[BaInstitutionID] [int] NULL,
	[EinzahlungsscheinCode] [int] NULL,
	[KgAuszahlungsArtCode] [int] NULL,
	[BaBankID] [int] NULL,
	[BankKontoNummer] [varchar](50) NULL,
	[IBANNummer] [varchar](50) NULL,
	[PostKontoNummer] [varchar](20) NULL,
	[ESRTeilnehmer] [varchar](50) NULL,
	[ESRReferenznummer] [varchar](50) NULL,
	[BeguenstigtName] [varchar](100) NULL,
	[BeguenstigtName2] [varchar](200) NULL,
	[BeguenstigtStrasse] [varchar](100) NULL,
	[BeguenstigtHausNr] [varchar](10) NULL,
	[BeguenstigtPostfach] [varchar](40) NULL,
	[BeguenstigtOrt] [varchar](100) NULL,
	[BeguenstigtPLZ] [varchar](10) NULL,
	[BeguenstigtLandCode] [int] NULL,
	[MitteilungZeile1] [varchar](35) NULL,
	[MitteilungZeile2] [varchar](35) NULL,
	[MitteilungZeile3] [varchar](35) NULL,
	[MitteilungZeile4] [varchar](35) NULL,
	[ErstelltUserID] [int] NULL,
	[ErstelltDatum] [datetime] NULL,
	[MutiertUserID] [int] NULL,
	[MutiertDatum] [datetime] NULL,
	[KgBuchungTS] [timestamp] NOT NULL,
	[PscdFehlermeldung] [varchar](200) NULL,
	[PscdBelegNr] [bigint] NULL,
	[StorniertKgBuchungID] [int] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING ON