CREATE TABLE [dbo].[XKeySource](
	[KeyName] [varchar](50) NOT NULL,
	[NextID] [int] NOT NULL,
	[FirstID] [int] NOT NULL,
	[LastID] [int] NOT NULL,
	[XKeySourceTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_XKeySource] PRIMARY KEY CLUSTERED 
(
	[KeyName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO