CREATE TABLE [dbo].[ConfigKeyPathToKeep](
	[KeyPath] [varchar](500) NOT NULL,
 CONSTRAINT [PK_ConfigKeyPathToKeep] PRIMARY KEY CLUSTERED 
(
	[KeyPath] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO