#region Header

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#endregion

using System;
using System.Collections.Generic;
using System.Data;
using Kiss.Interfaces.UI;
using KiSS4.DB;
using KiSS4.Gui;

namespace KiSS4.Klientenbuchhaltung.ZH
{
    public class CtlKbWVEinzelposten : KiSS4.Common.KissSearchUserControl
    {
        #region Fields

        private KiSS4.Gui.KissButton btnAlle;
        private KiSS4.Gui.KissButton btnKeine;
        private KiSS4.Gui.KissButton btnStatusSetzen;
        private KiSS4.Gui.KissButton btnStornoVerstecken;
        private DevExpress.XtraGrid.Columns.GridColumn colBED;
        private DevExpress.XtraGrid.Columns.GridColumn colBetrag;
        private DevExpress.XtraGrid.Columns.GridColumn colEinheitstraeger;
        private DevExpress.XtraGrid.Columns.GridColumn colFaktura;
        private DevExpress.XtraGrid.Columns.GridColumn colKostenart;
        private DevExpress.XtraGrid.Columns.GridColumn colPeriode;
        private DevExpress.XtraGrid.Columns.GridColumn colPscdBelegNr;
        private DevExpress.XtraGrid.Columns.GridColumn colSel;
        private DevExpress.XtraGrid.Columns.GridColumn colStatus;
        private DevExpress.XtraGrid.Columns.GridColumn colStatusShort;
        private DevExpress.XtraGrid.Columns.GridColumn colUT;
        private DevExpress.XtraGrid.Columns.GridColumn colWVCode;
        private System.ComponentModel.IContainer components;
        private KiSS4.Gui.KissLookUpEdit edtBED;
        private KiSS4.Gui.KissTextEdit edtPeriode;
        private KiSS4.Gui.KissTextEdit edtPscdBelegNr;
        private KiSS4.Gui.KissLookUpEdit edtSearchBED;
        private KiSS4.Gui.KissCalcEdit edtSearchJahr;
        private KiSS4.Gui.KissTextEdit edtSearchKbWVLaufID;
        private KiSS4.Gui.KissLookUpEdit edtSearchPeriod;
        private KiSS4.Gui.KissLookUpEdit edtSearchStatus;
        private KiSS4.Gui.KissTextEdit edtSearchUT;
        private KiSS4.Gui.KissLookUpEdit edtSearchWVCode;
        private KiSS4.Gui.KissLookUpEdit edtStatus;
        private KiSS4.Gui.KissLookUpEdit edtStatusAlt;
        private KiSS4.Gui.KissTextEdit edtUT;
        private KiSS4.Gui.KissCalcEdit edtUTBaPersonID;
        private KiSS4.Gui.KissLookUpEdit edtWVCode;
        private KiSS4.Gui.KissGrid grdWVEinzelposten;
        private DevExpress.XtraGrid.Views.Grid.GridView grvKbWVEinzelposten;
        private KiSS4.Gui.KissLabel kissLabel1;
        private KiSS4.Gui.KissLabel kissLabel2;
        private KiSS4.Gui.KissLabel kissLabel3;
        private KiSS4.Gui.KissLabel kissLabel4;
        private KiSS4.Gui.KissLabel kissLabel5;
        private KiSS4.Gui.KissLabel kissLabel6;
        private KiSS4.Gui.KissLabel kissLabel7;
        private KiSS4.Gui.KissLabel kissLabel8;
        private KiSS4.Gui.KissTextEdit kissTextEdit1;
        private KiSS4.Gui.KissLabel lblBED;
        private KiSS4.Gui.KissLabel lblFakturaNr;
        private KiSS4.Gui.KissLabel lblJahr;
        private KiSS4.Gui.KissLabel lblStatus;
        private KiSS4.Gui.KissLabel lblTotalSelektierteUndBetrag;
        private KiSS4.Gui.KissLabel lblUT;
        private KiSS4.Gui.KissLabel lblUTID;
        private KiSS4.Gui.KissLabel lblWVCode;
        private KiSS4.Gui.KissLabel lblZeitspanne;
        private KiSS4.DB.SqlQuery qryKbWVEinzelposten;
        private DevExpress.XtraGrid.Columns.GridColumn colLA;
        private DevExpress.XtraGrid.Columns.GridColumn colVPVon;
        private DevExpress.XtraGrid.Columns.GridColumn colVPBis;
        private DevExpress.XtraGrid.Columns.GridColumn colBelegNrBrutto;
        private DevExpress.XtraGrid.Columns.GridColumn colBruttobetrag;
        private DevExpress.XtraEditors.Repository.RepositoryItemCheckEdit repositoryItemCheckEdit1;

        #endregion

        #region Constructors

        public CtlKbWVEinzelposten()
        {
            this.InitializeComponent();

            repositoryItemCheckEdit1.EditValueChanging += SelectionChanging;

            colWVCode.ColumnEdit = grdWVEinzelposten.GetLOVLookUpEdit( DBUtil.OpenSQL( "SELECT Code, Text = ShortText FROM XLOVCode WHERE LOVName = 'BaWVCode'" ) );
            colStatus.ColumnEdit = grdWVEinzelposten.GetLOVLookUpEdit( "KbWVEinzelpostenStatus" );

            SqlQuery qryWVCode = DBUtil.OpenSQL(@"
                SELECT Code = NULL, Text = ''
                UNION ALL
                select  Code,
                    Text = Shorttext + '  ' + Text
                from    XLOVCode
                where   LOVName = 'BaWVCode' and Shorttext NOT IN('?-?','I-F','S-F','Z-E','K-E','A-E','F-E','B-E')");
            edtSearchWVCode.Properties.DataSource = qryWVCode;
            edtWVCode.Properties.DataSource = qryWVCode;

            SqlQuery qryBED = DBUtil.OpenSQL(@"
                SELECT Code = NULL, Text = ''
                UNION ALL
                select  Code,
                    Text = CAST( Code AS varchar ) + ',  ' + Text
                from    XLOVCode
                where   LOVName = 'BaBED' and Code NOT IN(16030,16031,16032)");
            edtSearchBED.Properties.DataSource = qryBED;
            edtBED.Properties.DataSource = qryBED;

            SqlQuery qryStatus = DBUtil.OpenSQL(@"
                SELECT Code = NULL, Text = ''
                UNION ALL
                select  Code,
                    Text = ShortText + '  (' + Text + ')'
                from    XLOVCode
                where   LOVName = 'KbWVEinzelpostenStatus' and Shorttext NOT IN('T','H')");
            edtSearchStatus.Properties.DataSource = qryStatus;
            edtStatusAlt.Properties.DataSource = qryStatus;

            SqlQuery qryStatusNeu = DBUtil.OpenSQL(@"
                SELECT Code = NULL, Text = ''
                UNION ALL
                select  Code,
                        Text = ShortText + '  (' + Text + ')'
                from    XLOVCode
                where   LOVName = 'KbWVEinzelpostenStatus'
                  and Code in (6,7) /*N,S*/");
            edtStatus.Properties.DataSource = qryStatusNeu;

            SqlQuery qryPeriod = DBUtil.OpenSQL(@"
                SELECT Code = NULL, Text = '', SortKey=0
                UNION ALL
                SELECT Code = Code,
                    Text = Text, SortKey
                FROM XLOVCode
                WHERE LOVName = 'KbWVLaufPeriode'
                ORDER BY SortKey");
            edtSearchPeriod.Properties.DataSource = qryPeriod;

            //edtSearchJahr.EditValue = DateTime.Today.Year;
            /*
            edtUT.LookupSQL = @"
            SELECT BaPersonID, Name + IsNull( ', ' + Vorname, '' )
            FROM BaPerson
            WHERE Name LIKE {0}
            ----
            SELECT Name + IsNull( ', ' + Vorname, '' )
            FROM BaPerson
            WHERE BaPersonID = {0}
            ";
            edtBeguenstigter.LookupSQL = edtUT.LookupSQL;
            */
            btnStornoVerstecken.Enabled = false;
            btnStatusSetzen.Enabled = false;
            tabControlSearch.SelectedTabIndex = 1;
        }

        #endregion

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CtlKbWVEinzelposten));
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject4 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject3 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject2 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject1 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject8 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject7 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject6 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject5 = new DevExpress.Utils.SerializableAppearanceObject();
            this.grdWVEinzelposten = new KiSS4.Gui.KissGrid();
            this.qryKbWVEinzelposten = new KiSS4.DB.SqlQuery(this.components);
            this.grvKbWVEinzelposten = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.colBED = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colFaktura = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colPeriode = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colWVCode = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colStatus = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colStatusShort = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colBetrag = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colKostenart = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colUT = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colEinheitstraeger = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colSel = new DevExpress.XtraGrid.Columns.GridColumn();
            this.repositoryItemCheckEdit1 = new DevExpress.XtraEditors.Repository.RepositoryItemCheckEdit();
            this.colLA = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colVPVon = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colVPBis = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colPscdBelegNr = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colBelegNrBrutto = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colBruttobetrag = new DevExpress.XtraGrid.Columns.GridColumn();
            this.kissLabel4 = new KiSS4.Gui.KissLabel();
            this.kissLabel1 = new KiSS4.Gui.KissLabel();
            this.kissLabel2 = new KiSS4.Gui.KissLabel();
            this.kissLabel3 = new KiSS4.Gui.KissLabel();
            this.kissLabel5 = new KiSS4.Gui.KissLabel();
            this.edtBED = new KiSS4.Gui.KissLookUpEdit();
            this.edtStatusAlt = new KiSS4.Gui.KissLookUpEdit();
            this.edtWVCode = new KiSS4.Gui.KissLookUpEdit();
            this.edtUT = new KiSS4.Gui.KissTextEdit();
            this.kissTextEdit1 = new KiSS4.Gui.KissTextEdit();
            this.kissLabel7 = new KiSS4.Gui.KissLabel();
            this.kissLabel8 = new KiSS4.Gui.KissLabel();
            this.edtStatus = new KiSS4.Gui.KissLookUpEdit();
            this.btnStatusSetzen = new KiSS4.Gui.KissButton();
            this.btnKeine = new KiSS4.Gui.KissButton();
            this.btnAlle = new KiSS4.Gui.KissButton();
            this.edtPeriode = new KiSS4.Gui.KissTextEdit();
            this.lblTotalSelektierteUndBetrag = new KiSS4.Gui.KissLabel();
            this.btnStornoVerstecken = new KiSS4.Gui.KissButton();
            this.lblBED = new KiSS4.Gui.KissLabel();
            this.lblWVCode = new KiSS4.Gui.KissLabel();
            this.lblUT = new KiSS4.Gui.KissLabel();
            this.lblStatus = new KiSS4.Gui.KissLabel();
            this.lblUTID = new KiSS4.Gui.KissLabel();
            this.edtSearchBED = new KiSS4.Gui.KissLookUpEdit();
            this.edtSearchStatus = new KiSS4.Gui.KissLookUpEdit();
            this.edtSearchWVCode = new KiSS4.Gui.KissLookUpEdit();
            this.edtSearchUT = new KiSS4.Gui.KissTextEdit();
            this.lblZeitspanne = new KiSS4.Gui.KissLabel();
            this.lblJahr = new KiSS4.Gui.KissLabel();
            this.lblFakturaNr = new KiSS4.Gui.KissLabel();
            this.edtSearchKbWVLaufID = new KiSS4.Gui.KissTextEdit();
            this.edtUTBaPersonID = new KiSS4.Gui.KissCalcEdit();
            this.edtSearchPeriod = new KiSS4.Gui.KissLookUpEdit();
            this.edtSearchJahr = new KiSS4.Gui.KissCalcEdit();
            this.kissLabel6 = new KiSS4.Gui.KissLabel();
            this.edtPscdBelegNr = new KiSS4.Gui.KissTextEdit();
            this.tabControlSearch.SuspendLayout();
            this.tpgListe.SuspendLayout();
            this.tpgSuchen.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdWVEinzelposten)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.qryKbWVEinzelposten)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grvKbWVEinzelposten)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemCheckEdit1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtBED)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtBED.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtStatusAlt)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtStatusAlt.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtWVCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtWVCode.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtUT.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissTextEdit1.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtStatus)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtStatus.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtPeriode.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblTotalSelektierteUndBetrag)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblBED)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblWVCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblUT)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblStatus)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblUTID)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchBED)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchBED.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchStatus)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchStatus.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchWVCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchWVCode.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchUT.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblZeitspanne)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblJahr)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblFakturaNr)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchKbWVLaufID.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtUTBaPersonID.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchPeriod)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchPeriod.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchJahr.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtPscdBelegNr.Properties)).BeginInit();
            this.SuspendLayout();
            // 
            // searchTitle
            // 
            this.searchTitle.Size = new System.Drawing.Size(776, 24);
            // 
            // tabControlSearch
            // 
            this.tabControlSearch.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.tabControlSearch.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControlSearch.Location = new System.Drawing.Point(0, 0);
            this.tabControlSearch.Size = new System.Drawing.Size(800, 500);
            this.tabControlSearch.SelectedTabChanged += new SharpLibrary.WinControls.TabControlExTabChangeEventHandler(this.tabControlSearch_SelectedTabChanged);
            // 
            // tpgListe
            // 
            this.tpgListe.Controls.Add(this.btnStornoVerstecken);
            this.tpgListe.Controls.Add(this.lblTotalSelektierteUndBetrag);
            this.tpgListe.Controls.Add(this.edtPeriode);
            this.tpgListe.Controls.Add(this.btnAlle);
            this.tpgListe.Controls.Add(this.btnKeine);
            this.tpgListe.Controls.Add(this.btnStatusSetzen);
            this.tpgListe.Controls.Add(this.edtStatus);
            this.tpgListe.Controls.Add(this.kissLabel8);
            this.tpgListe.Controls.Add(this.kissLabel7);
            this.tpgListe.Controls.Add(this.kissTextEdit1);
            this.tpgListe.Controls.Add(this.edtUT);
            this.tpgListe.Controls.Add(this.edtWVCode);
            this.tpgListe.Controls.Add(this.edtStatusAlt);
            this.tpgListe.Controls.Add(this.edtBED);
            this.tpgListe.Controls.Add(this.kissLabel5);
            this.tpgListe.Controls.Add(this.kissLabel3);
            this.tpgListe.Controls.Add(this.kissLabel2);
            this.tpgListe.Controls.Add(this.kissLabel1);
            this.tpgListe.Controls.Add(this.kissLabel4);
            this.tpgListe.Controls.Add(this.grdWVEinzelposten);
            this.tpgListe.Size = new System.Drawing.Size(788, 462);
            this.tpgListe.Title = "Liste";
            // 
            // tpgSuchen
            // 
            this.tpgSuchen.Controls.Add(this.edtPscdBelegNr);
            this.tpgSuchen.Controls.Add(this.kissLabel6);
            this.tpgSuchen.Controls.Add(this.edtSearchJahr);
            this.tpgSuchen.Controls.Add(this.edtSearchPeriod);
            this.tpgSuchen.Controls.Add(this.edtUTBaPersonID);
            this.tpgSuchen.Controls.Add(this.edtSearchKbWVLaufID);
            this.tpgSuchen.Controls.Add(this.lblFakturaNr);
            this.tpgSuchen.Controls.Add(this.lblJahr);
            this.tpgSuchen.Controls.Add(this.lblZeitspanne);
            this.tpgSuchen.Controls.Add(this.edtSearchUT);
            this.tpgSuchen.Controls.Add(this.edtSearchWVCode);
            this.tpgSuchen.Controls.Add(this.edtSearchStatus);
            this.tpgSuchen.Controls.Add(this.edtSearchBED);
            this.tpgSuchen.Controls.Add(this.lblUTID);
            this.tpgSuchen.Controls.Add(this.lblStatus);
            this.tpgSuchen.Controls.Add(this.lblUT);
            this.tpgSuchen.Controls.Add(this.lblWVCode);
            this.tpgSuchen.Controls.Add(this.lblBED);
            this.tpgSuchen.Size = new System.Drawing.Size(788, 462);
            this.tpgSuchen.Title = "Suche";
            this.tpgSuchen.Controls.SetChildIndex(this.searchTitle, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.lblBED, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.lblWVCode, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.lblUT, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.lblStatus, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.lblUTID, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtSearchBED, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtSearchStatus, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtSearchWVCode, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtSearchUT, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.lblZeitspanne, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.lblJahr, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.lblFakturaNr, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtSearchKbWVLaufID, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtUTBaPersonID, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtSearchPeriod, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtSearchJahr, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.kissLabel6, 0);
            this.tpgSuchen.Controls.SetChildIndex(this.edtPscdBelegNr, 0);
            // 
            // grdWVEinzelposten
            // 
            this.grdWVEinzelposten.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.grdWVEinzelposten.DataSource = this.qryKbWVEinzelposten;
            // 
            // 
            // 
            this.grdWVEinzelposten.EmbeddedNavigator.Name = "";
            this.grdWVEinzelposten.Location = new System.Drawing.Point(3, 25);
            this.grdWVEinzelposten.MainView = this.grvKbWVEinzelposten;
            this.grdWVEinzelposten.Name = "grdWVEinzelposten";
            this.grdWVEinzelposten.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] {
            this.repositoryItemCheckEdit1});
            this.grdWVEinzelposten.Size = new System.Drawing.Size(782, 226);
            this.grdWVEinzelposten.TabIndex = 0;
            this.grdWVEinzelposten.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.grvKbWVEinzelposten});
            // 
            // qryKbWVEinzelposten
            // 
            this.qryKbWVEinzelposten.BatchUpdate = true;
            this.qryKbWVEinzelposten.CanUpdate = true;
            this.qryKbWVEinzelposten.HostControl = this;
            this.qryKbWVEinzelposten.SelectStatement = resources.GetString("qryKbWVEinzelposten.SelectStatement");
            this.qryKbWVEinzelposten.TableName = "KbWVEinzelposten";
            this.qryKbWVEinzelposten.PositionChanged += new System.EventHandler(this.qryKbWVEinzelposten_PositionChanged);
            // 
            // grvKbWVEinzelposten
            // 
            this.grvKbWVEinzelposten.Appearance.Empty.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.grvKbWVEinzelposten.Appearance.Empty.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.grvKbWVEinzelposten.Appearance.Empty.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.Empty.Options.UseFont = true;
            this.grvKbWVEinzelposten.Appearance.EvenRow.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(227)))), ((int)(((byte)(215)))));
            this.grvKbWVEinzelposten.Appearance.EvenRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.grvKbWVEinzelposten.Appearance.EvenRow.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.EvenRow.Options.UseFont = true;
            this.grvKbWVEinzelposten.Appearance.FocusedCell.BackColor = System.Drawing.SystemColors.Highlight;
            this.grvKbWVEinzelposten.Appearance.FocusedCell.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.grvKbWVEinzelposten.Appearance.FocusedCell.ForeColor = System.Drawing.Color.White;
            this.grvKbWVEinzelposten.Appearance.FocusedCell.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.FocusedCell.Options.UseFont = true;
            this.grvKbWVEinzelposten.Appearance.FocusedCell.Options.UseForeColor = true;
            this.grvKbWVEinzelposten.Appearance.FocusedRow.BackColor = System.Drawing.SystemColors.Highlight;
            this.grvKbWVEinzelposten.Appearance.FocusedRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.grvKbWVEinzelposten.Appearance.FocusedRow.ForeColor = System.Drawing.Color.White;
            this.grvKbWVEinzelposten.Appearance.FocusedRow.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.FocusedRow.Options.UseFont = true;
            this.grvKbWVEinzelposten.Appearance.FocusedRow.Options.UseForeColor = true;
            this.grvKbWVEinzelposten.Appearance.GroupPanel.BackColor = System.Drawing.Color.PeachPuff;
            this.grvKbWVEinzelposten.Appearance.GroupPanel.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.GroupRow.BackColor = System.Drawing.Color.PeachPuff;
            this.grvKbWVEinzelposten.Appearance.GroupRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.grvKbWVEinzelposten.Appearance.GroupRow.ForeColor = System.Drawing.SystemColors.WindowText;
            this.grvKbWVEinzelposten.Appearance.GroupRow.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.GroupRow.Options.UseFont = true;
            this.grvKbWVEinzelposten.Appearance.GroupRow.Options.UseForeColor = true;
            this.grvKbWVEinzelposten.Appearance.HeaderPanel.BackColor = System.Drawing.Color.Tan;
            this.grvKbWVEinzelposten.Appearance.HeaderPanel.BorderColor = System.Drawing.Color.Tan;
            this.grvKbWVEinzelposten.Appearance.HeaderPanel.Font = new System.Drawing.Font("Arial", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.grvKbWVEinzelposten.Appearance.HeaderPanel.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.HeaderPanel.Options.UseBorderColor = true;
            this.grvKbWVEinzelposten.Appearance.HeaderPanel.Options.UseFont = true;
            this.grvKbWVEinzelposten.Appearance.HideSelectionRow.BackColor = System.Drawing.Color.PowderBlue;
            this.grvKbWVEinzelposten.Appearance.HideSelectionRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.grvKbWVEinzelposten.Appearance.HideSelectionRow.ForeColor = System.Drawing.SystemColors.WindowText;
            this.grvKbWVEinzelposten.Appearance.HideSelectionRow.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.HideSelectionRow.Options.UseFont = true;
            this.grvKbWVEinzelposten.Appearance.HideSelectionRow.Options.UseForeColor = true;
            this.grvKbWVEinzelposten.Appearance.HorzLine.BackColor = System.Drawing.Color.Silver;
            this.grvKbWVEinzelposten.Appearance.HorzLine.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.OddRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.grvKbWVEinzelposten.Appearance.OddRow.Options.UseFont = true;
            this.grvKbWVEinzelposten.Appearance.Row.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.grvKbWVEinzelposten.Appearance.Row.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.grvKbWVEinzelposten.Appearance.Row.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.Row.Options.UseFont = true;
            this.grvKbWVEinzelposten.Appearance.SelectedRow.BackColor = System.Drawing.Color.AliceBlue;
            this.grvKbWVEinzelposten.Appearance.SelectedRow.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.grvKbWVEinzelposten.Appearance.SelectedRow.ForeColor = System.Drawing.Color.Black;
            this.grvKbWVEinzelposten.Appearance.SelectedRow.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.Appearance.SelectedRow.Options.UseFont = true;
            this.grvKbWVEinzelposten.Appearance.SelectedRow.Options.UseForeColor = true;
            this.grvKbWVEinzelposten.Appearance.VertLine.BackColor = System.Drawing.Color.Silver;
            this.grvKbWVEinzelposten.Appearance.VertLine.Options.UseBackColor = true;
            this.grvKbWVEinzelposten.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.grvKbWVEinzelposten.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.colBED,
            this.colFaktura,
            this.colPeriode,
            this.colWVCode,
            this.colStatus,
            this.colStatusShort,
            this.colBetrag,
            this.colKostenart,
            this.colUT,
            this.colEinheitstraeger,
            this.colSel,
            this.colLA,
            this.colVPVon,
            this.colVPBis,
            this.colPscdBelegNr,
            this.colBelegNrBrutto,
            this.colBruttobetrag});
            this.grvKbWVEinzelposten.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.None;
            this.grvKbWVEinzelposten.GridControl = this.grdWVEinzelposten;
            this.grvKbWVEinzelposten.Name = "grvKbWVEinzelposten";
            this.grvKbWVEinzelposten.OptionsCustomization.AllowFilter = false;
            this.grvKbWVEinzelposten.OptionsFilter.UseNewCustomFilterDialog = true;
            this.grvKbWVEinzelposten.OptionsNavigation.AutoFocusNewRow = true;
            this.grvKbWVEinzelposten.OptionsNavigation.UseTabKey = false;
            this.grvKbWVEinzelposten.OptionsView.ColumnAutoWidth = false;
            this.grvKbWVEinzelposten.OptionsView.ShowFilterPanelMode = DevExpress.XtraGrid.Views.Base.ShowFilterPanelMode.Never;
            this.grvKbWVEinzelposten.OptionsView.ShowGroupPanel = false;
            this.grvKbWVEinzelposten.OptionsView.ShowIndicator = false;
            // 
            // colBED
            // 
            this.colBED.AppearanceCell.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colBED.AppearanceCell.Options.UseBackColor = true;
            this.colBED.Caption = "BED";
            this.colBED.FieldName = "BEDCode";
            this.colBED.Name = "colBED";
            this.colBED.OptionsColumn.AllowEdit = false;
            this.colBED.Visible = true;
            this.colBED.VisibleIndex = 3;
            this.colBED.Width = 41;
            // 
            // colFaktura
            // 
            this.colFaktura.AppearanceCell.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colFaktura.AppearanceCell.Options.UseBackColor = true;
            this.colFaktura.Caption = "Faktura-Nr.";
            this.colFaktura.FieldName = "KbWVLaufID";
            this.colFaktura.Name = "colFaktura";
            this.colFaktura.OptionsColumn.AllowEdit = false;
            this.colFaktura.Visible = true;
            this.colFaktura.VisibleIndex = 0;
            this.colFaktura.Width = 72;
            // 
            // colPeriode
            // 
            this.colPeriode.AppearanceCell.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colPeriode.AppearanceCell.Options.UseBackColor = true;
            this.colPeriode.AppearanceHeader.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colPeriode.AppearanceHeader.Options.UseBackColor = true;
            this.colPeriode.Caption = "Periode";
            this.colPeriode.FieldName = "Periode";
            this.colPeriode.Name = "colPeriode";
            this.colPeriode.OptionsColumn.AllowEdit = false;
            this.colPeriode.Visible = true;
            this.colPeriode.VisibleIndex = 1;
            this.colPeriode.Width = 106;
            // 
            // colWVCode
            // 
            this.colWVCode.AppearanceCell.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colWVCode.AppearanceCell.Options.UseBackColor = true;
            this.colWVCode.AppearanceHeader.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colWVCode.AppearanceHeader.Options.UseBackColor = true;
            this.colWVCode.Caption = "WVCode";
            this.colWVCode.FieldName = "WVCode";
            this.colWVCode.Name = "colWVCode";
            this.colWVCode.OptionsColumn.AllowEdit = false;
            this.colWVCode.Visible = true;
            this.colWVCode.VisibleIndex = 2;
            this.colWVCode.Width = 59;
            // 
            // colStatus
            // 
            this.colStatus.AppearanceCell.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colStatus.AppearanceCell.Options.UseBackColor = true;
            this.colStatus.AppearanceHeader.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colStatus.AppearanceHeader.Options.UseBackColor = true;
            this.colStatus.Caption = "Status";
            this.colStatus.FieldName = "KbWVEinzelpostenStatusCode";
            this.colStatus.Name = "colStatus";
            this.colStatus.OptionsColumn.AllowEdit = false;
            this.colStatus.Width = 120;
            // 
            // colStatusShort
            // 
            this.colStatusShort.Caption = "Status";
            this.colStatusShort.FieldName = "StatusShort";
            this.colStatusShort.Name = "colStatusShort";
            this.colStatusShort.OptionsColumn.AllowEdit = false;
            this.colStatusShort.Visible = true;
            this.colStatusShort.VisibleIndex = 4;
            this.colStatusShort.Width = 47;
            // 
            // colBetrag
            // 
            this.colBetrag.AppearanceCell.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colBetrag.AppearanceCell.Options.UseBackColor = true;
            this.colBetrag.AppearanceHeader.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colBetrag.AppearanceHeader.Options.UseBackColor = true;
            this.colBetrag.Caption = "Betrag";
            this.colBetrag.DisplayFormat.FormatString = "N2";
            this.colBetrag.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.colBetrag.FieldName = "Betrag";
            this.colBetrag.Name = "colBetrag";
            this.colBetrag.OptionsColumn.AllowEdit = false;
            this.colBetrag.Visible = true;
            this.colBetrag.VisibleIndex = 5;
            this.colBetrag.Width = 66;
            // 
            // colKostenart
            // 
            this.colKostenart.AppearanceCell.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colKostenart.AppearanceCell.Options.UseBackColor = true;
            this.colKostenart.AppearanceHeader.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colKostenart.AppearanceHeader.Options.UseBackColor = true;
            this.colKostenart.Caption = "Buchungstext";
            this.colKostenart.FieldName = "Buchungstext";
            this.colKostenart.Name = "colKostenart";
            this.colKostenart.OptionsColumn.AllowEdit = false;
            this.colKostenart.Visible = true;
            this.colKostenart.VisibleIndex = 6;
            this.colKostenart.Width = 176;
            // 
            // colUT
            // 
            this.colUT.AppearanceCell.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colUT.AppearanceCell.Options.UseBackColor = true;
            this.colUT.AppearanceHeader.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colUT.AppearanceHeader.Options.UseBackColor = true;
            this.colUT.Caption = "Unterstützungsträger";
            this.colUT.FieldName = "UT";
            this.colUT.Name = "colUT";
            this.colUT.OptionsColumn.AllowEdit = false;
            this.colUT.Visible = true;
            this.colUT.VisibleIndex = 7;
            this.colUT.Width = 152;
            // 
            // colEinheitstraeger
            // 
            this.colEinheitstraeger.AppearanceCell.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colEinheitstraeger.AppearanceCell.Options.UseBackColor = true;
            this.colEinheitstraeger.AppearanceHeader.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colEinheitstraeger.AppearanceHeader.Options.UseBackColor = true;
            this.colEinheitstraeger.Caption = "P-Nr. WV-Einheitträger";
            this.colEinheitstraeger.FieldName = "Einheitstraeger";
            this.colEinheitstraeger.Name = "colEinheitstraeger";
            this.colEinheitstraeger.OptionsColumn.AllowEdit = false;
            this.colEinheitstraeger.Visible = true;
            this.colEinheitstraeger.VisibleIndex = 8;
            this.colEinheitstraeger.Width = 135;
            // 
            // colSel
            // 
            this.colSel.AppearanceCell.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colSel.AppearanceCell.Options.UseBackColor = true;
            this.colSel.AppearanceHeader.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.colSel.AppearanceHeader.Options.UseBackColor = true;
            this.colSel.Caption = "Sel";
            this.colSel.ColumnEdit = this.repositoryItemCheckEdit1;
            this.colSel.FieldName = "Sel";
            this.colSel.Name = "colSel";
            this.colSel.Visible = true;
            this.colSel.VisibleIndex = 9;
            this.colSel.Width = 30;
            // 
            // repositoryItemCheckEdit1
            // 
            this.repositoryItemCheckEdit1.AutoHeight = false;
            this.repositoryItemCheckEdit1.Name = "repositoryItemCheckEdit1";
            // 
            // colLA
            // 
            this.colLA.Caption = "LA";
            this.colLA.FieldName = "LA";
            this.colLA.Name = "colLA";
            this.colLA.ToolTip = "Leistungsart";
            this.colLA.Visible = true;
            this.colLA.VisibleIndex = 10;
            this.colLA.Width = 50;
            // 
            // colVPVon
            // 
            this.colVPVon.Caption = "VP von";
            this.colVPVon.FieldName = "DatumVon";
            this.colVPVon.Name = "colVPVon";
            this.colVPVon.ToolTip = "Verwendungsperiode von";
            this.colVPVon.Visible = true;
            this.colVPVon.VisibleIndex = 11;
            // 
            // colVPBis
            // 
            this.colVPBis.Caption = "VP bis";
            this.colVPBis.FieldName = "DatumBis";
            this.colVPBis.Name = "colVPBis";
            this.colVPBis.ToolTip = "Verwendungsperiode bis";
            this.colVPBis.Visible = true;
            this.colVPBis.VisibleIndex = 12;
            // 
            // colPscdBelegNr
            // 
            this.colPscdBelegNr.Caption = "PSCD Beleg";
            this.colPscdBelegNr.FieldName = "PscdBelegNr";
            this.colPscdBelegNr.Name = "colPscdBelegNr";
            this.colPscdBelegNr.OptionsColumn.AllowEdit = false;
            this.colPscdBelegNr.Visible = true;
            this.colPscdBelegNr.VisibleIndex = 13;
            this.colPscdBelegNr.Width = 100;
            // 
            // colBelegNrBrutto
            // 
            this.colBelegNrBrutto.Caption = "BruttobelegNr";
            this.colBelegNrBrutto.FieldName = "BruttobelegNr";
            this.colBelegNrBrutto.Name = "colBelegNrBrutto";
            this.colBelegNrBrutto.Visible = true;
            this.colBelegNrBrutto.VisibleIndex = 14;
            this.colBelegNrBrutto.Width = 100;
            // 
            // colBruttobetrag
            // 
            this.colBruttobetrag.Caption = "Bruttobetrag";
            this.colBruttobetrag.DisplayFormat.FormatString = "N2";
            this.colBruttobetrag.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.colBruttobetrag.FieldName = "BruttobelegBetrag";
            this.colBruttobetrag.Name = "colBruttobetrag";
            this.colBruttobetrag.Visible = true;
            this.colBruttobetrag.VisibleIndex = 15;
            this.colBruttobetrag.Width = 66;
            // 
            // kissLabel4
            // 
            this.kissLabel4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.kissLabel4.Location = new System.Drawing.Point(3, 288);
            this.kissLabel4.Name = "kissLabel4";
            this.kissLabel4.Size = new System.Drawing.Size(100, 23);
            this.kissLabel4.TabIndex = 9;
            this.kissLabel4.Text = "BED";
            this.kissLabel4.UseCompatibleTextRendering = true;
            // 
            // kissLabel1
            // 
            this.kissLabel1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.kissLabel1.Location = new System.Drawing.Point(3, 318);
            this.kissLabel1.Name = "kissLabel1";
            this.kissLabel1.Size = new System.Drawing.Size(100, 23);
            this.kissLabel1.TabIndex = 10;
            this.kissLabel1.Text = "WV-Code";
            this.kissLabel1.UseCompatibleTextRendering = true;
            // 
            // kissLabel2
            // 
            this.kissLabel2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.kissLabel2.Location = new System.Drawing.Point(3, 377);
            this.kissLabel2.Name = "kissLabel2";
            this.kissLabel2.Size = new System.Drawing.Size(123, 24);
            this.kissLabel2.TabIndex = 11;
            this.kissLabel2.Text = "Unterstützungsträger";
            this.kissLabel2.UseCompatibleTextRendering = true;
            // 
            // kissLabel3
            // 
            this.kissLabel3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.kissLabel3.Location = new System.Drawing.Point(3, 407);
            this.kissLabel3.Name = "kissLabel3";
            this.kissLabel3.Size = new System.Drawing.Size(123, 24);
            this.kissLabel3.TabIndex = 12;
            this.kissLabel3.Text = "Begünstigte Person";
            this.kissLabel3.UseCompatibleTextRendering = true;
            // 
            // kissLabel5
            // 
            this.kissLabel5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.kissLabel5.Location = new System.Drawing.Point(3, 347);
            this.kissLabel5.Name = "kissLabel5";
            this.kissLabel5.Size = new System.Drawing.Size(123, 24);
            this.kissLabel5.TabIndex = 12;
            this.kissLabel5.Text = "Status";
            this.kissLabel5.UseCompatibleTextRendering = true;
            // 
            // edtBED
            // 
            this.edtBED.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.edtBED.DataMember = "BEDCode";
            this.edtBED.DataSource = this.qryKbWVEinzelposten;
            this.edtBED.EditMode = Kiss.Interfaces.UI.EditModeType.ReadOnly;
            this.edtBED.Location = new System.Drawing.Point(132, 287);
            this.edtBED.Name = "edtBED";
            this.edtBED.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.edtBED.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtBED.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtBED.Properties.Appearance.Options.UseBackColor = true;
            this.edtBED.Properties.Appearance.Options.UseBorderColor = true;
            this.edtBED.Properties.Appearance.Options.UseFont = true;
            this.edtBED.Properties.AppearanceDropDown.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.edtBED.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.edtBED.Properties.AppearanceDropDown.Options.UseBackColor = true;
            this.edtBED.Properties.AppearanceDropDown.Options.UseFont = true;
            this.edtBED.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject4.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject4.Options.UseBackColor = true;
            this.edtBED.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo, "", -1, true, true, false, DevExpress.Utils.HorzAlignment.Center, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject4)});
            this.edtBED.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtBED.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Text")});
            this.edtBED.Properties.DisplayMember = "Text";
            this.edtBED.Properties.NullText = "";
            this.edtBED.Properties.ReadOnly = true;
            this.edtBED.Properties.ShowFooter = false;
            this.edtBED.Properties.ShowHeader = false;
            this.edtBED.Properties.ValueMember = "Code";
            this.edtBED.Size = new System.Drawing.Size(372, 24);
            this.edtBED.TabIndex = 13;
            // 
            // edtStatusAlt
            // 
            this.edtStatusAlt.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.edtStatusAlt.DataMember = "KbWVEinzelpostenStatusCode";
            this.edtStatusAlt.DataSource = this.qryKbWVEinzelposten;
            this.edtStatusAlt.EditMode = Kiss.Interfaces.UI.EditModeType.ReadOnly;
            this.edtStatusAlt.Location = new System.Drawing.Point(132, 347);
            this.edtStatusAlt.LOVName = "KbWVEinzelpostenStatus";
            this.edtStatusAlt.Name = "edtStatusAlt";
            this.edtStatusAlt.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.edtStatusAlt.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtStatusAlt.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtStatusAlt.Properties.Appearance.Options.UseBackColor = true;
            this.edtStatusAlt.Properties.Appearance.Options.UseBorderColor = true;
            this.edtStatusAlt.Properties.Appearance.Options.UseFont = true;
            this.edtStatusAlt.Properties.AppearanceDropDown.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.edtStatusAlt.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.edtStatusAlt.Properties.AppearanceDropDown.Options.UseBackColor = true;
            this.edtStatusAlt.Properties.AppearanceDropDown.Options.UseFont = true;
            this.edtStatusAlt.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject3.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject3.Options.UseBackColor = true;
            this.edtStatusAlt.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo, "", -1, true, true, false, DevExpress.Utils.HorzAlignment.Center, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject3)});
            this.edtStatusAlt.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtStatusAlt.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Text")});
            this.edtStatusAlt.Properties.DisplayMember = "Text";
            this.edtStatusAlt.Properties.NullText = "";
            this.edtStatusAlt.Properties.ReadOnly = true;
            this.edtStatusAlt.Properties.ShowFooter = false;
            this.edtStatusAlt.Properties.ShowHeader = false;
            this.edtStatusAlt.Properties.ValueMember = "Code";
            this.edtStatusAlt.Size = new System.Drawing.Size(372, 24);
            this.edtStatusAlt.TabIndex = 14;
            // 
            // edtWVCode
            // 
            this.edtWVCode.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.edtWVCode.DataMember = "WVCode";
            this.edtWVCode.DataSource = this.qryKbWVEinzelposten;
            this.edtWVCode.EditMode = Kiss.Interfaces.UI.EditModeType.ReadOnly;
            this.edtWVCode.Location = new System.Drawing.Point(132, 317);
            this.edtWVCode.Name = "edtWVCode";
            this.edtWVCode.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.edtWVCode.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtWVCode.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtWVCode.Properties.Appearance.Options.UseBackColor = true;
            this.edtWVCode.Properties.Appearance.Options.UseBorderColor = true;
            this.edtWVCode.Properties.Appearance.Options.UseFont = true;
            this.edtWVCode.Properties.AppearanceDropDown.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.edtWVCode.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.edtWVCode.Properties.AppearanceDropDown.Options.UseBackColor = true;
            this.edtWVCode.Properties.AppearanceDropDown.Options.UseFont = true;
            this.edtWVCode.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject2.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject2.Options.UseBackColor = true;
            this.edtWVCode.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo, "", -1, true, true, false, DevExpress.Utils.HorzAlignment.Center, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject2)});
            this.edtWVCode.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtWVCode.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Text")});
            this.edtWVCode.Properties.DisplayMember = "Text";
            this.edtWVCode.Properties.NullText = "";
            this.edtWVCode.Properties.ReadOnly = true;
            this.edtWVCode.Properties.ShowFooter = false;
            this.edtWVCode.Properties.ShowHeader = false;
            this.edtWVCode.Properties.ValueMember = "Code";
            this.edtWVCode.Size = new System.Drawing.Size(372, 24);
            this.edtWVCode.TabIndex = 14;
            // 
            // edtUT
            // 
            this.edtUT.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.edtUT.DataMember = "UT";
            this.edtUT.DataSource = this.qryKbWVEinzelposten;
            this.edtUT.EditMode = Kiss.Interfaces.UI.EditModeType.ReadOnly;
            this.edtUT.Location = new System.Drawing.Point(132, 377);
            this.edtUT.Name = "edtUT";
            this.edtUT.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.edtUT.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtUT.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtUT.Properties.Appearance.Options.UseBackColor = true;
            this.edtUT.Properties.Appearance.Options.UseBorderColor = true;
            this.edtUT.Properties.Appearance.Options.UseFont = true;
            this.edtUT.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtUT.Properties.ReadOnly = true;
            this.edtUT.Size = new System.Drawing.Size(372, 24);
            this.edtUT.TabIndex = 15;
            // 
            // kissTextEdit1
            // 
            this.kissTextEdit1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.kissTextEdit1.DataMember = "Beguenstigter";
            this.kissTextEdit1.DataSource = this.qryKbWVEinzelposten;
            this.kissTextEdit1.EditMode = Kiss.Interfaces.UI.EditModeType.ReadOnly;
            this.kissTextEdit1.Location = new System.Drawing.Point(132, 407);
            this.kissTextEdit1.Name = "kissTextEdit1";
            this.kissTextEdit1.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.kissTextEdit1.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.kissTextEdit1.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.kissTextEdit1.Properties.Appearance.Options.UseBackColor = true;
            this.kissTextEdit1.Properties.Appearance.Options.UseBorderColor = true;
            this.kissTextEdit1.Properties.Appearance.Options.UseFont = true;
            this.kissTextEdit1.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.kissTextEdit1.Properties.ReadOnly = true;
            this.kissTextEdit1.Size = new System.Drawing.Size(372, 24);
            this.kissTextEdit1.TabIndex = 15;
            // 
            // kissLabel7
            // 
            this.kissLabel7.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.kissLabel7.Location = new System.Drawing.Point(3, 437);
            this.kissLabel7.Name = "kissLabel7";
            this.kissLabel7.Size = new System.Drawing.Size(100, 23);
            this.kissLabel7.TabIndex = 339;
            this.kissLabel7.Text = "Periode";
            this.kissLabel7.UseCompatibleTextRendering = true;
            // 
            // kissLabel8
            // 
            this.kissLabel8.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.kissLabel8.Location = new System.Drawing.Point(242, 257);
            this.kissLabel8.Name = "kissLabel8";
            this.kissLabel8.Size = new System.Drawing.Size(76, 24);
            this.kissLabel8.TabIndex = 343;
            this.kissLabel8.Text = "Neuer Status";
            this.kissLabel8.UseCompatibleTextRendering = true;
            // 
            // edtStatus
            // 
            this.edtStatus.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.edtStatus.Location = new System.Drawing.Point(313, 257);
            this.edtStatus.Name = "edtStatus";
            this.edtStatus.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtStatus.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtStatus.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtStatus.Properties.Appearance.Options.UseBackColor = true;
            this.edtStatus.Properties.Appearance.Options.UseBorderColor = true;
            this.edtStatus.Properties.Appearance.Options.UseFont = true;
            this.edtStatus.Properties.AppearanceDropDown.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.edtStatus.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.edtStatus.Properties.AppearanceDropDown.Options.UseBackColor = true;
            this.edtStatus.Properties.AppearanceDropDown.Options.UseFont = true;
            this.edtStatus.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject1.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject1.Options.UseBackColor = true;
            this.edtStatus.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo, "", -1, true, true, false, DevExpress.Utils.HorzAlignment.Center, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject1)});
            this.edtStatus.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtStatus.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Text")});
            this.edtStatus.Properties.DisplayMember = "Text";
            this.edtStatus.Properties.NullText = "";
            this.edtStatus.Properties.ShowFooter = false;
            this.edtStatus.Properties.ShowHeader = false;
            this.edtStatus.Properties.ValueMember = "Code";
            this.edtStatus.Size = new System.Drawing.Size(262, 24);
            this.edtStatus.TabIndex = 344;
            // 
            // btnStatusSetzen
            // 
            this.btnStatusSetzen.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnStatusSetzen.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStatusSetzen.Location = new System.Drawing.Point(581, 257);
            this.btnStatusSetzen.Name = "btnStatusSetzen";
            this.btnStatusSetzen.Size = new System.Drawing.Size(94, 24);
            this.btnStatusSetzen.TabIndex = 345;
            this.btnStatusSetzen.Text = "Status setzen";
            this.btnStatusSetzen.UseCompatibleTextRendering = true;
            this.btnStatusSetzen.UseVisualStyleBackColor = false;
            this.btnStatusSetzen.Click += new System.EventHandler(this.btnStatusSetzen_Click);
            // 
            // btnKeine
            // 
            this.btnKeine.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnKeine.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnKeine.Location = new System.Drawing.Point(736, 257);
            this.btnKeine.Name = "btnKeine";
            this.btnKeine.Size = new System.Drawing.Size(49, 24);
            this.btnKeine.TabIndex = 346;
            this.btnKeine.Text = "Keine";
            this.btnKeine.UseCompatibleTextRendering = true;
            this.btnKeine.UseVisualStyleBackColor = false;
            this.btnKeine.Click += new System.EventHandler(this.btnKeine_Click);
            // 
            // btnAlle
            // 
            this.btnAlle.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAlle.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAlle.Location = new System.Drawing.Point(681, 257);
            this.btnAlle.Name = "btnAlle";
            this.btnAlle.Size = new System.Drawing.Size(49, 24);
            this.btnAlle.TabIndex = 347;
            this.btnAlle.Text = "Alle";
            this.btnAlle.UseCompatibleTextRendering = true;
            this.btnAlle.UseVisualStyleBackColor = false;
            this.btnAlle.Click += new System.EventHandler(this.btnAlle_Click);
            // 
            // edtPeriode
            // 
            this.edtPeriode.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.edtPeriode.DataMember = "Periode";
            this.edtPeriode.DataSource = this.qryKbWVEinzelposten;
            this.edtPeriode.EditMode = Kiss.Interfaces.UI.EditModeType.ReadOnly;
            this.edtPeriode.Location = new System.Drawing.Point(132, 438);
            this.edtPeriode.Name = "edtPeriode";
            this.edtPeriode.Properties.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(239)))), ((int)(((byte)(231)))));
            this.edtPeriode.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtPeriode.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtPeriode.Properties.Appearance.Options.UseBackColor = true;
            this.edtPeriode.Properties.Appearance.Options.UseBorderColor = true;
            this.edtPeriode.Properties.Appearance.Options.UseFont = true;
            this.edtPeriode.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtPeriode.Properties.ReadOnly = true;
            this.edtPeriode.Size = new System.Drawing.Size(372, 24);
            this.edtPeriode.TabIndex = 348;
            // 
            // lblTotalSelektierteUndBetrag
            // 
            this.lblTotalSelektierteUndBetrag.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lblTotalSelektierteUndBetrag.LabelStyle = KiSS4.Gui.LabelStyleType.DataView;
            this.lblTotalSelektierteUndBetrag.Location = new System.Drawing.Point(208, 3);
            this.lblTotalSelektierteUndBetrag.Name = "lblTotalSelektierteUndBetrag";
            this.lblTotalSelektierteUndBetrag.Size = new System.Drawing.Size(573, 16);
            this.lblTotalSelektierteUndBetrag.TabIndex = 349;
            this.lblTotalSelektierteUndBetrag.Text = "Keine Belege selektiert";
            this.lblTotalSelektierteUndBetrag.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblTotalSelektierteUndBetrag.UseCompatibleTextRendering = true;
            // 
            // btnStornoVerstecken
            // 
            this.btnStornoVerstecken.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnStornoVerstecken.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStornoVerstecken.Location = new System.Drawing.Point(581, 288);
            this.btnStornoVerstecken.Name = "btnStornoVerstecken";
            this.btnStornoVerstecken.Size = new System.Drawing.Size(204, 24);
            this.btnStornoVerstecken.TabIndex = 350;
            this.btnStornoVerstecken.Text = "Selektierte Status S ausblenden";
            this.btnStornoVerstecken.UseCompatibleTextRendering = true;
            this.btnStornoVerstecken.UseVisualStyleBackColor = false;
            this.btnStornoVerstecken.Click += new System.EventHandler(this.btnStornoVerstecken_Click);
            // 
            // lblBED
            // 
            this.lblBED.Location = new System.Drawing.Point(5, 40);
            this.lblBED.Name = "lblBED";
            this.lblBED.Size = new System.Drawing.Size(100, 23);
            this.lblBED.TabIndex = 9;
            this.lblBED.Text = "BED";
            this.lblBED.UseCompatibleTextRendering = true;
            // 
            // lblWVCode
            // 
            this.lblWVCode.Location = new System.Drawing.Point(5, 70);
            this.lblWVCode.Name = "lblWVCode";
            this.lblWVCode.Size = new System.Drawing.Size(100, 23);
            this.lblWVCode.TabIndex = 10;
            this.lblWVCode.Text = "WV-Code";
            this.lblWVCode.UseCompatibleTextRendering = true;
            // 
            // lblUT
            // 
            this.lblUT.Location = new System.Drawing.Point(5, 99);
            this.lblUT.Name = "lblUT";
            this.lblUT.Size = new System.Drawing.Size(123, 24);
            this.lblUT.TabIndex = 11;
            this.lblUT.Text = "Unterstützungsträger";
            this.lblUT.UseCompatibleTextRendering = true;
            // 
            // lblStatus
            // 
            this.lblStatus.Location = new System.Drawing.Point(5, 159);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(123, 24);
            this.lblStatus.TabIndex = 12;
            this.lblStatus.Text = "Status";
            this.lblStatus.UseCompatibleTextRendering = true;
            // 
            // lblUTID
            // 
            this.lblUTID.Location = new System.Drawing.Point(5, 129);
            this.lblUTID.Name = "lblUTID";
            this.lblUTID.Size = new System.Drawing.Size(123, 24);
            this.lblUTID.TabIndex = 12;
            this.lblUTID.Text = "UT (P-Nr.)";
            this.lblUTID.UseCompatibleTextRendering = true;
            // 
            // edtSearchBED
            // 
            this.edtSearchBED.Location = new System.Drawing.Point(134, 39);
            this.edtSearchBED.Name = "edtSearchBED";
            this.edtSearchBED.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtSearchBED.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtSearchBED.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchBED.Properties.Appearance.Options.UseBackColor = true;
            this.edtSearchBED.Properties.Appearance.Options.UseBorderColor = true;
            this.edtSearchBED.Properties.Appearance.Options.UseFont = true;
            this.edtSearchBED.Properties.AppearanceDropDown.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.edtSearchBED.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchBED.Properties.AppearanceDropDown.Options.UseBackColor = true;
            this.edtSearchBED.Properties.AppearanceDropDown.Options.UseFont = true;
            this.edtSearchBED.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject8.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject8.Options.UseBackColor = true;
            this.edtSearchBED.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo, "", -1, true, true, false, DevExpress.Utils.HorzAlignment.Center, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject8)});
            this.edtSearchBED.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtSearchBED.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Text")});
            this.edtSearchBED.Properties.DisplayMember = "Text";
            this.edtSearchBED.Properties.NullText = "";
            this.edtSearchBED.Properties.ShowFooter = false;
            this.edtSearchBED.Properties.ShowHeader = false;
            this.edtSearchBED.Properties.ValueMember = "Code";
            this.edtSearchBED.Size = new System.Drawing.Size(283, 24);
            this.edtSearchBED.TabIndex = 0;
            // 
            // edtSearchStatus
            // 
            this.edtSearchStatus.Location = new System.Drawing.Point(134, 159);
            this.edtSearchStatus.Name = "edtSearchStatus";
            this.edtSearchStatus.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtSearchStatus.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtSearchStatus.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchStatus.Properties.Appearance.Options.UseBackColor = true;
            this.edtSearchStatus.Properties.Appearance.Options.UseBorderColor = true;
            this.edtSearchStatus.Properties.Appearance.Options.UseFont = true;
            this.edtSearchStatus.Properties.AppearanceDropDown.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.edtSearchStatus.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchStatus.Properties.AppearanceDropDown.Options.UseBackColor = true;
            this.edtSearchStatus.Properties.AppearanceDropDown.Options.UseFont = true;
            this.edtSearchStatus.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject7.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject7.Options.UseBackColor = true;
            this.edtSearchStatus.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo, "", -1, true, true, false, DevExpress.Utils.HorzAlignment.Center, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject7)});
            this.edtSearchStatus.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtSearchStatus.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Text")});
            this.edtSearchStatus.Properties.DisplayMember = "Text";
            this.edtSearchStatus.Properties.NullText = "";
            this.edtSearchStatus.Properties.ShowFooter = false;
            this.edtSearchStatus.Properties.ShowHeader = false;
            this.edtSearchStatus.Properties.ValueMember = "Code";
            this.edtSearchStatus.Size = new System.Drawing.Size(283, 24);
            this.edtSearchStatus.TabIndex = 4;
            // 
            // edtSearchWVCode
            // 
            this.edtSearchWVCode.Location = new System.Drawing.Point(134, 69);
            this.edtSearchWVCode.Name = "edtSearchWVCode";
            this.edtSearchWVCode.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtSearchWVCode.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtSearchWVCode.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchWVCode.Properties.Appearance.Options.UseBackColor = true;
            this.edtSearchWVCode.Properties.Appearance.Options.UseBorderColor = true;
            this.edtSearchWVCode.Properties.Appearance.Options.UseFont = true;
            this.edtSearchWVCode.Properties.AppearanceDropDown.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.edtSearchWVCode.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchWVCode.Properties.AppearanceDropDown.Options.UseBackColor = true;
            this.edtSearchWVCode.Properties.AppearanceDropDown.Options.UseFont = true;
            this.edtSearchWVCode.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject6.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject6.Options.UseBackColor = true;
            this.edtSearchWVCode.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo, "", -1, true, true, false, DevExpress.Utils.HorzAlignment.Center, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject6)});
            this.edtSearchWVCode.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtSearchWVCode.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Text")});
            this.edtSearchWVCode.Properties.DisplayMember = "Text";
            this.edtSearchWVCode.Properties.NullText = "";
            this.edtSearchWVCode.Properties.ShowFooter = false;
            this.edtSearchWVCode.Properties.ShowHeader = false;
            this.edtSearchWVCode.Properties.ValueMember = "Code";
            this.edtSearchWVCode.Size = new System.Drawing.Size(283, 24);
            this.edtSearchWVCode.TabIndex = 1;
            // 
            // edtSearchUT
            // 
            this.edtSearchUT.Location = new System.Drawing.Point(134, 99);
            this.edtSearchUT.Name = "edtSearchUT";
            this.edtSearchUT.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtSearchUT.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtSearchUT.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchUT.Properties.Appearance.Options.UseBackColor = true;
            this.edtSearchUT.Properties.Appearance.Options.UseBorderColor = true;
            this.edtSearchUT.Properties.Appearance.Options.UseFont = true;
            this.edtSearchUT.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtSearchUT.Size = new System.Drawing.Size(283, 24);
            this.edtSearchUT.TabIndex = 2;
            // 
            // lblZeitspanne
            // 
            this.lblZeitspanne.Location = new System.Drawing.Point(5, 189);
            this.lblZeitspanne.Name = "lblZeitspanne";
            this.lblZeitspanne.Size = new System.Drawing.Size(100, 23);
            this.lblZeitspanne.TabIndex = 17;
            this.lblZeitspanne.Text = "Periode";
            this.lblZeitspanne.UseCompatibleTextRendering = true;
            // 
            // lblJahr
            // 
            this.lblJahr.Location = new System.Drawing.Point(300, 189);
            this.lblJahr.Name = "lblJahr";
            this.lblJahr.Size = new System.Drawing.Size(26, 24);
            this.lblJahr.TabIndex = 19;
            this.lblJahr.Text = "Jahr";
            this.lblJahr.UseCompatibleTextRendering = true;
            // 
            // lblFakturaNr
            // 
            this.lblFakturaNr.Location = new System.Drawing.Point(5, 220);
            this.lblFakturaNr.Name = "lblFakturaNr";
            this.lblFakturaNr.Size = new System.Drawing.Size(100, 23);
            this.lblFakturaNr.TabIndex = 21;
            this.lblFakturaNr.Text = "Faktura-Nr.";
            this.lblFakturaNr.UseCompatibleTextRendering = true;
            // 
            // edtSearchKbWVLaufID
            // 
            this.edtSearchKbWVLaufID.Location = new System.Drawing.Point(134, 220);
            this.edtSearchKbWVLaufID.Name = "edtSearchKbWVLaufID";
            this.edtSearchKbWVLaufID.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtSearchKbWVLaufID.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtSearchKbWVLaufID.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchKbWVLaufID.Properties.Appearance.Options.UseBackColor = true;
            this.edtSearchKbWVLaufID.Properties.Appearance.Options.UseBorderColor = true;
            this.edtSearchKbWVLaufID.Properties.Appearance.Options.UseFont = true;
            this.edtSearchKbWVLaufID.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtSearchKbWVLaufID.Size = new System.Drawing.Size(108, 24);
            this.edtSearchKbWVLaufID.TabIndex = 7;
            // 
            // edtUTBaPersonID
            // 
            this.edtUTBaPersonID.Location = new System.Drawing.Point(134, 129);
            this.edtUTBaPersonID.Name = "edtUTBaPersonID";
            this.edtUTBaPersonID.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
            this.edtUTBaPersonID.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtUTBaPersonID.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtUTBaPersonID.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtUTBaPersonID.Properties.Appearance.Options.UseBackColor = true;
            this.edtUTBaPersonID.Properties.Appearance.Options.UseBorderColor = true;
            this.edtUTBaPersonID.Properties.Appearance.Options.UseFont = true;
            this.edtUTBaPersonID.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtUTBaPersonID.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtUTBaPersonID.Size = new System.Drawing.Size(283, 24);
            this.edtUTBaPersonID.TabIndex = 3;
            // 
            // edtSearchPeriod
            // 
            this.edtSearchPeriod.Location = new System.Drawing.Point(134, 190);
            this.edtSearchPeriod.Name = "edtSearchPeriod";
            this.edtSearchPeriod.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtSearchPeriod.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtSearchPeriod.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchPeriod.Properties.Appearance.Options.UseBackColor = true;
            this.edtSearchPeriod.Properties.Appearance.Options.UseBorderColor = true;
            this.edtSearchPeriod.Properties.Appearance.Options.UseFont = true;
            this.edtSearchPeriod.Properties.AppearanceDropDown.BackColor = System.Drawing.Color.BlanchedAlmond;
            this.edtSearchPeriod.Properties.AppearanceDropDown.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchPeriod.Properties.AppearanceDropDown.Options.UseBackColor = true;
            this.edtSearchPeriod.Properties.AppearanceDropDown.Options.UseFont = true;
            this.edtSearchPeriod.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            serializableAppearanceObject5.BackColor = System.Drawing.Color.Bisque;
            serializableAppearanceObject5.Options.UseBackColor = true;
            this.edtSearchPeriod.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo, "", -1, true, true, false, DevExpress.Utils.HorzAlignment.Center, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject5)});
            this.edtSearchPeriod.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtSearchPeriod.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Text")});
            this.edtSearchPeriod.Properties.DisplayMember = "Text";
            this.edtSearchPeriod.Properties.NullText = "";
            this.edtSearchPeriod.Properties.ShowFooter = false;
            this.edtSearchPeriod.Properties.ShowHeader = false;
            this.edtSearchPeriod.Properties.ValueMember = "Code";
            this.edtSearchPeriod.Size = new System.Drawing.Size(160, 24);
            this.edtSearchPeriod.TabIndex = 5;
            // 
            // edtSearchJahr
            // 
            this.edtSearchJahr.Location = new System.Drawing.Point(332, 190);
            this.edtSearchJahr.Name = "edtSearchJahr";
            this.edtSearchJahr.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
            this.edtSearchJahr.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtSearchJahr.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtSearchJahr.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtSearchJahr.Properties.Appearance.Options.UseBackColor = true;
            this.edtSearchJahr.Properties.Appearance.Options.UseBorderColor = true;
            this.edtSearchJahr.Properties.Appearance.Options.UseFont = true;
            this.edtSearchJahr.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtSearchJahr.Properties.ButtonsStyle = DevExpress.XtraEditors.Controls.BorderStyles.UltraFlat;
            this.edtSearchJahr.Size = new System.Drawing.Size(85, 24);
            this.edtSearchJahr.TabIndex = 6;
            // 
            // kissLabel6
            // 
            this.kissLabel6.Location = new System.Drawing.Point(5, 250);
            this.kissLabel6.Name = "kissLabel6";
            this.kissLabel6.Size = new System.Drawing.Size(123, 24);
            this.kissLabel6.TabIndex = 27;
            this.kissLabel6.Text = "PSCD Belegnummer";
            this.kissLabel6.UseCompatibleTextRendering = true;
            // 
            // edtPscdBelegNr
            // 
            this.edtPscdBelegNr.Location = new System.Drawing.Point(134, 250);
            this.edtPscdBelegNr.Name = "edtPscdBelegNr";
            this.edtPscdBelegNr.Properties.Appearance.BackColor = System.Drawing.Color.AliceBlue;
            this.edtPscdBelegNr.Properties.Appearance.BorderColor = System.Drawing.Color.Linen;
            this.edtPscdBelegNr.Properties.Appearance.Font = new System.Drawing.Font("Arial", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.edtPscdBelegNr.Properties.Appearance.Options.UseBackColor = true;
            this.edtPscdBelegNr.Properties.Appearance.Options.UseBorderColor = true;
            this.edtPscdBelegNr.Properties.Appearance.Options.UseFont = true;
            this.edtPscdBelegNr.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.HotFlat;
            this.edtPscdBelegNr.Size = new System.Drawing.Size(108, 24);
            this.edtPscdBelegNr.TabIndex = 8;
            // 
            // CtlKbWVEinzelposten
            // 
            this.ActiveSQLQuery = this.qryKbWVEinzelposten;
            this.Name = "CtlKbWVEinzelposten";
            this.tabControlSearch.ResumeLayout(false);
            this.tpgListe.ResumeLayout(false);
            this.tpgSuchen.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdWVEinzelposten)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.qryKbWVEinzelposten)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grvKbWVEinzelposten)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemCheckEdit1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtBED.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtBED)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtStatusAlt.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtStatusAlt)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtWVCode.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtWVCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtUT.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissTextEdit1.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtStatus.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtStatus)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtPeriode.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblTotalSelektierteUndBetrag)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblBED)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblWVCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblUT)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblStatus)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblUTID)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchBED.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchBED)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchStatus.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchStatus)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchWVCode.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchWVCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchUT.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblZeitspanne)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblJahr)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lblFakturaNr)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchKbWVLaufID.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtUTBaPersonID.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchPeriod.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchPeriod)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtSearchJahr.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kissLabel6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.edtPscdBelegNr.Properties)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        #region Dispose

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if ((components != null))
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #endregion

        #region Private Methods

        private void SelectionChanged()
        {
            bool allowStatusEdit = true;
            bool allowStornoVerstecken = true;
            Decimal selTotal = 0;
            int selAnzahl = 0;
            foreach(DataRow row in qryKbWVEinzelposten.DataTable.Rows)
            {
                if( (bool)row["Sel"] )
                {
                    selTotal = selTotal + (Decimal)row["Betrag"];
                    selAnzahl++;

                    if( ((int)row["KbWVEinzelpostenStatusCode"] != 5 /*Abgesetzt - in Abklärung*/)
                        && ((int)row["KbWVEinzelpostenStatusCode"] != 6 /*nicht weiterverechenbar*/)
                        && ((int)row["KbWVEinzelpostenStatusCode"] != 7 /*storniert*/)
                       )
                    {
                        allowStatusEdit = false;
                    }

                    if ((int)row["KbWVEinzelpostenStatusCode"] != 7 /*storniert*/)
                    {
                        // Mind. ein selektierte WV-EP ist nicht im Status 7
                        allowStornoVerstecken = false;
                    }
                }
            }

            if (selAnzahl > 0)
            {
                lblTotalSelektierteUndBetrag.Text = "Selektierte Belege: " + selAnzahl + ", Betragstotal = " + selTotal.ToString("C");
            }
            else
            {
                allowStatusEdit = false;
                allowStornoVerstecken = false;
                lblTotalSelektierteUndBetrag.Text = "Keine Belege selektiert";
            }

            btnStornoVerstecken.Enabled = allowStornoVerstecken;

            edtStatus.EditMode = allowStatusEdit ? EditModeType.Normal : EditModeType.ReadOnly;
            btnStatusSetzen.Enabled = allowStatusEdit;
            if(!allowStatusEdit){edtStatus.EditValue = null;}
        }

        private void SelectionChanging(object sender, DevExpress.XtraEditors.Controls.ChangingEventArgs e)
        {
            qryKbWVEinzelposten.Row["Sel"] = e.NewValue;

            SelectionChanged();
        }

        private void btnAlle_Click(object sender, System.EventArgs e)
        {
            foreach(DataRow row in qryKbWVEinzelposten.DataTable.Rows)
            {
                row["Sel"] = true;
            }
            SelectionChanging(null,new DevExpress.XtraEditors.Controls.ChangingEventArgs(false,true));
        }

        private void btnKeine_Click(object sender, System.EventArgs e)
        {
            foreach(DataRow row in qryKbWVEinzelposten.DataTable.Rows)
            {
                row["Sel"] = false;
            }
            SelectionChanging(null,new DevExpress.XtraEditors.Controls.ChangingEventArgs(true, false));
        }

        private void btnStatusSetzen_Click(object sender, System.EventArgs e)
        {
            if( edtStatus.EditValue == DBNull.Value || edtStatus.EditValue == null )
            {
                KissMsg.ShowError("CtlKbWVEinzelposten","StatusLeer","Bitte Status auswählen");
                return;
            }

            List<int> ids = new List<int>();

            foreach(DataRow row in qryKbWVEinzelposten.DataTable.Rows)
            {
                if( (bool)row["Sel"] )
                {
                    ids.Add((int)row["KbWVEinzelpostenID"]);
                }
            }

            DBUtil.ExecSQLThrowingException(string.Format(@"
              UPDATE KbWVEinzelposten
              SET KbWVEinzelpostenStatusCode = {1}
              WHERE KbWVEinzelpostenID IN ({0})", string.Join(",", ids.ConvertAll<string>(Convert.ToString).ToArray()),edtStatus.EditValue));

            qryKbWVEinzelposten.Refresh();

            edtStatus.EditValue = null;
            edtStatus.EditMode = EditModeType.ReadOnly;
            btnStatusSetzen.Enabled = false;
        }

        private void btnStornoVerstecken_Click(object sender, System.EventArgs e)
        {
            if (KissMsg.ShowQuestion("Sollen die selektierten WV-EPs mit Status S ausgeblendet werden? Achtung: Falls ja, sind diese WV-EPs nicht mehr aufrufbar!"))
            {
                // OK, verstecke die selektierten WV-EPs mit Status S
                List<int> ids = new List<int>();

                foreach(DataRow row in qryKbWVEinzelposten.DataTable.Rows)
                {
                    if( (bool)row["Sel"] && (int)row["KbWVEinzelpostenStatusCode"] == 7 /*storniert*/)
                    {
                        ids.Add((int)row["KbWVEinzelpostenID"]);
                    }
                }

                DBUtil.ExecSQLThrowingException(string.Format(@"
                  UPDATE KbWVEinzelposten
                  SET KbWVEinzelpostenStatusCode = 700 -- 700 => Storniert versteckt (hidden) 'H'
                  WHERE KbWVEinzelpostenID IN ({0})", string.Join(",", ids.ConvertAll<string>(Convert.ToString).ToArray()),edtStatus.EditValue));

                qryKbWVEinzelposten.Refresh();

                SelectionChanged();
            }
        }

        private void qryKbWVEinzelposten_PositionChanged(object sender, System.EventArgs e)
        {
            //int status = (int)qryKbWVEinzelposten["KbWVEinzelpostenStatusCode"];
            //edtStatus.EditMode = (status == 5 /*Abgesetzt - in Abklärung*/) ? EditModeType.Normal : EditModeType.ReadOnly;
        }

        private void tabControlSearch_SelectedTabChanged(SharpLibrary.WinControls.TabPageEx page)
        {
            //Bei jeder neuen Suche, initialisieren
            edtStatus.EditValue = null;
            edtStatus.EditMode = EditModeType.ReadOnly;
            btnStatusSetzen.Enabled = false;
            SelectionChanged();
        }

        #endregion
    }
}