CREATE TABLE [dbo].[FaFallPerson](
	[FaFallPersonID] [int] IDENTITY(1,1) NOT NULL,
	[FaFallID] [int] NOT NULL,
	[BaPersonID] [int] NOT NULL,
	[DatumVon] [datetime] NULL,
	[DatumBis] [datetime] NULL,
	[FaFallPersonTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_FaFallPerson] PRIMARY KEY CLUSTERED 
(
	[FaFallPersonID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Index [IX_FaFallPerson_BaPersonID]    Script Date: 11/23/2011 14:57:29 ******/
CREATE NONCLUSTERED INDEX [IX_FaFallPerson_BaPersonID] ON [dbo].[FaFallPerson] 
(
	[BaPersonID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

/****** Object:  Index [IX_FaFallPerson_FaFallID]    Script Date: 11/23/2011 14:57:29 ******/
CREATE NONCLUSTERED INDEX [IX_FaFallPerson_FaFallID] ON [dbo].[FaFallPerson] 
(
	[FaFallID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

/****** Object:  Index [IX_FaFallPerson_Sicherung]    Script Date: 11/23/2011 14:57:29 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_FaFallPerson_Sicherung] ON [dbo].[FaFallPerson] 
(
	[FaFallID] ASC,
	[BaPersonID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FaFallPerson]  WITH CHECK ADD  CONSTRAINT [FK_FaFall_Person_BaPerson] FOREIGN KEY([BaPersonID])
REFERENCES [dbo].[BaPerson] ([BaPersonID])
GO
ALTER TABLE [dbo].[FaFallPerson] CHECK CONSTRAINT [FK_FaFall_Person_BaPerson]
GO
ALTER TABLE [dbo].[FaFallPerson]  WITH CHECK ADD  CONSTRAINT [FK_FaFall_Person_FaFall] FOREIGN KEY([FaFallID])
REFERENCES [dbo].[FaFall] ([FaFallID])
GO
ALTER TABLE [dbo].[FaFallPerson] CHECK CONSTRAINT [FK_FaFall_Person_FaFall]