CREATE TABLE [dbo].[FaFall](
	[FaFallID] [int] IDENTITY(1,1) NOT NULL,
	[BaPersonID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[DatumVon] [datetime] NOT NULL,
	[DatumBis] [datetime] NULL,
	[Bemerkung] [text] NULL,
	[FaFallTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_FaFall] PRIMARY KEY CLUSTERED 
(
	[FaFallID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


/****** Object:  Index [IX_FaFall_BaPersonID_UserID]    Script Date: 03/22/2012 11:11:24 ******/
CREATE NONCLUSTERED INDEX [IX_FaFall_BaPersonID_UserID] ON [dbo].[FaFall] 
(
	[BaPersonID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
GO


/****** Object:  Index [IX_FaFall_FaFallID_BaPersonID_UserID]    Script Date: 03/22/2012 11:11:24 ******/
CREATE NONCLUSTERED INDEX [IX_FaFall_FaFallID_BaPersonID_UserID] ON [dbo].[FaFall] 
(
	[FaFallID] ASC,
	[BaPersonID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
GO


/****** Object:  Index [IX_FaFall_BaPersonID]    Script Date: 03/22/2012 11:11:24 ******/
CREATE NONCLUSTERED INDEX [IX_FaFall_BaPersonID] ON [dbo].[FaFall] 
(
	[BaPersonID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
GO


/****** Object:  Index [IX_FaFall_BaPersonID_DatumVon]    Script Date: 03/22/2012 11:11:24 ******/
CREATE NONCLUSTERED INDEX [IX_FaFall_BaPersonID_DatumVon] ON [dbo].[FaFall] 
(
	[BaPersonID] ASC,
	[DatumVon] DESC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
GO


/****** Object:  Index [IX_FaFall_UserID]    Script Date: 03/22/2012 11:11:24 ******/
CREATE NONCLUSTERED INDEX [IX_FaFall_UserID] ON [dbo].[FaFall] 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FaFall]  WITH CHECK ADD  CONSTRAINT [FK_FaFall_BaPerson] FOREIGN KEY([BaPersonID])
REFERENCES [dbo].[BaPerson] ([BaPersonID])
GO

ALTER TABLE [dbo].[FaFall] CHECK CONSTRAINT [FK_FaFall_BaPerson]
GO

ALTER TABLE [dbo].[FaFall]  WITH CHECK ADD  CONSTRAINT [FK_FaFall_XUser] FOREIGN KEY([UserID])
REFERENCES [dbo].[XUser] ([UserID])
GO

ALTER TABLE [dbo].[FaFall] CHECK CONSTRAINT [FK_FaFall_XUser]
GO

ALTER TABLE [dbo].[FaFall] ADD  CONSTRAINT [DF_FaFall_DatumEroeffnet]  DEFAULT (getdate()) FOR [DatumVon]
GO

