//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace KiSS4.FAMOZ.PSCDSvcWebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PSCDSvcSoap", Namespace="http://www.born.ch/KiSS/FAMOZ/PSCD/")]
    public partial class PSCDSvc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateAndSubmitBusinessPartnerPersonDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAndSubmitBusinessPartnerInstitutionDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitWhBelegeByIDsOperationCompleted;
        
        private System.Threading.SendOrPostCallback StornoNettoBelegeOperationCompleted;
        
        private System.Threading.SendOrPostCallback StornoBruttoBelegeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitAlimBelegeByIDsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitKgBelegeOperationCompleted;
        
        private System.Threading.SendOrPostCallback StornoKgBelegeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitWVEinzelpostenByIDsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearCacheOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PSCDSvc() {
            this.Url = global::KiSS4.FAMOZ.Properties.Settings.Default.KiSS4_FAMOZ_PSCDSvcWebReference_PSCDSvc;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateAndSubmitBusinessPartnerPersonDataCompletedEventHandler CreateAndSubmitBusinessPartnerPersonDataCompleted;
        
        /// <remarks/>
        public event CreateAndSubmitBusinessPartnerInstitutionDataCompletedEventHandler CreateAndSubmitBusinessPartnerInstitutionDataCompleted;
        
        /// <remarks/>
        public event SubmitWhBelegeByIDsCompletedEventHandler SubmitWhBelegeByIDsCompleted;
        
        /// <remarks/>
        public event StornoNettoBelegeCompletedEventHandler StornoNettoBelegeCompleted;
        
        /// <remarks/>
        public event StornoBruttoBelegeCompletedEventHandler StornoBruttoBelegeCompleted;
        
        /// <remarks/>
        public event SubmitAlimBelegeByIDsCompletedEventHandler SubmitAlimBelegeByIDsCompleted;
        
        /// <remarks/>
        public event SubmitKgBelegeCompletedEventHandler SubmitKgBelegeCompleted;
        
        /// <remarks/>
        public event StornoKgBelegeCompletedEventHandler StornoKgBelegeCompleted;
        
        /// <remarks/>
        public event SubmitWVEinzelpostenByIDsCompletedEventHandler SubmitWVEinzelpostenByIDsCompleted;
        
        /// <remarks/>
        public event ClearCacheCompletedEventHandler ClearCacheCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.born.ch/KiSS/FAMOZ/PSCD/CreateAndSubmitBusinessPartnerPersonData", RequestNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", ResponseNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnMsg CreateAndSubmitBusinessPartnerPersonData(string dbName, int userIDSender, string userWinLogonName, int baPersonID) {
            object[] results = this.Invoke("CreateAndSubmitBusinessPartnerPersonData", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        baPersonID});
            return ((ReturnMsg)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAndSubmitBusinessPartnerPersonDataAsync(string dbName, int userIDSender, string userWinLogonName, int baPersonID) {
            this.CreateAndSubmitBusinessPartnerPersonDataAsync(dbName, userIDSender, userWinLogonName, baPersonID, null);
        }
        
        /// <remarks/>
        public void CreateAndSubmitBusinessPartnerPersonDataAsync(string dbName, int userIDSender, string userWinLogonName, int baPersonID, object userState) {
            if ((this.CreateAndSubmitBusinessPartnerPersonDataOperationCompleted == null)) {
                this.CreateAndSubmitBusinessPartnerPersonDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAndSubmitBusinessPartnerPersonDataOperationCompleted);
            }
            this.InvokeAsync("CreateAndSubmitBusinessPartnerPersonData", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        baPersonID}, this.CreateAndSubmitBusinessPartnerPersonDataOperationCompleted, userState);
        }
        
        private void OnCreateAndSubmitBusinessPartnerPersonDataOperationCompleted(object arg) {
            if ((this.CreateAndSubmitBusinessPartnerPersonDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAndSubmitBusinessPartnerPersonDataCompleted(this, new CreateAndSubmitBusinessPartnerPersonDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.born.ch/KiSS/FAMOZ/PSCD/CreateAndSubmitBusinessPartnerInstitutionData", RequestNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", ResponseNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnMsg CreateAndSubmitBusinessPartnerInstitutionData(string dbName, int userIDSender, string userWinLogonName, int baInstitutionID) {
            object[] results = this.Invoke("CreateAndSubmitBusinessPartnerInstitutionData", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        baInstitutionID});
            return ((ReturnMsg)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAndSubmitBusinessPartnerInstitutionDataAsync(string dbName, int userIDSender, string userWinLogonName, int baInstitutionID) {
            this.CreateAndSubmitBusinessPartnerInstitutionDataAsync(dbName, userIDSender, userWinLogonName, baInstitutionID, null);
        }
        
        /// <remarks/>
        public void CreateAndSubmitBusinessPartnerInstitutionDataAsync(string dbName, int userIDSender, string userWinLogonName, int baInstitutionID, object userState) {
            if ((this.CreateAndSubmitBusinessPartnerInstitutionDataOperationCompleted == null)) {
                this.CreateAndSubmitBusinessPartnerInstitutionDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAndSubmitBusinessPartnerInstitutionDataOperationCompleted);
            }
            this.InvokeAsync("CreateAndSubmitBusinessPartnerInstitutionData", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        baInstitutionID}, this.CreateAndSubmitBusinessPartnerInstitutionDataOperationCompleted, userState);
        }
        
        private void OnCreateAndSubmitBusinessPartnerInstitutionDataOperationCompleted(object arg) {
            if ((this.CreateAndSubmitBusinessPartnerInstitutionDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAndSubmitBusinessPartnerInstitutionDataCompleted(this, new CreateAndSubmitBusinessPartnerInstitutionDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.born.ch/KiSS/FAMOZ/PSCD/SubmitWhBelegeByIDs", RequestNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", ResponseNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnMsg SubmitWhBelegeByIDs(string dbName, int userIDSender, string userWinLogonName, int[] kbBuchungIDs, int[] kbBuchungBruttoIDs) {
            object[] results = this.Invoke("SubmitWhBelegeByIDs", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        kbBuchungIDs,
                        kbBuchungBruttoIDs});
            return ((ReturnMsg)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitWhBelegeByIDsAsync(string dbName, int userIDSender, string userWinLogonName, int[] kbBuchungIDs, int[] kbBuchungBruttoIDs) {
            this.SubmitWhBelegeByIDsAsync(dbName, userIDSender, userWinLogonName, kbBuchungIDs, kbBuchungBruttoIDs, null);
        }
        
        /// <remarks/>
        public void SubmitWhBelegeByIDsAsync(string dbName, int userIDSender, string userWinLogonName, int[] kbBuchungIDs, int[] kbBuchungBruttoIDs, object userState) {
            if ((this.SubmitWhBelegeByIDsOperationCompleted == null)) {
                this.SubmitWhBelegeByIDsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitWhBelegeByIDsOperationCompleted);
            }
            this.InvokeAsync("SubmitWhBelegeByIDs", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        kbBuchungIDs,
                        kbBuchungBruttoIDs}, this.SubmitWhBelegeByIDsOperationCompleted, userState);
        }
        
        private void OnSubmitWhBelegeByIDsOperationCompleted(object arg) {
            if ((this.SubmitWhBelegeByIDsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitWhBelegeByIDsCompleted(this, new SubmitWhBelegeByIDsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.born.ch/KiSS/FAMOZ/PSCD/StornoNettoBelege", RequestNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", ResponseNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnMsg StornoNettoBelege(string dbName, int userIDSender, string userWinLogonName, int[] KbBuchungIDs, bool test) {
            object[] results = this.Invoke("StornoNettoBelege", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        KbBuchungIDs,
                        test});
            return ((ReturnMsg)(results[0]));
        }
        
        /// <remarks/>
        public void StornoNettoBelegeAsync(string dbName, int userIDSender, string userWinLogonName, int[] KbBuchungIDs, bool test) {
            this.StornoNettoBelegeAsync(dbName, userIDSender, userWinLogonName, KbBuchungIDs, test, null);
        }
        
        /// <remarks/>
        public void StornoNettoBelegeAsync(string dbName, int userIDSender, string userWinLogonName, int[] KbBuchungIDs, bool test, object userState) {
            if ((this.StornoNettoBelegeOperationCompleted == null)) {
                this.StornoNettoBelegeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStornoNettoBelegeOperationCompleted);
            }
            this.InvokeAsync("StornoNettoBelege", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        KbBuchungIDs,
                        test}, this.StornoNettoBelegeOperationCompleted, userState);
        }
        
        private void OnStornoNettoBelegeOperationCompleted(object arg) {
            if ((this.StornoNettoBelegeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StornoNettoBelegeCompleted(this, new StornoNettoBelegeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.born.ch/KiSS/FAMOZ/PSCD/StornoBruttoBelege", RequestNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", ResponseNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnMsg StornoBruttoBelege(string dbName, int userIDSender, string userWinLogonName, int[] KbBuchungBruttoIDs, bool test) {
            object[] results = this.Invoke("StornoBruttoBelege", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        KbBuchungBruttoIDs,
                        test});
            return ((ReturnMsg)(results[0]));
        }
        
        /// <remarks/>
        public void StornoBruttoBelegeAsync(string dbName, int userIDSender, string userWinLogonName, int[] KbBuchungBruttoIDs, bool test) {
            this.StornoBruttoBelegeAsync(dbName, userIDSender, userWinLogonName, KbBuchungBruttoIDs, test, null);
        }
        
        /// <remarks/>
        public void StornoBruttoBelegeAsync(string dbName, int userIDSender, string userWinLogonName, int[] KbBuchungBruttoIDs, bool test, object userState) {
            if ((this.StornoBruttoBelegeOperationCompleted == null)) {
                this.StornoBruttoBelegeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStornoBruttoBelegeOperationCompleted);
            }
            this.InvokeAsync("StornoBruttoBelege", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        KbBuchungBruttoIDs,
                        test}, this.StornoBruttoBelegeOperationCompleted, userState);
        }
        
        private void OnStornoBruttoBelegeOperationCompleted(object arg) {
            if ((this.StornoBruttoBelegeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StornoBruttoBelegeCompleted(this, new StornoBruttoBelegeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.born.ch/KiSS/FAMOZ/PSCD/SubmitAlimBelegeByIDs", RequestNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", ResponseNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnMsg SubmitAlimBelegeByIDs(string dbName, int userIDSender, string userWinLogonName, int[] kbBuchungIDs) {
            object[] results = this.Invoke("SubmitAlimBelegeByIDs", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        kbBuchungIDs});
            return ((ReturnMsg)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitAlimBelegeByIDsAsync(string dbName, int userIDSender, string userWinLogonName, int[] kbBuchungIDs) {
            this.SubmitAlimBelegeByIDsAsync(dbName, userIDSender, userWinLogonName, kbBuchungIDs, null);
        }
        
        /// <remarks/>
        public void SubmitAlimBelegeByIDsAsync(string dbName, int userIDSender, string userWinLogonName, int[] kbBuchungIDs, object userState) {
            if ((this.SubmitAlimBelegeByIDsOperationCompleted == null)) {
                this.SubmitAlimBelegeByIDsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitAlimBelegeByIDsOperationCompleted);
            }
            this.InvokeAsync("SubmitAlimBelegeByIDs", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        kbBuchungIDs}, this.SubmitAlimBelegeByIDsOperationCompleted, userState);
        }
        
        private void OnSubmitAlimBelegeByIDsOperationCompleted(object arg) {
            if ((this.SubmitAlimBelegeByIDsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitAlimBelegeByIDsCompleted(this, new SubmitAlimBelegeByIDsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.born.ch/KiSS/FAMOZ/PSCD/SubmitKgBelege", RequestNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", ResponseNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnMsg SubmitKgBelege(string dbName, int userIDSender, string userWinLogonName, int[] kgBuchungIDs) {
            object[] results = this.Invoke("SubmitKgBelege", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        kgBuchungIDs});
            return ((ReturnMsg)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitKgBelegeAsync(string dbName, int userIDSender, string userWinLogonName, int[] kgBuchungIDs) {
            this.SubmitKgBelegeAsync(dbName, userIDSender, userWinLogonName, kgBuchungIDs, null);
        }
        
        /// <remarks/>
        public void SubmitKgBelegeAsync(string dbName, int userIDSender, string userWinLogonName, int[] kgBuchungIDs, object userState) {
            if ((this.SubmitKgBelegeOperationCompleted == null)) {
                this.SubmitKgBelegeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitKgBelegeOperationCompleted);
            }
            this.InvokeAsync("SubmitKgBelege", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        kgBuchungIDs}, this.SubmitKgBelegeOperationCompleted, userState);
        }
        
        private void OnSubmitKgBelegeOperationCompleted(object arg) {
            if ((this.SubmitKgBelegeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitKgBelegeCompleted(this, new SubmitKgBelegeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.born.ch/KiSS/FAMOZ/PSCD/StornoKgBelege", RequestNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", ResponseNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnMsg StornoKgBelege(string dbName, int userIDSender, string userWinLogonName, int[] kgBuchungIDs) {
            object[] results = this.Invoke("StornoKgBelege", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        kgBuchungIDs});
            return ((ReturnMsg)(results[0]));
        }
        
        /// <remarks/>
        public void StornoKgBelegeAsync(string dbName, int userIDSender, string userWinLogonName, int[] kgBuchungIDs) {
            this.StornoKgBelegeAsync(dbName, userIDSender, userWinLogonName, kgBuchungIDs, null);
        }
        
        /// <remarks/>
        public void StornoKgBelegeAsync(string dbName, int userIDSender, string userWinLogonName, int[] kgBuchungIDs, object userState) {
            if ((this.StornoKgBelegeOperationCompleted == null)) {
                this.StornoKgBelegeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStornoKgBelegeOperationCompleted);
            }
            this.InvokeAsync("StornoKgBelege", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        kgBuchungIDs}, this.StornoKgBelegeOperationCompleted, userState);
        }
        
        private void OnStornoKgBelegeOperationCompleted(object arg) {
            if ((this.StornoKgBelegeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StornoKgBelegeCompleted(this, new StornoKgBelegeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.born.ch/KiSS/FAMOZ/PSCD/SubmitWVEinzelpostenByIDs", RequestNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", ResponseNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnMsg SubmitWVEinzelpostenByIDs(string dbName, int userIDSender, string userWinLogonName, int[] kbWVEinzelpostenIDs) {
            object[] results = this.Invoke("SubmitWVEinzelpostenByIDs", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        kbWVEinzelpostenIDs});
            return ((ReturnMsg)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitWVEinzelpostenByIDsAsync(string dbName, int userIDSender, string userWinLogonName, int[] kbWVEinzelpostenIDs) {
            this.SubmitWVEinzelpostenByIDsAsync(dbName, userIDSender, userWinLogonName, kbWVEinzelpostenIDs, null);
        }
        
        /// <remarks/>
        public void SubmitWVEinzelpostenByIDsAsync(string dbName, int userIDSender, string userWinLogonName, int[] kbWVEinzelpostenIDs, object userState) {
            if ((this.SubmitWVEinzelpostenByIDsOperationCompleted == null)) {
                this.SubmitWVEinzelpostenByIDsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitWVEinzelpostenByIDsOperationCompleted);
            }
            this.InvokeAsync("SubmitWVEinzelpostenByIDs", new object[] {
                        dbName,
                        userIDSender,
                        userWinLogonName,
                        kbWVEinzelpostenIDs}, this.SubmitWVEinzelpostenByIDsOperationCompleted, userState);
        }
        
        private void OnSubmitWVEinzelpostenByIDsOperationCompleted(object arg) {
            if ((this.SubmitWVEinzelpostenByIDsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitWVEinzelpostenByIDsCompleted(this, new SubmitWVEinzelpostenByIDsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.born.ch/KiSS/FAMOZ/PSCD/ClearCache", RequestNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", ResponseNamespace="http://www.born.ch/KiSS/FAMOZ/PSCD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearCache() {
            this.Invoke("ClearCache", new object[0]);
        }
        
        /// <remarks/>
        public void ClearCacheAsync() {
            this.ClearCacheAsync(null);
        }
        
        /// <remarks/>
        public void ClearCacheAsync(object userState) {
            if ((this.ClearCacheOperationCompleted == null)) {
                this.ClearCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearCacheOperationCompleted);
            }
            this.InvokeAsync("ClearCache", new object[0], this.ClearCacheOperationCompleted, userState);
        }
        
        private void OnClearCacheOperationCompleted(object arg) {
            if ((this.ClearCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearCacheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.born.ch/KiSS/FAMOZ/PSCD/")]
    public partial class ReturnMsg {
        
        private CreateObjectResult resultField;
        
        private string exceptionMessageField;
        
        private string warningMessageField;
        
        private int errorCodeField;
        
        /// <remarks/>
        public CreateObjectResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string ExceptionMessage {
            get {
                return this.exceptionMessageField;
            }
            set {
                this.exceptionMessageField = value;
            }
        }
        
        /// <remarks/>
        public string WarningMessage {
            get {
                return this.warningMessageField;
            }
            set {
                this.warningMessageField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.born.ch/KiSS/FAMOZ/PSCD/")]
    public enum CreateObjectResult {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        ExceptionOccured,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateAndSubmitBusinessPartnerPersonDataCompletedEventHandler(object sender, CreateAndSubmitBusinessPartnerPersonDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAndSubmitBusinessPartnerPersonDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAndSubmitBusinessPartnerPersonDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateAndSubmitBusinessPartnerInstitutionDataCompletedEventHandler(object sender, CreateAndSubmitBusinessPartnerInstitutionDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAndSubmitBusinessPartnerInstitutionDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAndSubmitBusinessPartnerInstitutionDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SubmitWhBelegeByIDsCompletedEventHandler(object sender, SubmitWhBelegeByIDsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitWhBelegeByIDsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitWhBelegeByIDsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void StornoNettoBelegeCompletedEventHandler(object sender, StornoNettoBelegeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StornoNettoBelegeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StornoNettoBelegeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void StornoBruttoBelegeCompletedEventHandler(object sender, StornoBruttoBelegeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StornoBruttoBelegeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StornoBruttoBelegeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SubmitAlimBelegeByIDsCompletedEventHandler(object sender, SubmitAlimBelegeByIDsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitAlimBelegeByIDsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitAlimBelegeByIDsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SubmitKgBelegeCompletedEventHandler(object sender, SubmitKgBelegeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitKgBelegeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitKgBelegeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void StornoKgBelegeCompletedEventHandler(object sender, StornoKgBelegeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StornoKgBelegeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StornoKgBelegeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SubmitWVEinzelpostenByIDsCompletedEventHandler(object sender, SubmitWVEinzelpostenByIDsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitWVEinzelpostenByIDsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitWVEinzelpostenByIDsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ClearCacheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591