CREATE TABLE [dbo].[PscdVerloreneBelegNummern](
	[BelegNr] [bigint] NOT NULL,
 CONSTRAINT [PK_PscdVerloreneBelegNummern] PRIMARY KEY CLUSTERED 
(
	[BelegNr] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
