CREATE TABLE [dbo].[PscdSentBaAdresse](
	[BaAdresseID] [int] NOT NULL,
	[BaAdresseTS_Sent] [binary](8) NOT NULL,
	[SentToPscd] [datetime] NOT NULL,
 CONSTRAINT [PK_PscdSentBaAdresse] PRIMARY KEY CLUSTERED 
(
	[BaAdresseID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON