CREATE TABLE [dbo].[PscdSentBaInstitution](
	[BaInstitutionID] [int] NOT NULL,
	[BaInstitutionTS_Sent] [binary](8) NOT NULL,
	[SentToPscd] [datetime] NOT NULL,
 CONSTRAINT [PK_PscdSentBaInstitution] PRIMARY KEY CLUSTERED 
(
	[BaInstitutionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON