CREATE TABLE [dbo].[XArchive](
	[ArchiveID] [int] IDENTITY(1,1) NOT NULL,
	[XArchiveTypeCode] [int] NULL CONSTRAINT [DF_XArchive_ArchiveTypCode]  DEFAULT ((1)),
	[Name] [varchar](80) NOT NULL,
	[Address] [text] NULL,
	[SortKey] [int] NOT NULL,
	[Remark] [text] NULL,
	[XArchiveTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_XArchive] PRIMARY KEY NONCLUSTERED 
(
	[ArchiveID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_XArchive]    Script Date: 11/23/2011 16:43:01 ******/
CREATE CLUSTERED INDEX [IX_XArchive] ON [dbo].[XArchive] 
(
	[SortKey] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]