CREATE TABLE [dbo].[XDocContext](
	[DocContextID] [int] IDENTITY(1,1) NOT NULL,
	[DocContextName] [varchar](50) NOT NULL,
	[Description] [varchar](500) NULL,
	[System] [bit] NOT NULL CONSTRAINT [DF_XDocContext_System]  DEFAULT ((0)),
	[XDocContextTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_XDocContext] PRIMARY KEY NONCLUSTERED 
(
	[DocContextID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [SYSTEM]
) ON [SYSTEM]

GO
SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_XDocContext]    Script Date: 11/23/2011 16:47:22 ******/
CREATE UNIQUE CLUSTERED INDEX [IX_XDocContext] ON [dbo].[XDocContext] 
(
	[DocContextName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [SYSTEM]