CREATE TABLE [dbo].[XHyperlink](
	[XHyperlinkID] [int] IDENTITY(1,1) NOT NULL,
	[Hyperlink] [varchar](8000) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[XHyperlinkTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_XHyperlink] PRIMARY KEY CLUSTERED 
(
	[XHyperlinkID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [SYSTEM]
) ON [SYSTEM]

GO
SET ANSI_PADDING ON