CREATE TABLE [dbo].[XUser_Archive](
	[UserID] [int] NOT NULL,
	[ArchiveID] [int] NOT NULL,
	[XUser_ArchiveTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_XUser_Archive] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[ArchiveID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[XUser_Archive]  WITH CHECK ADD  CONSTRAINT [FK_XUser_Archive_XArchive] FOREIGN KEY([ArchiveID])
REFERENCES [dbo].[XArchive] ([ArchiveID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[XUser_Archive] CHECK CONSTRAINT [FK_XUser_Archive_XArchive]
GO
ALTER TABLE [dbo].[XUser_Archive]  WITH CHECK ADD  CONSTRAINT [FK_XUser_Archive_XUser] FOREIGN KEY([UserID])
REFERENCES [dbo].[XUser] ([UserID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[XUser_Archive] CHECK CONSTRAINT [FK_XUser_Archive_XUser]