CREATE TABLE [dbo].[BaBeruf](
	[BaBerufID] [int] IDENTITY(1,1) NOT NULL,
	[Beruf] [varchar](200) NOT NULL,
	[BezeichnungM] [varchar](200) NULL,
	[BezeichnungW] [varchar](200) NULL,
	[SortKey] [int] NOT NULL,
	[BFSCode] [int] NOT NULL,
	[BaBerufTS] [timestamp] NOT NULL,
 CONSTRAINT [PK_BaBeruf] PRIMARY KEY CLUSTERED 
(
	[BaBerufID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_BaBeruf_Beruf]    Script Date: 11/23/2011 10:38:07 ******/
CREATE NONCLUSTERED INDEX [IX_BaBeruf_Beruf] ON [dbo].[BaBeruf] 
(
	[Beruf] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]