CREATE TABLE [dbo].[BaWVCode](
	[BaWVCodeID] [int] IDENTITY(1,1) NOT NULL,
	[BaPersonID] [int] NOT NULL,
	[DatumVon] [datetime] NOT NULL,
	[DatumBis] [datetime] NULL,
	[BaWVStatusCode] [int] NOT NULL CONSTRAINT [DF_BaWVCode_StatusCode]  DEFAULT ((1)),
	[WVCode] [int] NOT NULL,
	[BaBedID] [int] NOT NULL,
	[DatumRekurs] [datetime] NULL,
	[Bemerkung] [text] NULL,
	[SKZNummer] [varchar](50) NULL,
	[HeimatkantonNr] [varchar](50) NULL,
	[BaWVCodeTS] [timestamp] NOT NULL,
	[Migriert] [bit] NOT NULL CONSTRAINT [DF_BaWVCode_Migriert]  DEFAULT ((0)),
 CONSTRAINT [PK_BaWVCode] PRIMARY KEY CLUSTERED 
(
	[BaWVCodeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_BaWVCode_BaBedID]    Script Date: 11/23/2011 10:59:10 ******/
CREATE NONCLUSTERED INDEX [IX_BaWVCode_BaBedID] ON [dbo].[BaWVCode] 
(
	[BaBedID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

/****** Object:  Index [IX_BaWVCode_BaPersonID]    Script Date: 11/23/2011 10:59:10 ******/
CREATE NONCLUSTERED INDEX [IX_BaWVCode_BaPersonID] ON [dbo].[BaWVCode] 
(
	[BaPersonID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BaWVCode]  WITH CHECK ADD  CONSTRAINT [FK_BaWVCode_BaBED] FOREIGN KEY([BaBedID])
REFERENCES [dbo].[BaBED] ([BaBedID])
GO
ALTER TABLE [dbo].[BaWVCode] CHECK CONSTRAINT [FK_BaWVCode_BaBED]
GO
ALTER TABLE [dbo].[BaWVCode]  WITH CHECK ADD  CONSTRAINT [FK_BaWVCode_BaPerson] FOREIGN KEY([BaPersonID])
REFERENCES [dbo].[BaPerson] ([BaPersonID])
GO
ALTER TABLE [dbo].[BaWVCode] CHECK CONSTRAINT [FK_BaWVCode_BaPerson]