{DISPATCHER}
DropDatabase
CreateDatabase
CreateFileGroups
CreateUsers
CreateRoles:IFNSE=ZH
CreateTypes:IFNSE=Standard
CreateSchema

StringConcatenate_Assembly_mit_Conc_Functions

CreateDataIntegrityFunctions
CreateComputedColumnFunctions
CreateTables_Common
CreateTables

CreateFunctions_Common
CreateFunctions

CreateViews_Common
CreateViews

CreateStoredProcedures_Common
CreateStoredProcedures

InsertData_Common
InsertData

Rxxxx_2_PostReleaseDispatcher
