USE [master]
GO

-- create filegroups
ALTER DATABASE [{DBName}] ADD FILEGROUP DATEN1
GO
ALTER DATABASE [{DBName}] ADD FILEGROUP DATEN2
GO
ALTER DATABASE [{DBName}] ADD FILEGROUP DATEN3
GO
ALTER DATABASE [{DBName}] ADD FILEGROUP SYSTEM
GO
ALTER DATABASE [{DBName}] ADD FILEGROUP ARCHIV
GO
ALTER DATABASE [{DBName}] ADD FILEGROUP HISTORY
GO
ALTER DATABASE [{DBName}] ADD FILEGROUP LOGGING
GO

-- create file for filegroups and assign to filegroups
ALTER DATABASE [{DBName}] ADD FILE ( NAME = N'{DBName}_Daten1', FILENAME = N'{DBRootDirectory}\{DBName}\{DBName}_Daten1.ndf' , SIZE = 1MB , FILEGROWTH = 256MB ) TO FILEGROUP [DATEN1]
GO
ALTER DATABASE [{DBName}] ADD FILE ( NAME = N'{DBName}_Daten2', FILENAME = N'{DBRootDirectory}\{DBName}\{DBName}_Daten2.ndf' , SIZE = 1MB , FILEGROWTH = 256MB ) TO FILEGROUP [DATEN2]
GO
ALTER DATABASE [{DBName}] ADD FILE ( NAME = N'{DBName}_Daten3', FILENAME = N'{DBRootDirectory}\{DBName}\{DBName}_Daten3.ndf' , SIZE = 1MB , FILEGROWTH = 256MB ) TO FILEGROUP [DATEN3]
GO
ALTER DATABASE [{DBName}] ADD FILE ( NAME = N'{DBName}_System', FILENAME = N'{DBRootDirectory}\{DBName}\{DBName}_System.ndf' , SIZE = 1MB , FILEGROWTH = 256MB ) TO FILEGROUP [SYSTEM]
GO
ALTER DATABASE [{DBName}] ADD FILE ( NAME = N'{DBName}_Archiv', FILENAME = N'{DBRootDirectory}\{DBName}\{DBName}_Archiv.ndf' , SIZE = 1MB , FILEGROWTH = 256MB ) TO FILEGROUP [ARCHIV]
GO
ALTER DATABASE [{DBName}] ADD FILE ( NAME = N'{DBName}_History', FILENAME = N'{DBRootDirectory}\{DBName}\{DBName}_History.ndf' , SIZE = 1MB , FILEGROWTH = 256MB ) TO FILEGROUP [HISTORY]
GO
ALTER DATABASE [{DBName}] ADD FILE ( NAME = N'{DBName}_Logging', FILENAME = N'{DBRootDirectory}\{DBName}\{DBName}_Logging.ndf' , SIZE = 1MB , FILEGROWTH = 256MB ) TO FILEGROUP [LOGGING]
GO

-- switch back go origin database
USE [{DBName}]
GO