{DISPATCHER}
spDropObject

fnXGetUserRNDPwd
fnBaCKBaPersonRelationIntegrity
fnCKWshHaushaltPersonIntegrity
fnCKKbuTransferlaufRunningCount
fnSstCKSstZahlungseingang_KbuZahlungseingangID_UniqueOrNull
fnIkCKIkForderung_BgKostenartIntegrity
fnCKXLovCodeIntegrity
fnFaCKFaLeistungZugriffFaLeistungUserIntegrity
