/*===============================================================================================
  $Archive: /Database/KiSS4_PI_MasterDev/ServerAgent Jobs/KiSS4_PI_InsertSpecificUsersToAllOrgUnitsAsGuest.sql $
  $Author: Cjaeggi $
  $Modtime: 4.06.09 15:53 $
  $Revision: 1 $
=================================================================================================
  Description
-------------------------------------------------------------------------------------------------
  SUMMARY: Use this script to insert defined users into all orgunits as guest where they are not
           member or guest yet.
=================================================================================================
  $Log: /Database/KiSS4_PI_MasterDev/ServerAgent Jobs/KiSS4_PI_InsertSpecificUsersToAllOrgUnitsAsGuest.sql $
 * 
 * 1     4.06.09 15:55 Cjaeggi
 * #4805: Created new job to run on production-database
=================================================================================================*/

-------------------------------------------------------------------------------------------------
-- the following code was generated by managementstudio as script of defined job by wizard
-- 
-- INFO: see <changed> tags for changed items in comparisson with generated code
-------------------------------------------------------------------------------------------------
USE [msdb]
GO
/****** Object:  Job [KiSS4_PI_InsertSpecificUsersToAllOrgUnitsAsGuest]    Script Date: 06/04/2009 15:51:05 ******/
BEGIN TRANSACTION
DECLARE @ReturnCode INT
SELECT @ReturnCode = 0
/****** Object:  JobCategory [[Uncategorized (Local)]]]    Script Date: 06/04/2009 15:51:05 ******/
IF NOT EXISTS (SELECT name FROM msdb.dbo.syscategories WHERE name=N'[Uncategorized (Local)]' AND category_class=1)
BEGIN
EXEC @ReturnCode = msdb.dbo.sp_add_category @class=N'JOB', @type=N'LOCAL', @name=N'[Uncategorized (Local)]'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback

END

DECLARE @jobId BINARY(16)
EXEC @ReturnCode =  msdb.dbo.sp_add_job @job_name=N'KiSS4_PI_InsertSpecificUsersToAllOrgUnitsAsGuest', 
		@enabled=1, 
		@notify_level_eventlog=2, 
		@notify_level_email=0, 
		@notify_level_netsend=0, 
		@notify_level_page=0, 
		@delete_level=0, 
		@description=N'Insert defined users to all orgunits as guest where they are not member or guest yet.', 
		@category_name=N'[Uncategorized (Local)]', 
		@owner_login_name=N'sa', @job_id = @jobId OUTPUT
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
/****** Object:  Step [Insert user to all orgunits]    Script Date: 06/04/2009 15:51:06 ******/
EXEC @ReturnCode = msdb.dbo.sp_add_jobstep @job_id=@jobId, @step_name=N'Insert user to all orgunits', 
		@step_id=1, 
		@cmdexec_success_code=0, 
		@on_success_action=1, 
		@on_success_step_id=0, 
		@on_fail_action=2, 
		@on_fail_step_id=0, 
		@retry_attempts=1, 
		@retry_interval=1, 
		@os_run_priority=0, @subsystem=N'TSQL', 
		@command=N'-------------------------------------------------------------------------------------------------
-- start
-------------------------------------------------------------------------------------------------
PRINT (''start call: '' + CONVERT(VARCHAR, GETDATE(), 113))

-------------------------------------------------------------------------------------------------
-- execute action
-------------------------------------------------------------------------------------------------
-- new history version
INSERT INTO HistoryVersion (AppUser) VALUES (''dbjob'')

-- Get all org units where defined users are not member or guest
INSERT INTO XOrgUnit_User (OrgUnitID, UserID, OrgUnitMemberCode, MayInsert, MayUpdate, MayDelete)
  SELECT OrgUnitID         = ORG.OrgUnitID,  -- current orgunit where user is not member or guest
         UserID            = USR.UserID,     -- current user
         OrgUnitMemberCode = 3,              -- guest only
         MayInsert         = 1,              -- can insert
         MayUpdate         = 1,              -- can update
         MayDelete         = 1               -- can delete
  FROM dbo.XOrgUnit ORG WITH (READUNCOMMITTED)
    INNER JOIN dbo.XUser USR WITH (READUNCOMMITTED) ON USR.LogonName IN (''admin'', ''mawa'')
  WHERE ORG.OrgUnitID NOT IN (SELECT OrgUnitID
                              FROM XOrgUnit_User
                              WHERE UserID = USR.UserID) -- all users as defined in inner join
  ORDER BY USR.UserID

-------------------------------------------------------------------------------------------------
-- Done
-------------------------------------------------------------------------------------------------
PRINT (''done: '' + CONVERT(VARCHAR, GETDATE(), 113))', 
		@database_name=N'KiSS4_PI_Master',                          -- << <changed> here the database-name
		@flags=0
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_update_job @job_id = @jobId, @start_step_id = 1
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_add_jobschedule @job_id=@jobId, @name=N'Do job every morning', 
		@enabled=1, 
		@freq_type=4, 
		@freq_interval=1, 
		@freq_subday_type=1, 
		@freq_subday_interval=0, 
		@freq_relative_interval=0, 
		@freq_recurrence_factor=0, 
		@active_start_date=20090604, 
		@active_end_date=99991231, 
		@active_start_time=60000, 
		@active_end_time=235959
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_add_jobserver @job_id = @jobId, @server_name = N'(local)'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
COMMIT TRANSACTION
GOTO EndSave
QuitWithRollback:
    IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION
EndSave:
