CREATE TABLE [dbo].[BgPosition_R2](
	[BgPositionID] [int] IDENTITY(1,1) NOT NULL,
	[BgBudgetID] [int] NOT NULL,
	[BgKategorieCode] [int] NOT NULL,
	[DatumVon] [datetime] NULL,
	[DatumBis] [datetime] NULL,
	[BgPositionID_CopyOf] [int] NULL,
	[BgPositionID_Parent] [int] NULL,
	[BaPersonID] [int] NULL,
	[BaInstitutionID] [int] NULL,
	[DebitorBaPersonID] [int] NULL,
	[BgPositionsartID] [int] NULL,
	[Buchungstext] [varchar](100) NULL,
	[Betrag] [money] NOT NULL,
	[Reduktion] [money] NOT NULL,
	[Abzug] [money] NOT NULL,
	[MaxBeitragSD] [money] NOT NULL,
	[BgSpezkontoID] [int] NULL,
	[Bemerkung] [text] NULL,
	[VerwPeriodeVon] [datetime] NULL,
	[VerwPeriodeBis] [datetime] NULL,
	[FaelligAm] [datetime] NULL,
	[RechnungDatum] [datetime] NULL,
	[BetragAnfrage] [money] NULL,
	[VerwaltungSD] [bit] NOT NULL,
	[BgBewilligungStatusCode] [int] NULL,
	[BewilligtVon] [datetime] NULL,
	[BewilligtBis] [datetime] NULL,
	[BewilligtBetrag] [money] NULL,
	[FPPosition] [bit] NULL,
	[Value1] [sql_variant] NULL,
	[Value2] [sql_variant] NULL,
	[Value3] [sql_variant] NULL,
	[ErstelltUserID] [int] NULL,
	[ErstelltDatum] [datetime] NULL,
	[MutiertUserID] [int] NULL,
	[MutiertDatum] [datetime] NULL,
	[BgPositionTS] [timestamp] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING ON