CREATE TABLE [dbo].[WhSKZNummer](
	[WhSKZNummerID] [int] IDENTITY(1,1) NOT NULL,
	[BaPersonID] [int] NOT NULL,
	[SKZNummer] [int] NOT NULL,
	[DatumZuletztEingegeben] [datetime] NOT NULL,
 CONSTRAINT [PK_WhSKZNummer] PRIMARY KEY CLUSTERED 
(
	[WhSKZNummerID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Index [IX_WhSKZNummer_BaPersonID]    Script Date: 11/23/2011 16:41:17 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_WhSKZNummer_BaPersonID] ON [dbo].[WhSKZNummer] 
(
	[BaPersonID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]