//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiss.BusinessLogic.LocalResources.Kes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KesServiceRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KesServiceRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiss.BusinessLogic.LocalResources.Kes.KesServiceRes", typeof(KesServiceRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Abschlussdatum eines Auftrags darf nicht später als der {0:dd.MM.yyyy} sein oder es ist kein Enddatum erfasst..
        /// </summary>
        internal static string ErrorDatumBisAuftrag {
            get {
                return ResourceManager.GetString("ErrorDatumBisAuftrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es muss ein Grund ausgefüllt sein..
        /// </summary>
        internal static string ErrorDatumBisGrund {
            get {
                return ResourceManager.GetString("ErrorDatumBisGrund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Datum bis darf nicht kleiner sein als das Datum von ({0:dd.MM.yyyy})..
        /// </summary>
        internal static string ErrorDatumBisLeistung {
            get {
                return ResourceManager.GetString("ErrorDatumBisLeistung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Abschlussdatum einer Massnahme darf nicht später als der {0:dd.MM.yyyy} sein oder es ist kein Enddatum erfasst..
        /// </summary>
        internal static string ErrorDatumBisMassnahme {
            get {
                return ResourceManager.GetString("ErrorDatumBisMassnahme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Abschlussdatum einer Pflegekinderaufsicht darf nicht später als der {0:dd.MM.yyyy} sein oder es ist kein Enddatum erfasst..
        /// </summary>
        internal static string ErrorDatumBisPflegekinderaufsicht {
            get {
                return ResourceManager.GetString("ErrorDatumBisPflegekinderaufsicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Abschlussdatum einer Prävention darf nicht später als der {0:dd.MM.yyyy} sein oder es ist kein Enddatum erfasst..
        /// </summary>
        internal static string ErrorDatumBisPraevention {
            get {
                return ResourceManager.GetString("ErrorDatumBisPraevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Datum ist früher als das KES-Eröffnungsdatum ({0:dd.MM.yyyy})..
        /// </summary>
        internal static string ErrorDatumVon {
            get {
                return ResourceManager.GetString("ErrorDatumVon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Datensatz kann nicht gelöscht werden. Es sind noch abhängige Daten vorhanden..
        /// </summary>
        internal static string ErrorDeleteDatenExistieren {
            get {
                return ResourceManager.GetString("ErrorDeleteDatenExistieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Eintrag kann nicht gelöscht werden, da noch abhängige Dokumente existieren..
        /// </summary>
        internal static string ErrorDeleteDokumenteExistieren {
            get {
                return ResourceManager.GetString("ErrorDeleteDokumenteExistieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    - Mandatsführende Person.
        /// </summary>
        internal static string ErrorDeleteMandatsfuehrendePersonExistieren {
            get {
                return ResourceManager.GetString("ErrorDeleteMandatsfuehrendePersonExistieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    - Auftrag.
        /// </summary>
        internal static string ErrorDeleteMassnahmeAuftragExistieren {
            get {
                return ResourceManager.GetString("ErrorDeleteMassnahmeAuftragExistieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    - Bericht.
        /// </summary>
        internal static string ErrorDeleteMassnahmeBerichtExistieren {
            get {
                return ResourceManager.GetString("ErrorDeleteMassnahmeBerichtExistieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist kein Dokument zum Exportieren ausgewählt..
        /// </summary>
        internal static string ErrorKeinDokumentAusgewählt {
            get {
                return ResourceManager.GetString("ErrorKeinDokumentAusgewählt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Leistung. Bitte laden Sie den Fall neu..
        /// </summary>
        internal static string ErrorUngueltigeLeistung {
            get {
                return ResourceManager.GetString("ErrorUngueltigeLeistung", resourceCulture);
            }
        }
    }
}
