{DISPATCHER}

/*===============================================================================================
  $Revision: 3 $
=================================================================================================
  Description
-------------------------------------------------------------------------------------------------
  SUMMARY: Use this script to list all items to deploy for next release.
=================================================================================================*/

-- Cleanup migration tables
R4939_xxxx_Cleanup_OldMigrationTables


-------------------------------------------------------------------------------
-- release changes
-------------------------------------------------------------------------------

--KBE-1458 Maske Massnahmenführung in V-Modul integrieren
vwBaAdressate
R4939_KBE-1458_Update_XMenuItem
R4939_KBE-1458_Insert_BaInstitution
R4939_KBE-1458_Alter_KesMassnahme
R4939_KBE-1458_Insert_KesMassnahme
R4939_KBE-1458_Update_XModulTree
R4939_KBE-1458_Update_XLOVCode
vwTmVmLetzteMassnahme
vwTmVmMassnahme
vwTmVmLetzteBerPeriode
R4939_KBE-1458_Update_XBookmark

--KBE-1501 BFS Dossiernummer erweitern
fnBFSConcatDossierNr
spBFSGetDossierTree
R5239_KBE-1501_Update_BFSFrage

-- SOSTAT 2017
R41003_KBE-1453_Update_BFSFrage
fnBaIsValidVersichertennummer
R5305_SOSTAT-2017_Update_BFSFrage

--KBE-1520
fnBFSGetLeistungsartCode


--KFOR-873 ISO20022 Hausnummer Begünstigter in separatem Feld
vwKreditor
spWhBudget_CreateKbBuchung

--KBE-1493
R41006_KBE-1493_Insert_XConfig:IFNSE=BSS

--KBE-1492
R41006_KBE-1492_Add_Spezialrecht:IFNSE=BSS

--KBE-1519
R41006_KBE-1519_Insert_XConfig:IFNSE=BSS
R41006_KBE-1519_Update_LOV_TaskType:IFNSE=BSS
R41006_KBE-1519_Update_LOV_XTaskAutoGenerated:IFNSE=BSS
spPendenzCheck_Person1
spXTask_Create



