apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kiss4web-dev
spec:
  template:
    metadata:
      labels:
        app: kiss4web
    spec:
      containers:
      - name: kiss4web
        image: aventis.azurecr.io/kiss4web:latest
        ports:
        - containerPort: 80   
---
apiVersion: v1
kind: Service
metadata:
  name: kiss4web
spec:
  ports:
  - port: 80
  selector:
    app: kiss4web