//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Kiss.DbContext
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(FaLeistung))]
    [KnownType(typeof(FsDienstleistungspaket))]
    [KnownType(typeof(XUser))]
    public partial class FaPhase : PocoEntity, IAutoIdentityEntity<int>, IAuditableEntity
    {
        public int AutoIdentityID 
        {
            get{ return FaPhaseID; } 
        }
    
        [DataMember]
        private int _faPhaseID;
        public int FaPhaseID
        {
            get { return _faPhaseID; }
            set
            {
                if (_faPhaseID != value)
                {
                    _faPhaseID = value;
                    RaisePropertyChanged("FaPhaseID");
                }
            }
        }
    
        [DataMember]
        private int _faLeistungID;
        public int FaLeistungID
        {
            get { return _faLeistungID; }
            set
            {
                if (_faLeistungID != value)
                {
                    _faLeistungID = value;
                    RaisePropertyChanged("FaLeistungID");
                    if (FaLeistung != null && FaLeistung.FaLeistungID != value)
                    {
                        FaLeistung = null;
                    }
                }
            }
        }
    
        [DataMember]
        private Nullable<int> _userID;
        public Nullable<int> UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    _userID = value;
                    RaisePropertyChanged("UserID");
                    if (XUser != null && XUser.UserID != value)
                    {
                        XUser = null;
                    }
                }
            }
        }
    
        [DataMember]
        private Nullable<int> _fsDienstleistungspaketID_Zugewiesen;
        public Nullable<int> FsDienstleistungspaketID_Zugewiesen
        {
            get { return _fsDienstleistungspaketID_Zugewiesen; }
            set
            {
                if (_fsDienstleistungspaketID_Zugewiesen != value)
                {
                    _fsDienstleistungspaketID_Zugewiesen = value;
                    RaisePropertyChanged("FsDienstleistungspaketID_Zugewiesen");
                    if (FsDienstleistungspaket_Zugewiesen != null && FsDienstleistungspaket_Zugewiesen.FsDienstleistungspaketID != value)
                    {
                        FsDienstleistungspaket_Zugewiesen = null;
                    }
                }
            }
        }
    
        [DataMember]
        private Nullable<int> _fsDienstleistungspaketID_Bedarf;
        public Nullable<int> FsDienstleistungspaketID_Bedarf
        {
            get { return _fsDienstleistungspaketID_Bedarf; }
            set
            {
                if (_fsDienstleistungspaketID_Bedarf != value)
                {
                    _fsDienstleistungspaketID_Bedarf = value;
                    RaisePropertyChanged("FsDienstleistungspaketID_Bedarf");
                    if (FsDienstleistungspaket_Bedarf != null && FsDienstleistungspaket_Bedarf.FsDienstleistungspaketID != value)
                    {
                        FsDienstleistungspaket_Bedarf = null;
                    }
                }
            }
        }
    
        [DataMember]
        private int _faPhaseCode;
        public int FaPhaseCode
        {
            get { return _faPhaseCode; }
            set
            {
                if (_faPhaseCode != value)
                {
                    _faPhaseCode = value;
                    RaisePropertyChanged("FaPhaseCode");
                }
            }
        }
    
        [DataMember]
        private System.DateTime _datumVon;
        public System.DateTime DatumVon
        {
            get { return _datumVon; }
            set
            {
                if (_datumVon != value)
                {
                    _datumVon = value;
                    RaisePropertyChanged("DatumVon");
                }
            }
        }
    
        [DataMember]
        private Nullable<System.DateTime> _datumBis;
        public Nullable<System.DateTime> DatumBis
        {
            get { return _datumBis; }
            set
            {
                if (_datumBis != value)
                {
                    _datumBis = value;
                    RaisePropertyChanged("DatumBis");
                }
            }
        }
    
        [DataMember]
        private Nullable<int> _abschlussGrundCode;
        public Nullable<int> AbschlussGrundCode
        {
            get { return _abschlussGrundCode; }
            set
            {
                if (_abschlussGrundCode != value)
                {
                    _abschlussGrundCode = value;
                    RaisePropertyChanged("AbschlussGrundCode");
                }
            }
        }
    
        [DataMember]
        private string _bemerkung;
        public string Bemerkung
        {
            get { return _bemerkung; }
            set
            {
                if (_bemerkung != value)
                {
                    _bemerkung = value;
                    RaisePropertyChanged("Bemerkung");
                }
            }
        }
    
        [DataMember]
        private string _creator;
        public string Creator
        {
            get { return _creator; }
            set
            {
                if (_creator != value)
                {
                    _creator = value;
                    RaisePropertyChanged("Creator");
                }
            }
        }
    
        [DataMember]
        private System.DateTime _created;
        public System.DateTime Created
        {
            get { return _created; }
            set
            {
                if (_created != value)
                {
                    _created = value;
                    RaisePropertyChanged("Created");
                }
            }
        }
    
        [DataMember]
        private string _modifier;
        public string Modifier
        {
            get { return _modifier; }
            set
            {
                if (_modifier != value)
                {
                    _modifier = value;
                    RaisePropertyChanged("Modifier");
                }
            }
        }
    
        [DataMember]
        private System.DateTime _modified;
        public System.DateTime Modified
        {
            get { return _modified; }
            set
            {
                if (_modified != value)
                {
                    _modified = value;
                    RaisePropertyChanged("Modified");
                }
            }
        }
    
        [DataMember]
        private byte[] _faPhaseTS;
        public byte[] FaPhaseTS
        {
            get { return _faPhaseTS; }
            set
            {
                if (_faPhaseTS != value)
                {
                    _faPhaseTS = value;
                    RaisePropertyChanged("FaPhaseTS");
                }
            }
        }
    
    
        [DataMember]
        private FaLeistung _faLeistung;
        public virtual FaLeistung FaLeistung
        {
            get { return _faLeistung; }
            set
            {
                if (_faLeistung != value)
                {
                    _faLeistung = value;
                    RaisePropertyChanged("FaLeistung");
    
                    if (value != null)
                    {
                        FaLeistungID = value.FaLeistungID;
                    }
                }
            }
        }
        [DataMember]
        private FsDienstleistungspaket _fsDienstleistungspaket_Bedarf;
        public virtual FsDienstleistungspaket FsDienstleistungspaket_Bedarf
        {
            get { return _fsDienstleistungspaket_Bedarf; }
            set
            {
                if (_fsDienstleistungspaket_Bedarf != value)
                {
                    _fsDienstleistungspaket_Bedarf = value;
                    RaisePropertyChanged("FsDienstleistungspaket_Bedarf");
    
                    if (value != null)
                    {
                        FsDienstleistungspaketID_Bedarf = value.FsDienstleistungspaketID;
                    }
                }
            }
        }
        [DataMember]
        private FsDienstleistungspaket _fsDienstleistungspaket_Zugewiesen;
        public virtual FsDienstleistungspaket FsDienstleistungspaket_Zugewiesen
        {
            get { return _fsDienstleistungspaket_Zugewiesen; }
            set
            {
                if (_fsDienstleistungspaket_Zugewiesen != value)
                {
                    _fsDienstleistungspaket_Zugewiesen = value;
                    RaisePropertyChanged("FsDienstleistungspaket_Zugewiesen");
    
                    if (value != null)
                    {
                        FsDienstleistungspaketID_Zugewiesen = value.FsDienstleistungspaketID;
                    }
                }
            }
        }
        [DataMember]
        private XUser _xUser;
        public virtual XUser XUser
        {
            get { return _xUser; }
            set
            {
                if (_xUser != value)
                {
                    _xUser = value;
                    RaisePropertyChanged("XUser");
    
                    if (value != null)
                    {
                        UserID = value.UserID;
                    }
                }
            }
        }
    }
    
}
